# Bitacoras onomásticas SEMEFO 1968-1982
# Catálogo procedencia

In [1]:
import pandas as pd
from numpy import nan
from helper_pandas import simplify_string

In [2]:
def df_columns_to_dict(df_file, col_key, col_value, **kwargs):
    df = pd.read_csv(df_file, **kwargs)
    dic = {k:v for k,v in zip(df[col_key], df[col_value])}
    return dic

data = pd.read_pickle('data_clean/SEMEFO_BO_all.pkl')
data = data['Diagnostico']
data

f_replace = 'catalogos/catalogo_diagnostico_separados.csv'
replace = df_columns_to_dict(f_replace, 'Diagnostico', 'Separado')
data = data.replace(replace).replace({' x ', '+', ' y ', '+'}, regex=True)

data = [d.split('+') for d in data.to_list()]
data = [item for sublist in data for item in sublist]
data

data = pd.Series(data)
data = data.apply(simplify_string, str_case=None)
data = data.value_counts().reset_index()
data.columns = ['Diagnostico','Frequencia']
data['Upper'] = data['Diagnostico'].apply(simplify_string, str_case='upper', remove_special=True)
data

                     Diagnostico  Frequencia                       Upper
0                            S-D       55894                         S D
1                             TM        7990                          TM
2                            TCE        6893                         TCE
3                             BN        5081                          BN
4                            CVG        1444                         CVG
...                          ...         ...                         ...
2686                      HPAFPc           1                      HPAFPC
2687  BN Cisticerco sis cerebral           1  BN CISTICERCO SIS CEREBRAL
2688                         TQE           1                         TQE
2689                      PNyLOC           1                      PNYLOC
2690            AQxElectrocucion           1            AQXELECTROCUCION

[2691 rows x 3 columns]

In [3]:
cat = pd.read_csv('catalogos/catalogo_diagnostico_simplificado.csv')
cat['Upper'] = cat['Diagnostico'].apply(simplify_string, str_case='upper', remove_special=True)
cat

,Diagnostico,Equivalencia,Extendido,Upper
0,S-D,S-D,sin datos,S D
1,Aborto,ABORTO,aborto,ABORTO
2,AQ,AQ,amputacion quirurgica,AQ
3,AQxT,AQXT,amputacion quirurgica consecutiva al traumatismo,AQXT
4,AOxT,AQXT,amputacion quirurgica consecutiva al traumatismo,AOXT
...,...,...,...,...
233,Trombosis,TROMBOSIS,trombosis,TROMBOSIS
234,TB,TB,tuberculosis,TB
235,Tb,TB,tuberculosis,TB
236,VE,VE,varices esofagicas,VE
237,Villa,VILLA,villa,VILLA

In [4]:
data_ = data.merge(cat, on='Upper', how=)
data_

,Diagnostico_x,Frequencia,Upper,Diagnostico_y,Equivalencia,Extendido
0,S-D,55894,S D,S-D,S-D,sin datos
1,S-d,2,S D,S-D,S-D,sin datos
2,S.d,1,S D,S-D,S-D,sin datos
3,TM,7990,TM,TM,TM,traumatismo multiple
4,TCE,6893,TCE,TCE,TCE,traumatismo craneo encefalico
...,...,...,...,...,...,...
422,HIPCPS,1,HIPCPS,HIPCPs,HIPC,herida punzo cortante
423,Apendicitis,5,APENDICITIS,Apendicitis,APENDICITIS,apendicitis
424,Electrocusion,5,ELECTROCUSION,Electrocusion,ELECTROCUCION,electrocucion
425,TCervical,5,TCERVICAL,TCervical,TCERV,traumatismo cervical
426,TMsI,5,TMSI,TMsI,TMI,traumatismo miembro inferior

In [5]:
data_.notna().sum()

Diagnostico_x    427
Frequencia       427
Upper            427
Diagnostico_y    427
Equivalencia     427
Extendido        427
dtype: int64