# Bitacoras onomásticas SEMEFO 1968-1982

In [1]:
import pandas as pd
from numpy import nan
from helper_pandas import simplify_string

In [2]:
def df_columns_to_dict(df_file, col_key, col_value, **kwargs):
    df = pd.read_csv(df_file, **kwargs)
    dic = {k:v for k,v in zip(df[col_key], df[col_value])}
    return dic

df = pd.read_pickle('data_clean/SEMEFO_BO_all.pkl')
df

,ID,Numero_progresivo,Nombre_completo,Primer_apellido,Segundo_apellido,Nombres_propios,Fecha,Fecha_clean,Fecha_error,Expediente_Semefo,...,Edad,Edad_clean,Edad_error,Tipo_restos,Bitacora_ingresos,Pagina_PDF,Pagina_PDF_clean,Pagina_PDF_error,Foja,Observaciones
0,BO_1968_00001,NaN,acosta ortega teresa,acosta,ortega,teresa,1968-01-03,1968-01-03,NaN,37,...,S-D,NaN,NaN,Cadáver,semefo_df_bo_1968,2,2.0,NaN,1,NaN
1,BO_1968_00002,NaN,avila de cuestas catalina,avila,de cuestas,catalina,1968-01-05,1968-01-05,NaN,58,...,S-D,NaN,NaN,Cadáver,semefo_df_bo_1968,2,2.0,NaN,1,NaN
2,BO_1968_00003,NaN,arzate paredes juan,arzate,paredes,juan,1968-01-07,1968-01-07,NaN,83,...,S-D,NaN,NaN,Cadáver,semefo_df_bo_1968,2,2.0,NaN,1,NaN
3,BO_1968_00004,NaN,alvarez martinez isaac,alvarez,martinez,isaac,1968-01-07,1968-01-07,NaN,86,...,S-D,NaN,NaN,Cadáver,semefo_df_bo_1968,2,2.0,NaN,1,NaN
4,BO_1968_00005,NaN,arellano viuda de campos ma.,arellano,viuda de campos,ma.,1968-01-07,1968-01-07,NaN,88,...,S-D,NaN,NaN,Cadáver,semefo_df_bo_1968,2,2.0,NaN,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96855,BO_1982_07489,NaN,placenta,s-d,s-d,s-d,1982-06-05,1982-06-05,NaN,3079,...,S-D,NaN,NaN,Miembros,semefo_df_bo_1982,251,251.0,NaN,156,NaN
96856,BO_1982_07490,NaN,5 dedos del pie derecho de desconocido,s-d,s-d,s-d,1982-06-05,1982-06-05,NaN,3060,...,S-D,NaN,NaN,Miembros,semefo_df_bo_1982,251,251.0,NaN,156,NaN
96857,BO_1982_07491,NaN,dedo de desconocido,s-d,s-d,s-d,1982-11-19,1982-11-19,NaN,6389,...,S-D,NaN,NaN,Miembros,semefo_df_bo_1982,251,251.0,NaN,156,NaN
96858,BO_1982_07492,NaN,4 dedos de desconocido,s-d,s-d,s-d,1982-11-28,1982-11-28,NaN,6528,...,S-D,NaN,NaN,Miembros,semefo_df_bo_1982,251,251.0,NaN,156,NaN
96859,BO_1982_07493,NaN,osamenta de desconocido,s-d,s-d,s-d,1982-10-11,1982-10-11,NaN,5629,...,S-D,NaN,NaN,Cadáver,semefo_df_bo_1982,251,251.0,NaN,156,no se recibio necropsia. es una osamenta.

# Catálogo procedencia

In [3]:
data = df.loc[df['Procedencia_clean'].isna(), 'Procedencia']
data = data.value_counts().reset_index()
data.columns = ['Value','Freq']
data['Upper'] = data['Value'].apply( simplify_string, str_case='upper')
data['Simple'] = data['Value'].apply( simplify_string, str_case='upper', remove_special=True)
data

              Value  Freq           Upper          Simple
0             IZA I     2           IZA I           IZA I
1     2a Delegacion     2   2A DELEGACION   2A DELEGACION
2    7a. Delegacion     2  7A. DELEGACION   7A DELEGACION
3     4a Delegacion     2   4A DELEGACION   4A DELEGACION
4    14a Delegacion     2  14A DELEGACION  14A DELEGACION
..              ...   ...             ...             ...
399           BT-CH     1           BT-CH           BT CH
400     MH-CR VC-HB     1     MH-CR VC-HB     MH CR VC HB
401      BJ-1 MH-CR     1      BJ-1 MH-CR      BJ 1 MH CR
402         VC-HB-2     1         VC-HB-2         VC HB 2
403             27A     1             27A             27A

[404 rows x 4 columns]

In [4]:
cat = pd.read_csv('catalogos/catalogo_procedencia.csv')
cat['Upper'] = cat['Procedencia'].apply( simplify_string, str_case='upper').apply(lambda s: s.replace('.',''))
cat['Simple'] = cat['Procedencia'].apply( simplify_string, str_case='upper', remove_special=True)
cat = cat.drop(['Direccion','Alcaldia','Procedencia'], axis=1).rename({'Equivalencia':'Value'}, axis=1)
cat

    Value       Upper      Simple
0     10A         10A         10A
1     10A          10          10
2     10A   10A DELEG   10A DELEG
3     10A         10A         10A
4     10A     10A DEL     10A DEL
..    ...         ...         ...
400    VO   V OBREGON   V OBREGON
401   X-1         X-1         X 1
402   X-1         X-I         X I
403    XO  XOCHIMILCO  XOCHIMILCO
404    XO          XO          XO

[405 rows x 3 columns]

In [5]:
data = data.merge(cat, on='Upper', how='left', suffixes=('', '_upper'))
data = data.merge(cat, on='Simple', how='left', suffixes=('', '_simple'))
data

,Value,Freq,Upper,Simple,Value_upper,Simple_upper,Value_simple,Upper_simple
0,IZA I,2,IZA I,IZA I,NaN,NaN,IZA-1,IZA-I
1,IZA I,2,IZA I,IZA I,NaN,NaN,IZA-1,IZA-I-
2,2a Delegacion,2,2A DELEGACION,2A DELEGACION,NaN,NaN,NaN,NaN
3,7a. Delegacion,2,7A. DELEGACION,7A DELEGACION,NaN,NaN,7A,7A DELEGACION
4,4a Delegacion,2,4A DELEGACION,4A DELEGACION,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
447,BT-CH,1,BT-CH,BT CH,NaN,NaN,NaN,NaN
448,MH-CR VC-HB,1,MH-CR VC-HB,MH CR VC HB,NaN,NaN,NaN,NaN
449,BJ-1 MH-CR,1,BJ-1 MH-CR,BJ 1 MH CR,NaN,NaN,NaN,NaN
450,VC-HB-2,1,VC-HB-2,VC HB 2,NaN,NaN,NaN,NaN
451,27A,1,27A,27A,27A,27A,27A,27A

In [6]:
data.to_csv('catalogos/catalogo_procedencia_lowfreq.csv', index=False)
data.notna().sum()

Value           452
Freq            452
Upper           452
Simple          452
Value_upper      23
Simple_upper     23
Value_simple    116
Upper_simple    116
dtype: int64

# Catálogo diagnostico

In [7]:
data = df.loc[df['Diagnostico_estandar'].isna(), 'Diagnostico']
data = data.value_counts().reset_index()
data.columns = ['Value','Freq']
#data['Upper'] = data['Value'].apply( simplify_string, str_case='upper')
#data['Simple'] = data['Value'].apply( simplify_string, str_case='upper', remove_special=True)
data

         Value  Freq
0        BN+CH   715
1       TCE+BN   569
2      Quem+BN   340
3        TM+BN   266
4        PN+CH   167
...        ...   ...
3712    InfPul     0
3713  Inf. Pul     0
3714   Inf Pul     0
3715       Inf     0
3716       tct     0

[3717 rows x 2 columns]

In [8]:
set([s.count('+') for s in data['Value']])

{0, 1, 2, 3, 4}

In [9]:
cat = pd.read_csv('catalogos/catalogo_diagnostico_simplificado.csv')
cat['Upper'] = cat['Diagnostico'].apply( simplify_string, str_case='upper')
cat['Simple'] = cat['Diagnostico'].apply( simplify_string, str_case='upper', remove_special=True)
cat = cat.drop(['Extendido'], axis=1).rename({'Equivalencia':'Value'}, axis=1)
cat

    Diagnostico   Value     Upper    Simple
0           S-D     S-D       S-D       S D
1            TM      TM        TM        TM
2           TCE     TCE       TCE       TCE
3            BN      BN        BN        BN
4           CVG     CVG       CVG       CVG
..          ...     ...       ...       ...
345     HsPAFps    HPAF   HSPAFPS   HSPAFPS
346        ANeN    ANEN      ANEN      ANEN
347          EN     ENT        EN        EN
348    TCCermed    TCCM  TCCERMED  TCCERMED
349      HPAFPc  HPAFPC    HPAFPC    HPAFPC

[350 rows x 4 columns]