# Bitacoras onomásticas SEMEFO 1968-1982

In [1]:
import pandas as pd
from numpy import nan
from helper_pandas import simplify_string

In [2]:
df = pd.read_pickle('data_clean/SEMEFO_BO_all.pkl')
df

,ID,Numero_progresivo,Nombre_completo,Primer_apellido,Segundo_apellido,Nombres_propios,Fecha,Fecha_clean,Fecha_error,Expediente_Semefo,...,Edad,Edad_clean,Edad_error,Tipo_restos,Bitacora_ingresos,Pagina_PDF,Pagina_PDF_clean,Pagina_PDF_error,Foja,Observaciones
0,BO_1968_00001,NaN,acosta ortega teresa,acosta,ortega,teresa,1968-01-03,1968-01-03,NaN,37,...,S-D,NaN,NaN,Cadáver,semefo_df_bo_1968,2,2.0,NaN,1,NaN
1,BO_1968_00002,NaN,avila de cuestas catalina,avila,de cuestas,catalina,1968-01-05,1968-01-05,NaN,58,...,S-D,NaN,NaN,Cadáver,semefo_df_bo_1968,2,2.0,NaN,1,NaN
2,BO_1968_00003,NaN,arzate paredes juan,arzate,paredes,juan,1968-01-07,1968-01-07,NaN,83,...,S-D,NaN,NaN,Cadáver,semefo_df_bo_1968,2,2.0,NaN,1,NaN
3,BO_1968_00004,NaN,alvarez martinez isaac,alvarez,martinez,isaac,1968-01-07,1968-01-07,NaN,86,...,S-D,NaN,NaN,Cadáver,semefo_df_bo_1968,2,2.0,NaN,1,NaN
4,BO_1968_00005,NaN,arellano viuda de campos ma.,arellano,viuda de campos,ma.,1968-01-07,1968-01-07,NaN,88,...,S-D,NaN,NaN,Cadáver,semefo_df_bo_1968,2,2.0,NaN,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96855,BO_1982_07489,NaN,placenta,s-d,s-d,s-d,1982-06-05,1982-06-05,NaN,3079,...,S-D,NaN,NaN,Miembros,semefo_df_bo_1982,251,251.0,NaN,156,NaN
96856,BO_1982_07490,NaN,5 dedos del pie derecho de desconocido,s-d,s-d,s-d,1982-06-05,1982-06-05,NaN,3060,...,S-D,NaN,NaN,Miembros,semefo_df_bo_1982,251,251.0,NaN,156,NaN
96857,BO_1982_07491,NaN,dedo de desconocido,s-d,s-d,s-d,1982-11-19,1982-11-19,NaN,6389,...,S-D,NaN,NaN,Miembros,semefo_df_bo_1982,251,251.0,NaN,156,NaN
96858,BO_1982_07492,NaN,4 dedos de desconocido,s-d,s-d,s-d,1982-11-28,1982-11-28,NaN,6528,...,S-D,NaN,NaN,Miembros,semefo_df_bo_1982,251,251.0,NaN,156,NaN
96859,BO_1982_07493,NaN,osamenta de desconocido,s-d,s-d,s-d,1982-10-11,1982-10-11,NaN,5629,...,S-D,NaN,NaN,Cadáver,semefo_df_bo_1982,251,251.0,NaN,156,no se recibio necropsia. es una osamenta.

# Catálogo procedencia

In [3]:
data = df.loc[df['Procedencia_clean'].isna(), 'Procedencia']
data = data.value_counts().reset_index()
data.columns = ['Value','Freq']
data['Upper'] = data['Value'].apply( simplify_string, str_case='upper')
data['Simple'] = data['Value'].apply( simplify_string, str_case='upper', remove_special=True)
data

              Value  Freq           Upper          Simple
0             IZA I     2           IZA I           IZA I
1     2a Delegacion     2   2A DELEGACION   2A DELEGACION
2    7a. Delegacion     2  7A. DELEGACION   7A DELEGACION
3     4a Delegacion     2   4A DELEGACION   4A DELEGACION
4    14a Delegacion     2  14A DELEGACION  14A DELEGACION
..              ...   ...             ...             ...
399           BT-CH     1           BT-CH           BT CH
400     MH-CR VC-HB     1     MH-CR VC-HB     MH CR VC HB
401      BJ-1 MH-CR     1      BJ-1 MH-CR      BJ 1 MH CR
402         VC-HB-2     1         VC-HB-2         VC HB 2
403             27A     1             27A             27A

[404 rows x 4 columns]

In [4]:
cat = pd.read_csv('catalogos/catalogo_procedencia.csv')
cat['Upper'] = cat['Procedencia'].apply( simplify_string, str_case='upper').apply(lambda s: s.replace('.',''))
cat['Simple'] = cat['Procedencia'].apply( simplify_string, str_case='upper', remove_special=True)
cat = cat.drop(['Direccion','Alcaldia','Procedencia'], axis=1).rename({'Equivalencia':'Value'}, axis=1)
cat

    Value       Upper      Simple
0     10A         10A         10A
1     10A          10          10
2     10A   10A DELEG   10A DELEG
3     10A         10A         10A
4     10A     10A DEL     10A DEL
..    ...         ...         ...
400    VO   V OBREGON   V OBREGON
401   X-1         X-1         X 1
402   X-1         X-I         X I
403    XO  XOCHIMILCO  XOCHIMILCO
404    XO          XO          XO

[405 rows x 3 columns]

In [5]:
data = data.merge(cat, on='Upper', how='left', suffixes=('', '_upper'))
data = data.merge(cat, on='Simple', how='left', suffixes=('', '_simple'))
data

,Value,Freq,Upper,Simple,Value_upper,Simple_upper,Value_simple,Upper_simple
0,IZA I,2,IZA I,IZA I,NaN,NaN,IZA-1,IZA-I
1,IZA I,2,IZA I,IZA I,NaN,NaN,IZA-1,IZA-I-
2,2a Delegacion,2,2A DELEGACION,2A DELEGACION,NaN,NaN,NaN,NaN
3,7a. Delegacion,2,7A. DELEGACION,7A DELEGACION,NaN,NaN,7A,7A DELEGACION
4,4a Delegacion,2,4A DELEGACION,4A DELEGACION,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
447,BT-CH,1,BT-CH,BT CH,NaN,NaN,NaN,NaN
448,MH-CR VC-HB,1,MH-CR VC-HB,MH CR VC HB,NaN,NaN,NaN,NaN
449,BJ-1 MH-CR,1,BJ-1 MH-CR,BJ 1 MH CR,NaN,NaN,NaN,NaN
450,VC-HB-2,1,VC-HB-2,VC HB 2,NaN,NaN,NaN,NaN
451,27A,1,27A,27A,27A,27A,27A,27A

In [6]:
data.to_csv('catalogos/catalogo_procedencia_lowfreq.csv', index=False)
data.notna().sum()

Value           452
Freq            452
Upper           452
Simple          452
Value_upper      23
Simple_upper     23
Value_simple    116
Upper_simple    116
dtype: int64

# Catálogo diagnostico

In [7]:
def break_and_simplify(row):
    row = row.to_list()
    row[0] = row[0].replace(' x ','+').replace(' y ','+')
    row = row + row[0].split('+')
    row = [simplify_string(s, str_case=None) for s in row]
    return row

data = df.loc[df['Diagnostico_estandar'].isna(), 'Diagnostico']
data = data.value_counts().reset_index()
data = [break_and_simplify(row) for i,row in data.iterrows()]
col_sigla = [f'Sig{i}' for i in range(5)]
data = pd.DataFrame( data, columns = ['Value','Freq']+col_sigla )
data = data.replace('',None)
data

         Value  Freq      Sig0  Sig1  Sig2  Sig3  Sig4
0        BN+CH   715        BN    CH  None  None  None
1       TCE+BN   569       TCE    BN  None  None  None
2      Quem+BN   340      Quem    BN  None  None  None
3        TM+BN   266        TM    BN  None  None  None
4        PN+CH   167        PN    CH  None  None  None
...        ...   ...       ...   ...   ...   ...   ...
3712    InfPul     0    InfPul  None  None  None  None
3713  Inf. Pul     0  Inf. Pul  None  None  None  None
3714   Inf Pul     0   Inf Pul  None  None  None  None
3715       Inf     0       Inf  None  None  None  None
3716       tct     0       tct  None  None  None  None

[3717 rows x 7 columns]

In [8]:
cat = pd.read_csv('catalogos/catalogo_diagnostico_simplificado.csv')
cat

    Diagnostico Equivalencia                         Extendido
0             A            A       diagnostico no determinable
1        Aborto       ABORTO                            aborto
2        ABORTO       ABORTO                            aborto
3            AE           AE        asfixia por estrangulacion
4            AN           AN                            anemia
..          ...          ...                               ...
345         TTA          TTA         traumatismo torax abdomen
346        TTAP         TTAP  traumatismo torax abdomen pelvis
347         TTP          TTP          traumatismo torax pelvis
348          VE           VE                varices esofagicas
349       Villa        VILLA                             villa

[350 rows x 3 columns]

In [9]:
from helper_pandas import join_strings_with_nans

equi_dict = {k:v for k,v in zip(cat['Diagnostico'], cat['Equivalencia'])}
ext_dict = {k:v for k,v in zip(cat['Diagnostico'], cat['Extendido'])}
for i in range(5):
    data[f'Std{i}'] = data[f'Sig{i}'].map(equi_dict)
    data[f'Ext{i}'] = data[f'Sig{i}'].map(ext_dict)
    data[f'Fail{i}'] = data[f'Sig{i}'].where( data[f'Sig{i}'].isna().ne( data[f'Std{i}'].isna() ) )

data['Value_join'] = data[ [f'Std{i}' for i in range(5)] + [f'Fail{i}' for i in range(5)] ] \
                         .apply(join_strings_with_nans, sep='+', axis=1)
data['Ext_join'] = data[ [f'Ext{i}' for i in range(5)] + [f'Fail{i}' for i in range(5)] ] \
                         .apply(join_strings_with_nans, sep=' + ', axis=1)
data

,Value,Freq,Sig0,Sig1,Sig2,Sig3,Sig4,Std0,Ext0,Fail0,...,Ext2,Fail2,Std3,Ext3,Fail3,Std4,Ext4,Fail4,Value_join,Ext_join
0,BN+CH,715,BN,CH,None,None,None,BN,bronconeumonia,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BN+CH,bronconeumonia + cirrosis hepatica
1,TCE+BN,569,TCE,BN,None,None,None,TCE,traumatismo craneo encefalico,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TCE+BN,traumatismo craneo encefalico + bronconeumonia
2,Quem+BN,340,Quem,BN,None,None,None,QUEM,quemaduras,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,QUEM+BN,quemaduras + bronconeumonia
3,TM+BN,266,TM,BN,None,None,None,TM,traumatismo multiple,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TM+BN,traumatismo multiple + bronconeumonia
4,PN+CH,167,PN,CH,None,None,None,PN,pleuro pneumonia,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PN+CH,pleuro pneumonia + cirrosis hepatica
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3712,InfPul,0,InfPul,None,None,None,None,INFPUL,infeccion pulmon,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INFPUL,infeccion pulmon
3713,Inf. Pul,0,Inf. Pul,None,None,None,None,INFPUL,infeccion pulmon,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INFPUL,infeccion pulmon
3714,Inf Pul,0,Inf Pul,None,None,None,None,INFPUL,infeccion pulmon,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INFPUL,infeccion pulmon
3715,Inf,0,Inf,None,None,None,None,INF,infeccion,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INF,infeccion
3716,tct,0,tct,None,None,None,None,TCT,traumatismo craneo torax,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TCT,traumatismo craneo torax

In [10]:
data.to_csv('catalogos/catalogo_diagnostico.csv', index=False)
data.notna().sum()

Value         3717
Freq          3717
Sig0          3717
Sig1          1559
Sig2           114
Sig3             3
Sig4             1
Std0          1613
Ext0          1613
Fail0         2104
Std1          1142
Ext1          1142
Fail1          417
Std2            92
Ext2            92
Fail2           22
Std3             3
Ext3             3
Fail3            0
Std4             0
Ext4             0
Fail4            1
Value_join    3717
Ext_join      3717
dtype: int64

In [11]:
lowfreq = pd.concat([data[f'Fail{i}'] for i in range(5)]).value_counts()
lowfreq = lowfreq.reset_index()
lowfreq.columns = ['Diagnostico','Freq']
lowfreq['Upper'] = lowfreq['Diagnostico'].apply(simplify_string, str_case='upper', remove_special=True)
lowfreq = lowfreq.sort_values(by='Upper')
lowfreq.to_csv('catalogos/catalogo_diagnostico_lowfreq.csv', index=False)
lowfreq

             Diagnostico  Freq               Upper
449               2HPNFP     1              2HPNFP
414                   4C     1                  4C
921                    9     1                   9
412         A AxHIxExSTD     1        A AXHIXEXSTD
409   A broncoaspiracion     1  A BRONCOASPIRACION
...                  ...   ...                 ...
915     Violacion rectal     1    VIOLACION RECTAL
930             Visceras     1            VISCERAS
787                    W     1                   W
1575                Xoco     1                XOCO
799                    Y     1                   Y

[2319 rows x 3 columns]