# Bitácoras Onmásticas del SEMEFO-DF de 1968-1982
# Generación y estandarización de catálogos

In [148]:
import os
import re
from glob import glob

import pandas as pd
from numpy import nan
from unidecode import unidecode 

import wibblywobbly as ww

def simplify_string(text, text_format='upper'):
    if type(text)==str:
        if text_format=='upper': text = text.upper()
        if text_format=='lower': text = text.lower()
        if text_format=='title': text = text.title()
        if text_format=='capitalize': text = text.capitalize()
        text = unidecode(text)
        text = ' '.join([t for t in text.split()])
    return text

## Generar tablas de incidencia por año para catálogos seleccionados

In [17]:
data_dir = "data_raw/BO_20230303/"
catalogos = ['Sexo','Tipo_restos','Procedencia','Diagnostico',]

# Diccionario para guardar datos
cat_raw = {cat:[] for cat in catalogos}

#Obtener archivos 
in_files = glob( data_dir+"*.xlsx" )

# read every file
for in_file in in_files:    
    print("Reading: "+in_file)
    year = re.search(r"19(\d{2})", in_file)[0]
    try: df = pd.read_excel(in_file, dtype='str')
    except: print("Failed to read file: "+in_file)
    else:
        for cat in catalogos: #generar catalogo unificado
            if cat in df.columns:
                data = df[cat].value_counts()
                data.name = year
                cat_raw[cat] += [data]
            else:
                print("\tNo se encontro columna: " +cat)
        if 'ID' in df.columns:
            id_unique = df['ID'].is_unique
            if not id_unique:
                print("\tIndice no es único")
                display( df[df['ID'].duplicated()] )
        else: print("\tNo se encontro ID")
        
for cat in catalogos:
    print(cat)
    df_cat = pd.concat(cat_raw[cat], axis=1)
    df_cat = df_cat.reindex(sorted(df_cat.columns), axis=1)
    df_cat['Total'] = df_cat.sum(axis=1)
    df_cat = df_cat.sort_values('Total', ascending=False)#.sort_index()
    cat_raw[cat] = df_cat
    display(cat_raw[cat])

Reading: data_raw/BO_20230303/SEMEFO_BO_1980_revision.xlsx
Reading: data_raw/BO_20230303/SEMEFO_BO_1982_revision.xlsx
Reading: data_raw/BO_20230303/SEMEFO_BO_1968_revision.xlsx

/home/esther/anaconda3/envs/SEMEFO_busqueda/lib/python3.10/site-packages/openpyxl/worksheet/_reader.py:312: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

Reading: data_raw/BO_20230303/SEMEFO_BO_1971_revision.xlsx
Reading: data_raw/BO_20230303/SEMEFO_BO_1975_revision.xlsx

/home/esther/anaconda3/envs/SEMEFO_busqueda/lib/python3.10/site-packages/openpyxl/worksheet/_reader.py:211: UserWarning: Cell L1770 is marked as a date but the serial value 3679962.0 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
/home/esther/anaconda3/envs/SEMEFO_busqueda/lib/python3.10/site-packages/openpyxl/worksheet/_reader.py:211: UserWarning: Cell L5432 is marked as a date but the serial value 3679840.0 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)

Reading: data_raw/BO_20230303/SEMEFO_BO_1978_revision.xlsx

/home/esther/anaconda3/envs/SEMEFO_busqueda/lib/python3.10/site-packages/openpyxl/worksheet/_reader.py:211: UserWarning: Cell G835 is marked as a date but the serial value 3681115.0 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)

Reading: data_raw/BO_20230303/SEMEFO_BO_1969_revision.xlsx
Reading: data_raw/BO_20230303/SEMEFO_BO_1972_revision.xlsx

/home/esther/anaconda3/envs/SEMEFO_busqueda/lib/python3.10/site-packages/openpyxl/worksheet/_reader.py:211: UserWarning: Cell G4960 is marked as a date but the serial value 3678765.0 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)

Reading: data_raw/BO_20230303/SEMEFO_BO_1981_revision.xlsx
Reading: data_raw/BO_20230303/SEMEFO_BO_1977_revision.xlsx
Reading: data_raw/BO_20230303/SEMEFO_BO_1979_revision.xlsx
Reading: data_raw/BO_20230303/SEMEFO_BO_1976_revision.xlsx
Reading: data_raw/BO_20230303/SEMEFO_BO_1974_revision.xlsx
Reading: data_raw/BO_20230303/SEMEFO_BO_1970_revision.xlsx
Reading: data_raw/BO_20230303/SEMEFO_BO_1973_revision.xlsx

## Sexo

In [27]:
cat_sexo = ['Masculino', 'Femenino', 'Indeterminado', 'S-D']
score_sexo = ww.map_list_to_catalog(cat_raw['Sexo'].index, cat_sexo, reject_value='S-D')
score_sexo = score_sexo.set_index('Data')[['Option1','Score1']]
score_sexo = pd.concat( [score_sexo,cat_raw['Sexo']], axis=1 )
score_sexo

WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']

,Option1,Score1,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,Total
s/d,S-D,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,3.0
s-d,S-D,100,NaN,NaN,NaN,NaN,NaN,NaN,18.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.0
masculino,Masculino,100,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
masculino,Masculino,100,NaN,NaN,2540.0,NaN,53.0,NaN,NaN,NaN,NaN,NaN,5409.0,91.0,NaN,NaN,NaN,8093.0
indeterminado,Indeterminado,100,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
femenino,Femenino,100,NaN,NaN,685.0,NaN,13.0,NaN,NaN,NaN,NaN,NaN,1685.0,NaN,NaN,NaN,NaN,2383.0
S/D,S-D,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,3.0
S-d-,S-D,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.0,NaN,NaN,NaN,NaN,NaN,11.0
S-d,S-D,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.0,NaN,NaN,NaN,NaN,NaN,11.0
S-D,S-D,100,NaN,3787.0,NaN,1009.0,1793.0,1502.0,NaN,39.0,26.0,21.0,14.0,40.0,1267.0,1391.0,3840.0,14729.0
Masculino.,Masculino,100,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
Masculino,Masculino,100,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0
Masculino,Masculino,100,3484.0,1783.0,1500.0,NaN,2088.0,2969.0,4375.0,NaN,5280.0,5469.0,NaN,2452.0,4843.0,4770.0,2849.0,41862.0
MAsculino,Masculino,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,2.0
Indeterminado,Indeterminado,100,4.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0
Femenino,Femenino,100,862.0,377.0,308.0,NaN,465.0,1016.0,1261.0,NaN,1591.0,1614.0,NaN,631.0,1481.0,1468.0,783.0,11857.0
Masculino,Masculino,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0
Masculino,Masculino,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0
Indeterminao,Indeterminado,96,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
Mascullino,Masculino,95,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
Maculino,Masculino,94,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,4.0
Femenno,Femenino,93,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
f,Femenino,90,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,2.0
[M],Femenino,90,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0
N,Femenino,90,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,2.0,NaN,NaN,3.0
M,Femenino,90,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,1.0
M,Femenino,90,NaN,NaN,NaN,NaN,NaN,NaN,53.0,5210.0,3.0,NaN,NaN,3289.0,NaN,NaN,NaN,8555.0
I?,Femenino,90,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,1.0
Femenino y Masculino,Femenino,90,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0
F,Femenino,90,NaN,NaN,1.0,NaN,NaN,NaN,17.0,1611.0,NaN,NaN,NaN,926.0,NaN,NaN,NaN,2555.0
D,S-D,90,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0
femenina,Femenino,88,NaN,NaN,NaN,NaN,29.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.0
Feminino,Femenino,88,42.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42.0
Femenina,Femenino,88,NaN,NaN,8.0,NaN,132.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,140.0
Indeterminable,Indeterminado,81,327.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,331.0
sin dato,S-D,0,NaN,NaN,19.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.0
ilegible,S-D,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.0,NaN,NaN,NaN,NaN,14.0
[?],S-D,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0
Sin dato,S-D,0,NaN,NaN,229.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,229.0
MM,S-D,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,1.0
M F,S-D,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,1.0
M (F),S-D,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,1.0
Ilegible,S-D,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0
Ia,S-D,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0
?,S-D,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,3.0,NaN,NaN,NaN,15.0
40,S-D,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,2.0
15,S-D,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0
-,S-D,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,1.0,NaN,NaN,NaN,5.0

In [29]:
file_sexo = "data_raw/Mapeo_Sexo.csv"
score_sexo.to_csv(file_sexo)

## Tipo de restos

In [28]:
cat_restos = ['Cadaver', 'Feto', 'Miembro', 'S-D']
score_restos = ww.map_list_to_catalog(cat_raw['Tipo_restos'].index, cat_restos, reject_value='S-D')
score_restos = score_restos.set_index('Data')[['Option1','Score1']]
score_restos = pd.concat( [score_restos,cat_raw['Tipo_restos']], axis=1 )
score_restos

,Option1,Score1,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,Total
miembro,Miembro,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,72.0,NaN,NaN,NaN,NaN,72.0
feto,Feto,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,208.0,1.0,NaN,NaN,NaN,210.0
cadáver,Cadaver,100,NaN,NaN,NaN,NaN,659.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,659.0
cadaver.,Cadaver,100,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
cadaver,Cadaver,100,NaN,NaN,NaN,NaN,761.0,515.0,NaN,3861.0,NaN,NaN,6758.0,NaN,NaN,NaN,NaN,11895.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"""M. Sup.""",S-D,0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
"""M. Izq.""",S-D,0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
"""M. Inf.""",S-D,0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
"""M. Inf""",S-D,0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
"""M der.""",S-D,0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0

In [30]:
file_restos = "data_raw/Mapeo_Restos.csv"
score_restos.to_csv(file_restos)

## Procedencia

In [ ]:
f_procedencia = "data_raw/Catálogo_Procedencia.csv"
cat_pro = pd.read_csv(f_procedencia)
cat_pro = cat_pro[cat_pro['CONTEO']>=5]
cat_pro = cat_pro[['SIGLAS','EQUIVALENCIA']].drop_duplicates()
cat_pro = {k:v for k,v in zip(cat_pro['SIGLAS'],cat_pro['EQUIVALENCIA'])}
cat_pro

In [45]:
score_pro = ww.map_list_to_catalog(cat_raw['Procedencia'].index, cat_pro.values(), reject_value='S-D')
score_pro = score_pro.set_index('Data')[['Option1','Score1']]
score_pro['Simplificado'] = score_pro['Option1'].replace(cat_pro)
score_pro
score_pro = pd.concat( [score_pro,cat_raw['Procedencia']], axis=1 )
score_pro

WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']

,Option1,Score1,Simplificado,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,Total
s/d,S-D,100,S-D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0
s-d,S-D,100,S-D,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0
hx,HX,100,HX,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
[37a],37A,100,37A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0
X-1,X-1,100,X-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,95.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10ª delegación 32 sero 29,S-D,0,S-D,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
10 deleg,S-D,0,S-D,NaN,2.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0
10 a deleg,S-D,0,S-D,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
10 Del.,S-D,0,S-D,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
-,S-D,0,S-D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,NaN,NaN,NaN,3.0

In [46]:
file_pro = "data_raw/Mapeo_Procedencia.csv"
score_pro.to_csv(file_pro)

## Diagnostico

In [119]:
f_diagnostico = "data_raw/Catálogo_Diagnóstico_simplificado.csv"
cat_dia = pd.read_csv(f_diagnostico)
cat_dia = {k:v for k,v in zip(cat_dia['Data'],cat_dia['Valor'])}
cat_dia

{'ABORTO': 'aborto',
 'AOXT': 'amputación quirúrgica consecutiva al traumatismo',
 'AQT': 'amputación quirúrgica consecutiva al traumatismo',
 'AQXT': 'amputación quirúrgica consecutiva al traumatismo',
 'AT': 'amputación traumática',
 'AN': 'anemia',
 'ANOXIA': 'anoxia',
 'ANEN': 'asfixia neo natorum',
 'ANEON': 'asfixia neo natorum',
 'ANN': 'asfixia neo natorum',
 'A NE N': 'asfixia neo natorum',
 'AA': 'asfixia por ahorcamiento',
 'AXA': 'asfixia por ahorcamiento',
 'AXAH': 'asfixia por ahorcamiento',
 'AXBRONCOASPIRACION': 'asfixia por broncoaspiracion',
 'AE': 'asfixia por estrangulación',
 'AOVA': 'asfixia por obstrucción de vías aéreas',
 'AS': 'asfixia por sofocación',
 'ASF': 'asfixia por sofocación',
 'ASB': 'asfixia por sumersion',
 'BN': 'bronconeumonia',
 'BBNT': 'bronconeumonia bilateral no traumatica',
 'BNT': 'bronconeumonia no traumatica',
 'CH': 'cirrosis hepatica',
 'C': 'cirrosis',
 'CISTICERCOSIS': 'cisticercosis',
 'CVG': 'congestion visceral generalizada',
 'CL': 'conjunto de lesiones',
 'DESNUT': 'desnutricion',
 'DESNUTRICION': 'desnutricion',
 'T': 'diagnostico no determinable',
 'PTE': 'diagnostico no determinable (pleuroneumonia o septicemia)',
 'DISPENSA': 'dispensa',
 'DISPENSAN': 'dispensa',
 'EC': 'edema cerebral',
 'EP': 'edema pulmonar',
 'ELECTROCUCION': 'electrocucion',
 'ELECTROCUTADO': 'electrocucion',
 'EOC': 'enfermedad orgánica del corazón',
 'LOC': 'enfermedad orgánica del corazón',
 'ENT': 'enteritis',
 'ENTERITIS': 'enteritis',
 'EX PSM': 'expulsion prematura del seno materno',
 'EXP PSM': 'expulsion prematura del seno materno',
 'EXPPMS': 'expulsion prematura del seno materno',
 'EXPPSM': 'expulsion prematura del seno materno',
 'FCPN': 'falta de cuidado post natales',
 'G': 'gangrena',
 'GANG': 'gangrena',
 'GANGRENA': 'gangrena',
 'GASTROENTERITIS': 'gastroenteritis',
 'HC': 'hemorragia cerebral',
 'HIP': 'herida por instrumento punzo cortante',
 'HIPC': 'herida por instrumento punzocortante penetrante',
 'HIPCPA': 'herida por instrumento punzocortante penetrante de abdomen',
 'HIPCPC': 'herida por instrumento punzocortante penetrante de cuello',
 'HIPCPTA': 'herida por instrumento punzocortante penetrante tórax y abdomen',
 'HIPCP': 'herida por instrumento punzocortante penetrante',
 'HIPCPT': 'herida por instrumento punzocortante penetrante de tórax',
 'HPA': 'herida por proyectil de arma de fuego',
 'HPAF': 'herida por proyectil de arma de fuego',
 'HPAFPA': 'herida por proyectil de arma de fuego penetrante de abdomen',
 'HPAFP': 'herida por proyectil de arma de fuego penetrante',
 'HPAP': 'herida por proyectil de arma de fuego penetrante',
 'HPPAFP': 'herida por proyectil de arma de fuego penetrante',
 'HPAFPC': 'herida por proyectil de arma de fuego penetrante de cráneo',
 'HPPAFPC': 'herida por proyectil de arma de fuego penetrante de cráneo',
 'HPAFPT': 'herida por proyectil de arma de fuego penetrante de tórax',
 'HPIPCPT': 'herida por proyectil de arma de fuego penetrante de tórax',
 'HPPAFPT': 'herida por proyectil de arma de fuego penetrante de tórax',
 'HPAFPTA': 'herida por proyectil de arma de fuego penetrante de tórax y abdomen',
 'HPAFPTYA': 'herida por proyectil de arma de fuego penetrante de tórax y abdomen',
 'HPAFPV': 'herida por proyectil de arma de fuego penetrante de vientre',
 'HSIP': 'heridas por instrumento punzo cortante',
 'HSIPC': 'heridas por instrumento punzo cortante',
 'HSIPCPS': 'heridas por instrumento punzo cortante penetrantes',
 'HSIPCPST': 'heridas por instrumento punzo cortante penetrantes de tórax',
 'HSIPCPSTA': 'heridas por instrumento punzo cortante penetrantes de tórax y abdomen',
 'HSPA': 'heridas por proyectil de arma de fuego',
 'HSPAF': 'heridas por proyectil de arma de fuego',
 'HSPAFP': 'heridas por proyectil de arma de fuego penetrante',
 'HSPAFPS': 'heridas por proyectil de arma de fuego penetrante',
 'HSPSAFPS': 'heridas por proyectil de arma de fuego penetrante',
 'HSPAFPC': 'heridas por proyectil de arma de fuego penetrante de cráneo',
 'HSPAFPSC': 'heridas por proyectil de arma de fuego penetrante de cráneo',
 'HSPAFPSA': 'heridas por proyectil de arma de fuego penetrantes de abdomen',
 'HSPAFPST': 'heridas por proyectil de arma de fuego penetrantes de tórax',
 'HSPSAFPST': 'heridas por proyectil de arma de fuego penetrantes de tórax',
 'HSPAFPSTA': 'heridas por proyectil de arma de fuego penetrantes de tórax y abdomen',
 'ILEGIBLE': 'ilegible',
 'INDETERMINABLE': 'indeterminado',
 'INDETERMINADO': 'indeterminado',
 'LOC INF MIOCARDIO': 'infarto agudo al miocardio',
 'INTOX': 'intoxicacion',
 'INTOXICACION': 'intoxicacion',
 'INTOX CO2': 'intoxicación por co2',
 'MENINGITIS': 'meningitis',
 'NECROSIS': 'necrosis',
 'N': 'neumonia',
 'NO COPIAS XOCO': 'no copias xoco',
 'PANCREATITIS': 'pancreatitis',
 'PER': 'peritonitis',
 'PERITONITIS': 'peritonitis',
 'PN': 'pleuro pneumonia',
 'QUEM': 'quemaduras',
 'QUEMADURA': 'quemaduras',
 'QUEMADURAS': 'quemaduras',
 '-': 'sin datos',
 '?': 'sin datos',
 '??': 'sin datos',
 'S': 'septicemia',
 'SEPTICEMIA': 'septicemia',
 'S-D': 'sin datos',
 'TCE': 'traumatismo craneoencefalico',
 'TT': 'traumatismo toracico',
 'TA': 'traumatismo abdominal',
 'TAP': 'traumatismo abdomino pelvico',
 'TC': 'traumatismo cervical',
 'TCER': 'traumatismo cervical',
 'TCERV': 'traumatismo cervical',
 'TCERVICAL': 'traumatismo cervical',
 'TCERVMED': 'traumatismo cervical medular',
 'TCTAP': 'traumatismo cervical toracico abdomino pelvico',
 'TCM': 'traumatismo cervical medullary',
 'TCA': 'traumatismo craneal abdominal',
 'TCP': 'traumatismo cráneo abdomino pelvico',
 'TCAP': 'traumatismo cráneo abdomino pelvico',
 'TCC': 'traumatismo craneo cervical',
 'TCCER': 'traumatismo craneo cervical',
 'TCCERV': 'traumatismo craneo cervical',
 'TCCERMED': 'traumatismo craneo cervico medular',
 'TCCM': 'traumatismo craneo cervico medular',
 'TCERM': 'traumatismo craneo cervico medular',
 'TCERMED': 'traumatismo craneo cervico medular',
 'TCCERT': 'traumatismo craneo cervico toracico',
 'TCCT': 'traumatismo craneo cervico toracico',
 'TCERT': 'traumatismo craneo cervico toracico',
 'TCEA': 'traumatismo cráneo encefálico abdominal',
 'TCET': 'traumatismo craneoencefalico toracico',
 'TCF': 'traumatismo craneo facial',
 'TCRM': 'traumatismo cráneo raqui medular',
 'TCT': 'traumatismo craneo toracico',
 'TCTA': 'traumatismo craneal torácico abdominal',
 'TCTP': 'traumatismo craneo toracico pelvico',
 'T M': 'traumatismo de miembro',
 'TMI': 'traumatismo de miembro inferior',
 'TMS': 'traumatismo de miembro superior',
 'TMIS': 'traumatismo multiple',
 'TMSIS': 'traumatismo de miembros inferiores',
 'TM': 'traumatismo multiple',
 'TP': 'traumatismo pelvico',
 'TTA': 'traumatismo toracico abdominal',
 'TTP': 'traumatismo toracico pelvico',
 'TTAP': 'traumatismo toracico abdomino pelvico',
 'TROMBOSIS': 'trombosis',
 'TB': 'tuberculosis',
 'VE': 'varices esofagicas',
 'VILLA': 'villa'}

In [149]:
score_dia = pd.DataFrame([d.split('+') for d in cat_raw['Diagnostico'].index ])
score_dia.columns = ['Sigla1','Sigla2','Sigla3','Sigla4','Sigla5',]
score_dia.index = cat_raw['Diagnostico'].index
score_dia = score_dia.applymap(simplify_string)

for col in score_dia.columns:
    score_dia[col.replace('Sigla','Valor')] = score_dia[col].replace(cat_dia)
score_dia['Valor'] = score_dia[['Valor1','Valor2','Valor3','Valor4','Valor5']] \
                     .apply(lambda l: ' + '.join([s for s in l if type(s)==str]), axis=1 )

score_dia = pd.concat( [score_dia,cat_raw['Diagnostico']], axis=1 )
score_dia

,Sigla1,Sigla2,Sigla3,Sigla4,Sigla5,Valor1,Valor2,Valor3,Valor4,Valor5,...,1974,1975,1976,1977,1978,1979,1980,1981,1982,Total
S-D,S-D,None,None,None,None,sin datos,None,None,None,None,...,NaN,28.0,29.0,26.0,8.0,82.0,7595.0,5026.0,7472.0,44127.0
TM,TM,None,None,None,None,traumatismo multiple,None,None,None,None,...,845.0,1135.0,1352.0,1457.0,1337.0,1372.0,NaN,NaN,NaN,7498.0
TCE,TCE,None,None,None,None,traumatismo craneoencefalico,None,None,None,None,...,730.0,960.0,1000.0,1059.0,1060.0,1126.0,NaN,NaN,NaN,5935.0
BN,BN,None,None,None,None,bronconeumonia,None,None,None,None,...,199.0,231.0,290.0,309.0,352.0,442.0,NaN,NaN,NaN,1823.0
CVG,CVG,None,None,None,None,congestion visceral generalizada,None,None,None,None,...,158.0,196.0,189.0,254.0,243.0,247.0,NaN,NaN,NaN,1287.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
AAxHExHPAFP,AAXHEXHPAFP,None,None,None,None,AAXHEXHPAFP,None,None,None,None,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0
TM y Electrocución,TM Y ELECTROCUCION,None,None,None,None,TM Y ELECTROCUCION,None,None,None,None,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0
P/BN+TP,P/BN,TP,None,None,None,P/BN,traumatismo pelvico,None,None,None,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0
BN+S+TMI,BN,S,TMI,None,None,bronconeumonia,septicemia,traumatismo de miembro inferior,None,None,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0
AECA,AECA,None,None,None,None,AECA,None,None,None,None,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0

In [150]:
file_dia = "data_raw/Mapeo_Diagnostico.csv"
score_dia.to_csv(file_dia)