# Bitácoras Onmásticas del SEMEFO-DF de 1968-1982
# Generación y estandarización de catálogos

In [1]:
import os
from glob import glob

import pandas as pd
from unidecode import unidecode 

def simplify_string(text):
    text = text.upper()
    text = ' '.join([t for t in text.split()])
    text = unidecode(text)
    text = ' '.join([t for t in text.split()]) #paranoia
    return text

data_dir = "data_raw/B0_20230223/"
catalogos = ['Sexo','Tipo_restos','Procedencia','Diagnostico',]

In [2]:
# Diccionario para guardar datos
cat_raw = {c:list() for c in catalogos}
cat_raw

#Obtener archivos 
in_files = glob( data_dir+"*.xlsx" )

# read every file
for in_file in in_files:    
    print("Reading: "+in_file)
    try: df = pd.read_excel(in_file, dtype='str')
    except: print("Failed to read file: "+in_file)
    else:
        for cat in catalogos: #generar catalogo unificado
            if cat in df.columns:
                cat_raw[cat] += df[cat].unique().tolist()
            else:
                print("\tNo se encontro columna: " +cat)
        if 'ID' in df.columns:
            id_unique = df['ID'].is_unique
            if not id_unique:
                print("\tIndice no es único")
                display( df[df['ID'].duplicated()] )
        else: print("\tNo se encontro ID")

Reading: data_raw/B0_20230223/SEMEFO_BO_1980_revision.xlsx
Reading: data_raw/B0_20230223/SEMEFO_BO_1982_revision.xlsx
Reading: data_raw/B0_20230223/SEMEFO_BO_1968_revision.xlsx

/home/esther/anaconda3/envs/SEMEFO_busqueda/lib/python3.10/site-packages/openpyxl/worksheet/_reader.py:312: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

Reading: data_raw/B0_20230223/SEMEFO_BO_1971_revision.xlsx
Reading: data_raw/B0_20230223/SEMEFO_BO_1975_revision.xlsx

/home/esther/anaconda3/envs/SEMEFO_busqueda/lib/python3.10/site-packages/openpyxl/worksheet/_reader.py:211: UserWarning: Cell L1770 is marked as a date but the serial value 3679962.0 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
/home/esther/anaconda3/envs/SEMEFO_busqueda/lib/python3.10/site-packages/openpyxl/worksheet/_reader.py:211: UserWarning: Cell L5432 is marked as a date but the serial value 3679840.0 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)

Reading: data_raw/B0_20230223/SEMEFO_BO_1978_revision.xlsx

/home/esther/anaconda3/envs/SEMEFO_busqueda/lib/python3.10/site-packages/openpyxl/worksheet/_reader.py:211: UserWarning: Cell G835 is marked as a date but the serial value 3681115.0 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)

Reading: data_raw/B0_20230223/SEMEFO_BO_1969_revision.xlsx
Reading: data_raw/B0_20230223/SEMEFO_BO_1972_revision.xlsx

/home/esther/anaconda3/envs/SEMEFO_busqueda/lib/python3.10/site-packages/openpyxl/worksheet/_reader.py:211: UserWarning: Cell G4960 is marked as a date but the serial value 3678765.0 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)

Reading: data_raw/B0_20230223/SEMEFO_BO_1981_revision.xlsx
	Indice no es único

,ID,Numero_progresivo,Primer_apellido,Segundo_apellido,Nombres_propios,Nombre_completo,Fecha,Expediente _Semefo,Procedencia,Numero_acta,Diagnostico,Sexo,Edad,Tipo_restos,Bitacora_ingresos,Pagina_PDF,Foja,Posible_identificado_como,Observaciones_capturista
7630,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7631,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7632,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7633,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7634,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8029,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8030,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8031,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8032,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8033,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Reading: data_raw/B0_20230223/SEMEFO_BO_1977_revision.xlsx
Reading: data_raw/B0_20230223/SEMEFO_BO_1979_revision.xlsx
	Indice no es único

,ID,Numero_progresivo,Primer_apellido,Segundo_apellido,Nombres_propios,Nombre_completo,Fecha,Expediente _Semefo,Procedencia,Numero_acta,Diagnostico,Sexo,Edad,Tipo_restos,Bitacora_ingresos,Pagina_PDF,Foja,Posible_identificado_como,Observaciones_capturista
7454,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7455,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7456,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7457,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7458,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7996,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7997,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7998,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7999,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Reading: data_raw/B0_20230223/SEMEFO_BO_1976_revision.xlsx

/home/esther/anaconda3/envs/SEMEFO_busqueda/lib/python3.10/site-packages/openpyxl/worksheet/_reader.py:211: UserWarning: Cell G5647 is marked as a date but the serial value 3680232.0 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)

Reading: data_raw/B0_20230223/SEMEFO_BO_1974_revision.xlsx
Reading: data_raw/B0_20230223/SEMEFO_BO_1970_revision.xlsx
Reading: data_raw/B0_20230223/SEMEFO_BO_1973_revision.xlsx

In [13]:
for k,v in cat_raw.items():
    #print(k, len(v), v[0:10])
    v = [s for s in v if type(s)==str]
    #v = [simplify_string(s) for s in v]
    v = list(set(v))
    v.sort()
    cat_raw[k] = v
    print(k, len(v), v[0:10])

Sexo 48 ['  Masculino', ' Masculino', '-', '15', '40', '?', 'D', 'F', 'Femenina', 'Femenino']
Tipo_restos 112 ['"M der."', '"M. Inf"', '"M. Inf."', '"M. Izq."', '"M. Sup."', '"M. Sup.·', '"M. inf.', '"M. superior derecho"', '2022-05-18 00:00:00', '4 dedos miembro superior']
Procedencia 1690 ['  CR 83928', ' 10ª delegación 32364', ' 1a Delegación', ' H.T.B. ', ' VO 1606', '-', '03a', '1', '1 deleg', '10']
Diagnostico 3793 [' AQxT+gangrena', '" "', '"DSIPENSA"', '"Depósito"', '"Dispensa', '"No Exp"', '"Quemadura', '"Quemaduras', '"TETANOS"', '"Tetanos"+BN']

In [14]:
cat_raw['Sexo']

['  Masculino',
 ' Masculino',
 '-',
 '15',
 '40',
 '?',
 'D',
 'F',
 'Femenina',
 'Femenino',
 'Femenino y Masculino',
 'Femenno',
 'Feminino',
 'I?',
 'Ia',
 'Ilegible',
 'Indeterminable',
 'Indeterminado',
 'Indeterminao',
 'M',
 'M ',
 'M (F)',
 'M F',
 'MAsculino',
 'MM',
 'Maculino',
 'Masculino',
 'Masculino ',
 'Masculino.',
 'Mascullino',
 'N',
 'S-D',
 'S-d',
 'S-d-',
 'S/D',
 'Sin dato',
 '[?]',
 '[M]',
 'f',
 'femenina',
 'femenino',
 'ilegible',
 'indeterminado',
 'masculino',
 'masculino ',
 's-d',
 's/d',
 'sin dato']

**Done!**