# Bitacoras onomásticas SEMEFO 1968-1982
# Revisión de bitacoras integradas

In [1]:
import pandas as pd
from numpy import nan

from itertools import product
from helper_pandas import  profile_minimal, translate_datetime, \
                          join_strings_with_nans, simplify_string

In [2]:
data_file = "data_raw/SEMEFO_revision_20230925.csv"
df = pd.read_csv(data_file, dtype='str')
df

,ID,Numero_progresivo_transcrito,Nombre_completo_transcrito,Primer_apellido,Segundo_apellido,Nombres_propios,Fecha_transcrito,Fecha_estandar,Expediente_SEMEFO_transcrito,Procedencia_transcrito,...,Diagnostico_extendido,Sexo,Edad_transcrito,Edad_estandar,Tipo_restos,Bitacora_ingresos,Pagina_PDF,Foja_transcrito,Observaciones,Conocido_desconocido
0,BO_1971_01274,NaN,diaz luna alejandro,diaz,luna,alejandro,10/5/1971,10/5/1971,2148,S-D,...,sin datos,Masculino,6 dias,0,Cadáver,semefo_df_bo_1971,39,30 reverso,NaN,conocido
1,BO_1974_00051,51,alfora herrera antonio,alfora,herrera,antonio,27/2/1974,27/2/1974,1001,11a,...,quemaduras,Masculino,19m,1,Cadáver,semefo_df_bo_1974,4,1 reverso,NaN,conocido
2,BO_1975_04776,144,sandoval ortiz castulo,sandoval,ortiz,castulo,28/5/1975,28/5/1975,2688,C-1,...,falta cuidado post natales,Masculino,-12 horas,1,Cadáver,semefo_df_bo_1975,147,86,NaN,conocido
3,BO_1974_00247,247,aldo mucino maribel,aldo,mucino,maribel,11/10/1974,11/10/1974,4897,25a,...,asfixia por obstruccion de vias aereas,Femenino,1.5,1.5,Cadáver,semefo_df_bo_1974,10,4 reverso,NaN,conocido
4,BO_1974_00081,81,alcantar valero emma,alcantar,valero,emma,3/4/1974,3/4/1974,1634,12a,...,traumatismo craneo torax,Femenino,2,2,Cadáver,semefo_df_bo_1974,5,2,NaN,conocido
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96855,BO_1982_07489,NaN,placenta,s-d,s-d,s-d,5/6/1982,5/6/1982,3079,15a,...,sin datos,S-D,S-D,NaN,Miembros,semefo_df_bo_1982,251,156,NaN,desconocido
96856,BO_1982_07490,NaN,5 dedos del pie derecho de desconocido,s-d,s-d,s-d,5/6/1982,5/6/1982,3060,32a,...,sin datos,S-D,S-D,NaN,Miembros,semefo_df_bo_1982,251,156,NaN,desconocido
96857,BO_1982_07491,NaN,dedo de desconocido,s-d,s-d,s-d,19/11/1982,19/11/1982,6389,32a,...,sin datos,S-D,S-D,NaN,Miembros,semefo_df_bo_1982,251,156,NaN,desconocido
96858,BO_1982_07492,NaN,4 dedos de desconocido,s-d,s-d,s-d,28/11/1982,28/11/1982,6528,27a,...,sin datos,S-D,S-D,NaN,Miembros,semefo_df_bo_1982,251,156,NaN,desconocido
96859,BO_1982_07493,NaN,osamenta de desconocido,s-d,s-d,s-d,11/10/1982,11/10/1982,5629,9a,...,sin datos,S-D,S-D,NaN,Cadáver,semefo_df_bo_1982,251,156,no se recibio necropsia. es una osamenta.,desconocido

## ID

In [3]:
# Format
df.loc[(df['ID'].str.startswith('BO')!=True)]

Empty DataFrame
Columns: [ID, Numero_progresivo_transcrito, Nombre_completo_transcrito, Primer_apellido, Segundo_apellido, Nombres_propios, Fecha_transcrito, Fecha_estandar, Expediente_SEMEFO_transcrito, Procedencia_transcrito, Procedencia_estandar, Procedencia_direccion, Procedencia_alcaldia, Numero_acta_transcrito, Procedencia_acta, Diagnostico_transcrito, Diagnostico_estandar, Diagnostico_extendido, Sexo, Edad_transcrito, Edad_estandar, Tipo_restos, Bitacora_ingresos, Pagina_PDF, Foja_transcrito, Observaciones, Conocido_desconocido]
Index: []

[0 rows x 27 columns]

In [4]:
# Format
data = pd.DataFrame([row.split('_') for row in df['ID'].to_list()], columns=['BO', 'year','ID'])
data.index = df['ID']
data['year'] = pd.to_numeric(data['year'], downcast='integer')
data['ID'] = pd.to_numeric(data['ID'], downcast='integer')

data.groupby('year').agg({
            'BO':'size',
            'ID':['max', pd.Series.nunique]
            })

        BO    ID
      size   max nunique
year
1968  4719  4719    4719
1969  5052  5052    5052
1970  5303  5303    5303
1971  5524  5524    5524
1972  5770  5770    5770
1973  6471  6471    6471
1974  5731  5731    5731
1975  6861  6861    6861
1976  6907  6907    6907
1977  7166  7166    7166
1978  7154  7154    7154
1979  7461  7461    7461
1980  7619  7619    7619
1981  7629  7629    7629
1982  7493  7493    7493

## Numero_progresivo

In [5]:
col = 'Numero_progresivo_transcrito'
df[col] = pd.to_numeric(df[col], downcast='integer')
df[col].value_counts(dropna=False)

Numero_progresivo_transcrito
NaN      69681
38.0       110
41.0       110
37.0       109
39.0       109
         ...
921.0        1
920.0        1
919.0        1
918.0        1
917.0        1
Name: count, Length: 924, dtype: int64

## Nombre_completo_transcrito, 
### Primer_apellido
### Segundo_apellido
### Nombres_propios

In [6]:
cols = ['Nombre_completo_transcrito', 'Primer_apellido', 'Segundo_apellido', 'Nombres_propios', ]
df[cols] = df[cols].replace('s-d','S-D')

display( (df[cols]=='S-D').sum() )
df.loc[df['Nombre_completo_transcrito']=='S-D','ID'].to_list()

Nombre_completo_transcrito       45
Primer_apellido               18118
Segundo_apellido              21938
Nombres_propios               18154
dtype: int64

['BO_1970_04404',
 'BO_1971_01483',
 'BO_1972_03641',
 'BO_1972_04589',
 'BO_1973_06164',
 'BO_1976_06508',
 'BO_1976_06812',
 'BO_1976_06814',
 'BO_1977_00277',
 'BO_1977_00278',
 'BO_1977_00348',
 'BO_1977_00399',
 'BO_1977_00468',
 'BO_1977_00469',
 'BO_1977_00540',
 'BO_1977_00609',
 'BO_1977_00610',
 'BO_1977_00752',
 'BO_1977_00962',
 'BO_1977_01105',
 'BO_1977_01233',
 'BO_1977_01524',
 'BO_1977_01593',
 'BO_1977_01594',
 'BO_1977_06012',
 'BO_1978_00345',
 'BO_1978_00536',
 'BO_1978_00608',
 'BO_1978_00793',
 'BO_1978_00836',
 'BO_1978_01109',
 'BO_1978_02288',
 'BO_1978_02289',
 'BO_1978_02290',
 'BO_1978_02291',
 'BO_1978_02292',
 'BO_1978_02293',
 'BO_1978_02294',
 'BO_1978_02295',
 'BO_1978_04471',
 'BO_1978_04472',
 'BO_1978_04473',
 'BO_1978_06541',
 'BO_1978_06542',
 'BO_1978_07031']

## Fecha_transcrito
### Fecha_estandar
### Fecha_añomes
### Fecha_diasemana

In [7]:
df['Fecha_estandar'] = pd.to_datetime(df['Fecha_estandar'], format="%d/%m/%Y")
df['Fecha_estandar'].value_counts(dropna=False)

Fecha_estandar
NaT           276
1982-03-27     46
1979-12-26     43
1982-06-21     41
1981-12-26     41
             ...
1969-11-23      3
1971-09-29      3
1968-04-25      2
1968-05-26      2
1970-05-05      2
Name: count, Length: 5480, dtype: int64

In [8]:
df['Fecha_año'] = df['Fecha_estandar'].dt.year.fillna('') \
                  .apply(lambda s: str(int(s)) if s!='' else nan)
display( df['Fecha_año'].value_counts(dropna=False).to_dict() )

df['Fecha_mes'] = translate_datetime(df['Fecha_estandar'].dt.month_name())
display( df['Fecha_mes'].value_counts(dropna=False).to_dict() )

df['Fecha_añomes'] = df[['Fecha_año','Fecha_mes']] \
                       .apply(join_strings_with_nans, sep=' ', axis=1)
df = df.drop(['Fecha_año','Fecha_mes'], axis=1)
df['Fecha_añomes'].value_counts(dropna=False)

{'1981': 7615,
 '1980': 7604,
 '1982': 7481,
 '1979': 7431,
 '1977': 7132,
 '1978': 7115,
 '1976': 6892,
 '1975': 6854,
 '1973': 6213,
 '1974': 5947,
 '1972': 5754,
 '1971': 5503,
 '1970': 5282,
 '1969': 5045,
 '1968': 4716,
 nan: 276}

{'Diciembre': 9426,
 'Enero': 8799,
 'Marzo': 8200,
 'Octubre': 8166,
 'Noviembre': 8092,
 'Agosto': 8088,
 'Julio': 7826,
 'Septiembre': 7765,
 'Mayo': 7750,
 'Abril': 7562,
 'Febrero': 7539,
 'Junio': 7371,
 nan: 276}

Fecha_añomes
1977 Diciembre    762
1981 Diciembre    752
1979 Diciembre    743
1982 Diciembre    716
1980 Diciembre    714
                 ...
1969 Febrero      366
1969 Agosto       365
1968 Mayo         343
1968 Abril        319
NaN               276
Name: count, Length: 181, dtype: int64

In [9]:
año = [str(i) for i in range(1968, 1983)]
mes = ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 
       'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre', ]
cat_type = [' '.join(p) for p in product(año, mes)]
cat_type = pd.CategoricalDtype(categories=cat_type, ordered=True)

df['Fecha_añomes'] = df['Fecha_añomes'].astype(cat_type)
df['Fecha_añomes']

0             1971 Mayo
1          1974 Febrero
2             1975 Mayo
3          1974 Octubre
4            1974 Abril
              ...
96855        1982 Junio
96856        1982 Junio
96857    1982 Noviembre
96858    1982 Noviembre
96859      1982 Octubre
Name: Fecha_añomes, Length: 96860, dtype: category
Categories (180, object): ['1968 Enero' < '1968 Febrero' < '1968 Marzo' < '1968 Abril' ... '1982 Septiembre' < '1982 Octubre' < '1982 Noviembre' < '1982 Diciembre']

In [10]:
df['Fecha_diasemana'] = translate_datetime(df['Fecha_estandar'].dt.day_name())
dia = ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado', 'Domingo']
cat_type = pd.CategoricalDtype(categories=dia, ordered=True)
df['Fecha_diasemana'] = df['Fecha_diasemana'].astype(cat_type)
df['Fecha_diasemana'].value_counts(dropna=False)

Fecha_diasemana
Lunes        16580
Martes       15089
Miércoles    13618
Jueves       13132
Domingo      12730
Sábado       12729
Viernes      12706
NaN            276
Name: count, dtype: int64

## Sexo

In [11]:
df['Sexo'] = df['Sexo'].astype("category")
df['Sexo'].value_counts(dropna=False)

Sexo
Masculino    73740
Femenino     20601
S-D           2519
Name: count, dtype: int64

## Edad_transcrito
### Edad_estandar
### Edad_rango

In [12]:
from math import floor
from helper_pandas import to_dtype_with_errors

def replace_edades_menor_al_año(edad):
    if type(edad)==str:
        edad_ = simplify_string(edad)
        edad_ = edad_.replace(' 1/2','.5')
        edad_ = edad_.replace('horas','hora').replace('dias','dia').replace('semanas','semana').replace('meses','mes').replace('anos','ano')
        dic_time = {'ano':1, 'mes':12, 'semana':52, 'dia':365, 'hora':8766}
        for nombre, n in dic_time.items():
            if nombre in edad_:
                edad_ = simplify_string( edad_.replace(nombre,'') )
                try: edad_ = float(edad_)
                except ValueError: return edad
                return floor( edad_ / n )
        dic_time = {'a':1, 'm':12, 'd':365}
        for nombre, n in dic_time.items():
            if nombre in edad_:
                edad_ = simplify_string( edad_.replace(nombre,'') )
                try: edad_ = float(edad_)
                except ValueError: return edad
                return floor( edad_ / n )
        try: edad_ = float(edad_)
        except(ValueError): return edad
        return floor(edad_)
    return edad

dic_replace = {'[1-10 días]':0, '10 SEMNS':0, '15-30 días':0, '2 mese':0, '2 o 3 meses':0, '30 - 90 días':0, '5 meses 15 días':0, 
               '6 meses UI':0, '7 - 12 meses':0, '72 hrs':0, '-12 horas':1, '1 año 3 meses':1, '1 año 4 meses':1, '1 año 7 meses':1, 
               '1 Y 8 meses':1, '15 mese':1, '18 mese':1, '3 años y medio ':3, '7 añoss':7, '[8]':8, '-72 años':72, ' S-D':'S-D', 
               '-':'S-D', '?':'S-D', 'F':'S-D', 'M':'S-D', 'S-d':'S-D', '-72 años':72, '-1':1, '2/6':'S-D', '$45':45, '3-5':4, 
               ' +3-5':4,'7-9':8,' +6-8':7,' +7-9':8,'4-6':5,'5-7':6,'6-8':7,'4 y 5':'S-D',' +4-6':5,'8 años7':8,'más 72':'S-D',
               '1 - 3':2,'1-2':1,'9-9':9,'3-4':3,'7-8':7,'2-4':3,'8 Ins.':8,'41 n':41,'R.N':0,'18-25':21, '7 - 9':8,
               '25-30':27,' +3-4':3,' +5-6':5,' +2-3':2,' +4-7':5,' +7-8':7,' +5-7':6,' +6-7':6,'25-40':'S-D','20 o 24':22,'25/30':22,
               #'8 172':'S-D',
              }

df['Edad_estandar'] = df['Edad_transcrito']
df['Edad_estandar'] = df['Edad_estandar'].apply(replace_edades_menor_al_año) \
                       .replace(',','.', regex=True).replace(dic_replace)
df = to_dtype_with_errors(df, 'Edad_estandar')
df.loc[df['Tipo_restos'].isin(['Feto','Recién nacido']), 'Edad_estandar_clean'] = 0
df['Edad_estandar'] = df['Edad_estandar_clean']
df = df.drop(['Edad_estandar_clean', 'Edad_estandar_error'], axis=1)
df['Edad_estandar'].value_counts()

Edad_estandar
0.0      4666
40.0     1728
30.0     1710
35.0     1666
25.0     1619
         ...
668.0       1
226.0       1
116.0       1
107.0       1
232.0       1
Name: count, Length: 116, dtype: int64

In [13]:
df.loc[(df['Edad_estandar']>99) | (df['Edad_estandar']<0), 
       ['ID','Nombre_completo_transcrito','Edad_estandar','Tipo_restos','Pagina_PDF']]

,ID,Nombre_completo_transcrito,Edad_estandar,Tipo_restos,Pagina_PDF
2,BO_1975_04776,sandoval ortiz castulo,-1.0,Cadáver,147
37094,BO_1974_04230,salas viuda de barroso guadalupe,103.0,Cadáver,138
37472,BO_1974_04608,desconocido,5575.0,Cadáver,167
40289,BO_1975_01697,garcia martinez pedro,118.0,Cadáver,54
41033,BO_1975_02442,jaramillo cervantes leonardo,102.0,Cadáver,77
43148,BO_1975_04557,rodriguez vda de a maria dolores,100.0,Cadáver,140
49970,BO_1976_04524,reyes clora antonia,102.0,Cadáver,141
50085,BO_1976_04639,sanchez guerrero emiliano,102.0,Cadáver,144
50841,BO_1976_05395,vergara rios eugenia,100.0,Cadáver,166
52914,BO_1977_00576,benitez rojas alberto,102.0,Cadáver,19
54103,BO_1977_01765,guerrero alvarez ana maria,100.0,Cadáver,56
57633,BO_1977_05295,ubaldo guillen angel,103.0,Cadáver,166
61267,BO_1978_01763,gonzalez barragan arcadio,108.0,Cadáver,59
61606,BO_1978_02102,gomez vda. de m concepcion,100.0,Cadáver,69
63909,BO_1978_04405,rivera zavala emma,102.0,Cadáver,140
66092,BO_1978_06588,desconocido,-72.0,Cadáver,232
66813,BO_1979_00156,aguas landoverde sacramento,668.0,Cadáver,7
67413,BO_1979_00756,cruz fernandez reynalda,100.0,Cadáver,25
68824,BO_1979_02167,garcia campos,100.0,Cadáver,70
70117,BO_1979_03460,morales lopez graciela,226.0,Cadáver,110
70426,BO_1979_03769,nieto tapia teodomira,116.0,Cadáver,119
70708,BO_1979_04051,perez espinoza carlos,107.0,Cadáver,129
70882,BO_1979_04225,quiroz novarro juan m.,232.0,Cadáver,135

In [14]:
df.groupby('Tipo_restos').agg({
    'Edad_estandar':['min','mean','max']
})

              Edad_estandar
                        min       mean     max
Tipo_restos
Cadáver               -72.0  36.686759  5575.0
Feto                    0.0   0.000000     0.0
Miembros                0.0  35.586626    91.0
Recién nacido           0.0   0.000000     0.0
Restos óseos           16.0  26.000000    40.0
S-D                     NaN        NaN     NaN

In [15]:
df['Edad_estandar'] = df['Edad_estandar'].abs()
df.loc[ df['Edad_estandar']>100, 'Edad_estandar'] = nan

In [16]:
df['Edad_rango'] = pd.cut(df['Edad_estandar'], bins=[-1,0] + list(range(4,101,5)))
df['Edad_rango'].value_counts(dropna=False)

Edad_rango
NaN             54632
(-1.0, 0.0]      4666
(24.0, 29.0]     3821
(19.0, 24.0]     3810
(34.0, 39.0]     3217
(29.0, 34.0]     3032
(39.0, 44.0]     2753
(44.0, 49.0]     2680
(14.0, 19.0]     2453
(49.0, 54.0]     2358
(0.0, 4.0]       1964
(59.0, 64.0]     1867
(54.0, 59.0]     1779
(64.0, 69.0]     1622
(69.0, 74.0]     1570
(4.0, 9.0]       1402
(9.0, 14.0]      1237
(74.0, 79.0]     1028
(79.0, 84.0]      538
(84.0, 89.0]      266
(89.0, 94.0]      121
(94.0, 99.0]       44
Name: count, dtype: int64

## Expediente_SEMEFO_transcrito

## Procedencia_transcrito
### Procedencia_estandar
### Procedencia_direccion
### Procedencia_alcaldia

In [17]:
df['Procedencia_estandar'] = df['Procedencia_estandar'].astype("category")
display( df['Procedencia_estandar'].value_counts(dropna=False) )
df['Procedencia_alcaldia'] = df['Procedencia_alcaldia'].astype("category")
display( df['Procedencia_alcaldia'].value_counts(dropna=False) )

Procedencia_estandar
S-D         26862
32A          3635
33A          3054
37A          2812
1A           2444
            ...
CU-2            2
DGAP            2
Grupo 4o        2
Gpo 1           2
31A             2
Name: count, Length: 110, dtype: int64

Procedencia_alcaldia
NaN                    31972
Cuauhtémoc             10682
Miguel Hidalgo         10493
Gustavo A. Madero       9010
Benito Juárez           8645
Venustiano Carranza     7579
Iztacalco               4232
Coyoacán                2638
Álvaro Obregón          2412
Iztapalapa              2356
Azcapotzalco            2203
Tlalpan                 1619
Xochimilco              1146
Cuajimalpa               770
Tláhuac                  483
Magdalena Conteras       367
Milpa Alta               253
Name: count, dtype: int64

In [18]:
procedencias = df[['Procedencia_transcrito', 'Procedencia_estandar', 'Procedencia_direccion', 'Procedencia_alcaldia']]
procedencias = procedencias.value_counts(dropna=False)
procedencias.to_csv('catalogos/conteo_procedencia.csv')
procedencias

Procedencia_transcrito  Procedencia_estandar  Procedencia_direccion                        Procedencia_alcaldia
S-D                     S-D                   Sin datos                                    nan                     26862
32a                     32A                   Ministerio Público 32                        nan                      2073
33a                     33A                   Ministerio Público 33 (Col Jardín Balbuena)  Venustiano Carranza      1970
37a                     37A                   Ministerio Público 37 (Col Polanco)          Miguel Hidalgo           1701
32                      32A                   Ministerio Público 32                        nan                      1562
                                                                                                                   ...
C-H-6                   nan                   NaN                                          nan                         1
C-H-5                   nan                   NaN                                          nan                         1
C-H                     nan                   NaN                                          nan                         1
C-GAM-HV                nan                   NaN                                          nan                         1
xoco                    nan                   NaN                                          nan                         1
Name: count, Length: 809, dtype: int64

## Numero_acta_transcrito
### Procedencia_acta

In [19]:
df['Procedencia_acta'] = df[['Procedencia_estandar','Numero_acta_transcrito']].replace('S-D',nan) \
                         .apply(join_strings_with_nans,sep='/',axis=1)
df['Procedencia_acta'].value_counts(dropna=False)

Procedencia_acta
NaN          25660
26A/144         27
HX              16
TP-1/868        13
10A/1658        12
             ...
GAM-1/196        1
TC-1/12          1
VC-1/183         1
VC-1/191         1
9A/4193          1
Name: count, Length: 55649, dtype: int64

## Diagnostico_transcrito
### Diagnostico_estandar
### Diagnostico_extendido

In [20]:
df['Diagnostico_estandar'] = df['Diagnostico_estandar'].astype("category")
display( df['Diagnostico_estandar'].value_counts(dropna=False) )

Diagnostico_estandar
S-D            55911
NaN             8267
TM              7513
TCE             5951
BN              1859
               ...
SH                 2
P                  2
APENDICITIS        1
NECROSIS           1
E                  1
Name: count, Length: 109, dtype: int64

In [21]:
cols = ['Procedencia_direccion', 'Procedencia_alcaldia','Diagnostico_extendido']
df[cols] = df[cols].replace('sin datos','S-D')

## Tipo_restos
## Conocido_desconocido
## Bitacora_ingresos
### Pagina_PDF
### Foja_transcrito
### Observaciones

In [22]:
cat_type = ['Cadáver', 'Recién nacido', 'Feto', 'Miembros', 'Restos óseos', 'S-D']
cat_type = pd.CategoricalDtype(categories=cat_type, ordered=True)
df['Tipo_restos'] = df['Tipo_restos'].astype(cat_type)
display( df['Tipo_restos'].value_counts(dropna=False) )

Tipo_restos
Cadáver          91253
Feto              2844
Miembros          2064
Recién nacido      633
Restos óseos        48
S-D                 18
Name: count, dtype: int64

In [23]:
df['Conocido_desconocido'] = df['Conocido_desconocido'].astype("category")
display( df['Conocido_desconocido'].value_counts(dropna=False) )
df['Bitacora_ingresos'] = df['Bitacora_ingresos'].astype("category")
display( df['Bitacora_ingresos'].value_counts(dropna=False) )

Conocido_desconocido
conocido       78612
desconocido    18248
Name: count, dtype: int64

Bitacora_ingresos
semefo_df_bo_1981    7629
semefo_df_bo_1980    7619
semefo_df_bo_1982    7493
semefo_df_bo_1979    7461
semefo_df_bo_1977    7166
semefo_df_bo_1978    7154
semefo_df_bo_1976    6907
semefo_df_bo_1975    6861
semefo_df_bo_1973    6471
semefo_df_bo_1972    5770
semefo_df_bo_1974    5731
semefo_df_bo_1971    5524
semefo_df_bo_1970    5303
semefo_df_bo_1969    5052
semefo_df_bo_1968    4719
Name: count, dtype: int64

## Guardar

In [24]:
df = df[['ID', 'Numero_progresivo_transcrito', 'Nombre_completo_transcrito',
         'Primer_apellido', 'Segundo_apellido', 'Nombres_propios',
         'Fecha_transcrito', 'Fecha_estandar', 'Fecha_añomes', 'Fecha_diasemana',
         'Sexo', 'Edad_transcrito', 'Edad_estandar', 'Edad_rango', 
         'Expediente_SEMEFO_transcrito', 'Procedencia_transcrito', 'Procedencia_estandar',
         'Procedencia_direccion', 'Procedencia_alcaldia', 'Numero_acta_transcrito', 'Procedencia_acta', 
         'Diagnostico_transcrito', 'Diagnostico_estandar', 'Diagnostico_extendido', 
         'Tipo_restos', 'Conocido_desconocido',  'Bitacora_ingresos',
         'Pagina_PDF', 'Foja_transcrito', 'Observaciones',
         ]]
df.to_csv('data_clean/SEMEFO_BO_all_revision.csv', index=False)
df.to_pickle('data_clean/SEMEFO_BO_all.pkl')

f_profile = 'profiles/SEMEFO_BO_all_revision_profile.html'
profile_minimal(df, f_profile)

/home/esther/anaconda3/envs/SEMEFO_busqueda/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Ignoring profiles/SEMEFO_BO_all_revision_profile.html file alredy exists