# Bitacoras onomásticas SEMEFO 1968-1982
# Revisión de bitacoras integradas

In [1]:
import pandas as pd
from numpy import nan

from itertools import product
from helper_pandas import  profile_minimal, translate_datetime, \
                          join_strings_with_nans, simplify_string

In [2]:
data_file = "data_raw/SEMEFO_integracion_20231006.csv"
df = pd.read_csv(data_file, dtype='str')
df

,ID,Numero_progresivo_transcrito,Nombre_completo_transcrito,Primer_apellido,Segundo_apellido,Nombres_propios,Fecha_transcrito,Fecha_estandar,Expediente_SEMEFO_transcrito,Procedencia_transcrito,...,Diagnostico_extendido,Sexo,Edad_transcrito,Edad_estandar,Tipo_restos,Bitacora_ingresos,Pagina_PDF,Foja_transcrito,Observaciones,Conocido_desconocido
0,BO_1968_00001,NaN,acosta ortega teresa,acosta,ortega,teresa,1968-01-03,1968-01-03,37,S-D,...,sin datos,Femenino,S-D,NaN,Cadáver,semefo_df_bo_1968,2,1,NaN,conocido
1,BO_1968_00002,NaN,avila de cuestas catalina,avila,de cuestas,catalina,1968-01-05,1968-01-05,58,S-D,...,sin datos,Femenino,S-D,NaN,Cadáver,semefo_df_bo_1968,2,1,NaN,conocido
2,BO_1968_00003,NaN,arzate paredes juan,arzate,paredes,juan,1968-01-07,1968-01-07,83,S-D,...,sin datos,Masculino,S-D,NaN,Cadáver,semefo_df_bo_1968,2,1,NaN,conocido
3,BO_1968_00004,NaN,alvarez martinez isaac,alvarez,martinez,isaac,1968-01-07,1968-01-07,86,S-D,...,sin datos,Masculino,S-D,NaN,Cadáver,semefo_df_bo_1968,2,1,NaN,conocido
4,BO_1968_00005,NaN,arellano viuda de campos ma.,arellano,viuda de campos,ma.,1968-01-07,1968-01-07,88,S-D,...,sin datos,Femenino,S-D,NaN,Cadáver,semefo_df_bo_1968,2,1,NaN,conocido
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96839,BO_1982_07489,NaN,placenta,s-d,s-d,s-d,1982-06-05,1982-06-05,3079,15a,...,sin datos,S-D,S-D,NaN,Miembros,semefo_df_bo_1982,251,156,NaN,desconocido
96840,BO_1982_07490,NaN,5 dedos del pie derecho de desconocido,s-d,s-d,s-d,1982-06-05,1982-06-05,3060,32a,...,sin datos,S-D,S-D,NaN,Miembros,semefo_df_bo_1982,251,156,NaN,desconocido
96841,BO_1982_07491,NaN,dedo de desconocido,s-d,s-d,s-d,1982-11-19,1982-11-19,6389,32a,...,sin datos,S-D,S-D,NaN,Miembros,semefo_df_bo_1982,251,156,NaN,desconocido
96842,BO_1982_07492,NaN,4 dedos de desconocido,s-d,s-d,s-d,1982-11-28,1982-11-28,6528,27a,...,sin datos,S-D,S-D,NaN,Miembros,semefo_df_bo_1982,251,156,NaN,desconocido
96843,BO_1982_07493,NaN,osamenta de desconocido,s-d,s-d,s-d,1982-10-11,1982-10-11,5629,9a,...,sin datos,S-D,S-D,NaN,Cadáver,semefo_df_bo_1982,251,156,no se recibio necropsia. es una osamenta.,desconocido

## ID

In [3]:
# Format
df.loc[(df['ID'].str.startswith('BO')!=True)]

Empty DataFrame
Columns: [ID, Numero_progresivo_transcrito, Nombre_completo_transcrito, Primer_apellido, Segundo_apellido, Nombres_propios, Fecha_transcrito, Fecha_estandar, Expediente_SEMEFO_transcrito, Procedencia_transcrito, Procedencia_estandar, Procedencia_direccion, Procedencia_alcaldia, Numero_acta_transcrito, Procedencia_acta, Diagnostico_transcrito, Diagnostico_estandar, Diagnostico_extendido, Sexo, Edad_transcrito, Edad_estandar, Tipo_restos, Bitacora_ingresos, Pagina_PDF, Foja_transcrito, Observaciones, Conocido_desconocido]
Index: []

[0 rows x 27 columns]

In [4]:
# Format
data = pd.DataFrame([row.split('_') for row in df['ID'].to_list()], columns=['BO', 'year','ID'])
data.index = df['ID']
data['year'] = pd.to_numeric(data['year'], downcast='integer')
data['ID'] = pd.to_numeric(data['ID'], downcast='integer')

data.groupby('year').agg({
            'BO':'size',
            'ID':['max', pd.Series.nunique]
            })

        BO    ID
      size   max nunique
year
1968  4719  4719    4719
1969  5052  5052    5052
1970  5303  5303    5303
1971  5524  5524    5524
1972  5768  5768    5768
1973  6471  6471    6471
1974  5731  5731    5731
1975  6861  6861    6861
1976  6907  6907    6907
1977  7166  7166    7166
1978  7140  7140    7140
1979  7461  7461    7461
1980  7619  7619    7619
1981  7629  7629    7629
1982  7493  7493    7493

## Numero_progresivo

In [5]:
col = 'Numero_progresivo_transcrito'
df[col] = pd.to_numeric(df[col], downcast='integer')
df[col].value_counts(dropna=False)

Numero_progresivo_transcrito
NaN      69673
41.0       110
38.0       110
37.0       109
40.0       109
         ...
921.0        1
920.0        1
919.0        1
918.0        1
917.0        1
Name: count, Length: 924, dtype: int64

## Nombre_completo_transcrito, 
### Primer_apellido
### Segundo_apellido
### Nombres_propios

In [6]:
cols = ['Nombre_completo_transcrito', 'Primer_apellido', 'Segundo_apellido', 'Nombres_propios', ]
df[cols] = df[cols].replace('s-d','S-D')

display( (df[cols]=='S-D').sum() )

Nombre_completo_transcrito       24
Primer_apellido               18098
Segundo_apellido              21917
Nombres_propios               18136
dtype: int64

## Fecha_transcrito
### Fecha_estandar
### Fecha_añomes
### Fecha_diasemana

In [7]:
df['Fecha_estandar'] = pd.to_datetime(df['Fecha_transcrito'], errors='coerce')
df['Fecha_estandar'].value_counts(dropna=False)

Fecha_estandar
NaT           265
1982-03-27     46
1979-12-26     43
1981-12-26     41
1977-04-19     41
             ...
1968-05-03      3
1971-09-29      3
1970-05-05      2
1968-05-26      2
1968-04-25      2
Name: count, Length: 5480, dtype: int64

In [8]:
df['Fecha_año'] = df['Fecha_estandar'].dt.year.fillna('') \
                  .apply(lambda s: str(int(s)) if s!='' else nan)
display( df['Fecha_año'].value_counts(dropna=False).to_dict() )

df['Fecha_mes'] = translate_datetime(df['Fecha_estandar'].dt.month_name())
display( df['Fecha_mes'].value_counts(dropna=False).to_dict() )

df['Fecha_añomes'] = df[['Fecha_año','Fecha_mes']] \
                       .apply(join_strings_with_nans, sep=' ', axis=1)
df = df.drop(['Fecha_año','Fecha_mes'], axis=1)
df['Fecha_añomes'].value_counts(dropna=False)

{'1981': 7615,
 '1980': 7604,
 '1982': 7481,
 '1979': 7428,
 '1977': 7132,
 '1978': 7112,
 '1976': 6892,
 '1975': 6854,
 '1973': 6214,
 '1974': 5947,
 '1972': 5754,
 '1971': 5503,
 '1970': 5282,
 '1969': 5045,
 '1968': 4716,
 nan: 265}

{'Diciembre': 9427,
 'Enero': 8798,
 'Marzo': 8200,
 'Octubre': 8166,
 'Noviembre': 8092,
 'Agosto': 8086,
 'Julio': 7826,
 'Septiembre': 7765,
 'Mayo': 7749,
 'Abril': 7561,
 'Febrero': 7538,
 'Junio': 7371,
 nan: 265}

Fecha_añomes
1977 Diciembre    762
1981 Diciembre    752
1979 Diciembre    743
1982 Diciembre    716
1977 Enero        714
                 ...
1968 Julio        366
1969 Agosto       365
1968 Mayo         343
1968 Abril        319
NaN               265
Name: count, Length: 181, dtype: int64

In [9]:
replace = {'1970-04-31': '1970 Abril', '1970-02-29': '1970 Febrero', '1971-02-29': '1971 Febrero', '1972-02-30': '1972 Febrero', '1974-02-29': '1974 Febrero', '1976-04-31': '1976 Abril', '1976-11-31': '1976 Noviembre', '1976-06-31': '1976 Junio', '1976-02-31': '1976 Febrero', '1978-02-30': '1978 Febrero', '1978-02': '1978 Febrero', '1977-12': '1977 Diciembre', '1978-04': '1978 Abril', '1978-05': '1978 Mayo', '1979-11-31': '1979 Noviembre', '1979-02-29': '1979 Febrero', '1979-02-30': '1979 Febrero', '1979-02-31': '1979 Febrero', '1979-08': '1979 Agosto', '1979-09': '1979 Septiembre', '1979-01': '1979 Enero', '1980-06-31': '1980 Junio', '1981-02-31': '1981 Febrero', '31/04/1981': '1981 Abril', }
df['Fecha_añomes'] = df['Fecha_añomes'].fillna(df['Fecha_transcrito']).replace(replace)
df.loc[(df['Fecha_estandar'].isna()) & (df['Fecha_añomes']!='S-D'),['ID','Fecha_transcrito','Fecha_añomes']]

                  ID Fecha_transcrito     Fecha_añomes
10937  BO_1970_01167       1970-04-31       1970 Abril
12766  BO_1970_02996       1970-02-29     1970 Febrero
13004  BO_1970_03234       1970-02-29     1970 Febrero
15392  BO_1971_00319       1971-02-29     1971 Febrero
26128  BO_1972_05531       1972-02-30     1972 Febrero
34844  BO_1974_02008       1974-02-29     1974 Febrero
45884  BO_1976_00456       1976-04-31       1976 Abril
46016  BO_1976_00588       1976-11-31   1976 Noviembre
46718  BO_1976_01290       1976-06-31       1976 Junio
47889  BO_1976_02461       1976-02-31     1976 Febrero
48119  BO_1976_02691       1976-04-31       1976 Abril
48393  BO_1976_02965       1976-02-31     1976 Febrero
60730  BO_1978_01229       1978-02-30     1978 Febrero
62431  BO_1978_02930          1978-02     1978 Febrero
64287  BO_1978_04786          1977-12   1977 Diciembre
66623  BO_1978_07122          1978-04       1978 Abril
66624  BO_1978_07123          1978-05        1978 Mayo
66979  BO_1979_00338       1979-11-31   1979 Noviembre
67068  BO_1979_00427       1979-02-29     1979 Febrero
67069  BO_1979_00428       1979-02-30     1979 Febrero
67070  BO_1979_00429       1979-02-31     1979 Febrero
70128  BO_1979_03487          1979-08      1979 Agosto
70129  BO_1979_03488          1979-08      1979 Agosto
70130  BO_1979_03489          1979-09  1979 Septiembre
71845  BO_1979_05204          1979-01       1979 Enero
72688  BO_1979_06047       1979-02-29     1979 Febrero
79483  BO_1980_05381       1980-06-31       1980 Junio
88090  BO_1981_06369       1981-02-31     1981 Febrero
88281  BO_1981_06560       31/04/1981       1981 Abril
88282  BO_1981_06561       31/04/1981       1981 Abril
88283  BO_1981_06562       31/04/1981       1981 Abril
88298  BO_1981_06577       31/04/1981       1981 Abril

In [10]:
año = [str(i) for i in range(1968, 1983)]
mes = ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 
       'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre', ]
cat_type = ['S-D'] + [' '.join(p) for p in product(año, mes)]
cat_type = pd.CategoricalDtype(categories=cat_type, ordered=True)

df['Fecha_añomes'] = df['Fecha_añomes'].astype(cat_type)
df['Fecha_añomes'].value_counts(dropna=False)

Fecha_añomes
1977 Diciembre    763
1981 Diciembre    752
1979 Diciembre    743
1982 Diciembre    716
1980 Diciembre    714
                 ...
1969 Febrero      366
1969 Agosto       365
1968 Mayo         343
1968 Abril        319
S-D               233
Name: count, Length: 181, dtype: int64

In [11]:
df['Fecha_diasemana'] = translate_datetime(df['Fecha_estandar'].dt.day_name())
dia = ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado', 'Domingo']
cat_type = pd.CategoricalDtype(categories=dia, ordered=True)
df['Fecha_diasemana'] = df['Fecha_diasemana'].astype(cat_type)
df['Fecha_diasemana'].value_counts(dropna=False)

Fecha_diasemana
Lunes        16578
Martes       15090
Miércoles    13615
Jueves       13132
Domingo      12731
Sábado       12727
Viernes      12706
NaN            265
Name: count, dtype: int64

## Sexo

In [12]:
df['Sexo'] = df['Sexo'].astype("category")
df['Sexo'].value_counts(dropna=False)

Sexo
Masculino    73741
Femenino     20601
S-D           2502
Name: count, dtype: int64

## Edad_transcrito
### Edad_estandar
### Edad_rango

In [13]:
from math import floor
from helper_pandas import to_dtype_with_errors

def replace_edades_menor_al_año(edad):
    if type(edad)==str:
        edad_ = simplify_string(edad)
        edad_ = edad_.replace(' 1/2','.5')
        edad_ = edad_.replace('horas','hora').replace('dias','dia').replace('semanas','semana').replace('meses','mes').replace('anos','ano')
        dic_time = {'ano':1, 'mes':12, 'semana':52, 'dia':365, 'hora':8766}
        for nombre, n in dic_time.items():
            if nombre in edad_:
                edad_ = simplify_string( edad_.replace(nombre,'') )
                try: edad_ = float(edad_)
                except ValueError: return edad
                return floor( edad_ / n )
        dic_time = {'a':1, 'm':12, 'd':365}
        for nombre, n in dic_time.items():
            if nombre in edad_:
                edad_ = simplify_string( edad_.replace(nombre,'') )
                try: edad_ = float(edad_)
                except ValueError: return edad
                return floor( edad_ / n )
        try: edad_ = float(edad_)
        except(ValueError): return edad
        return floor(edad_)
    return edad

dic_replace = {'[1-10 días]':0, '10 SEMNS':0, '15-30 días':0, '2 mese':0, '2 o 3 meses':0, '30 - 90 días':0, '5 meses 15 días':0, 
               '6 meses UI':0, '7 - 12 meses':0, '72 hrs':0, '-12 horas':1, '1 año 3 meses':1, '1 año 4 meses':1, '1 año 7 meses':1, 
               '1 Y 8 meses':1, '15 mese':1, '18 mese':1, '3 años y medio ':3, '7 añoss':7, '[8]':8, '-72 años':72, ' S-D':'S-D', 
               '-':'S-D', '?':'S-D', 'F':'S-D', 'M':'S-D', 'S-d':'S-D', '-72 años':72, '-1':1, '2/6':'S-D', '$45':45, '3-5':4, 
               ' +3-5':4,'7-9':8,' +6-8':7,' +7-9':8,'4-6':5,'5-7':6,'6-8':7,'4 y 5':'S-D',' +4-6':5,'8 años7':8,'más 72':'S-D',
               '1 - 3':2,'1-2':1,'9-9':9,'3-4':3,'7-8':7,'2-4':3,'8 Ins.':8,'41 n':41,'R.N':0,'18-25':21, '7 - 9':8,
               '25-30':27,' +3-4':3,' +5-6':5,' +2-3':2,' +4-7':5,' +7-8':7,' +5-7':6,' +6-7':6,'25-40':'S-D','20 o 24':22,'25/30':22,
               #'8 172':'S-D',
              }

df['Edad_estandar'] = df['Edad_transcrito']
df['Edad_estandar'] = df['Edad_estandar'].apply(replace_edades_menor_al_año) \
                       .replace(',','.', regex=True).replace(dic_replace)
df = to_dtype_with_errors(df, 'Edad_estandar')
df.loc[df['Tipo_restos'].isin(['Feto','Recién nacido']), 'Edad_estandar_clean'] = 0
df['Edad_estandar'] = df['Edad_estandar_clean']
df = df.drop(['Edad_estandar_clean', 'Edad_estandar_error'], axis=1)
df['Edad_estandar'].value_counts()

Edad_estandar
 0.0      4666
 40.0     1728
 30.0     1710
 35.0     1666
 25.0     1619
          ...
 2.5         1
-1.0         1
 108.0       1
 116.0       1
 107.0       1
Name: count, Length: 110, dtype: int64

In [14]:
df.loc[(df['Edad_estandar']>99) | (df['Edad_estandar']<0), 
       ['ID','Nombre_completo_transcrito','Edad_estandar','Tipo_restos','Pagina_PDF']]

,ID,Nombre_completo_transcrito,Edad_estandar,Tipo_restos,Pagina_PDF
37066,BO_1974_04230,salas viuda de barroso guadalupe,103.0,Cadáver,138
41009,BO_1975_02442,jaramillo cervantes leonarda,102.0,Cadáver,77
43124,BO_1975_04557,rodriguez vda de a maria dolores,100.0,Cadáver,140
43343,BO_1975_04776,sandoval ortiz castulo,-1.0,Cadáver,147
49952,BO_1976_04524,reyes clara antonia,102.0,Cadáver,141
50067,BO_1976_04639,sanchez guerrero emiliano,102.0,Cadáver,144
50823,BO_1976_05395,vergara rios eugenia,100.0,Cadáver,166
52911,BO_1977_00576,benitez rojas alberto,102.0,Cadáver,19
54100,BO_1977_01765,guerrero alvarez ana maria,100.0,Cadáver,56
57630,BO_1977_05295,ubaldo guillen angel,103.0,Cadáver,166
61258,BO_1978_01757,gonzalez barragan arcadio,108.0,Cadáver,59
61597,BO_1978_02096,gomez vda. de m concepcion,100.0,Cadáver,69
63892,BO_1978_04391,rivera zavala emma,102.0,Cadáver,140
67397,BO_1979_00756,cruz fernandez reynalda,100.0,Cadáver,25
68808,BO_1979_02167,garcia campos,100.0,Cadáver,70
70410,BO_1979_03769,nieto tapia teodomira,116.0,Cadáver,119
70692,BO_1979_04051,perez espinoza carlos,107.0,Cadáver,129

In [15]:
df['Edad_estandar'] = df['Edad_estandar'].abs()
df['Edad_estandar'].value_counts()

Edad_estandar
0.0      4666
40.0     1728
30.0     1710
35.0     1666
25.0     1619
         ...
7.5         1
2.5         1
108.0       1
116.0       1
107.0       1
Name: count, Length: 109, dtype: int64

In [16]:
df.groupby('Tipo_restos').agg({
    'Edad_estandar':['min','mean','max']
})

              Edad_estandar
                        min       mean    max
Tipo_restos
Cadáver                 0.0  36.517183  116.0
Feto                    0.0   0.000000    0.0
Miembros                0.0  35.586626   91.0
Recién nacido           0.0   0.000000    0.0
Restos óseos           16.0  26.000000   40.0

In [17]:
df['Edad_rango'] = pd.cut(df['Edad_estandar'], bins=[-1,0] + list(range(4,99,5)) + [df['Edad_estandar'].max()] )
df['Edad_rango'].value_counts(dropna=False).sort_index()

Edad_rango
(-1.0, 0.0]       4666
(0.0, 4.0]        1964
(4.0, 9.0]        1402
(9.0, 14.0]       1237
(14.0, 19.0]      2454
(19.0, 24.0]      3811
(24.0, 29.0]      3822
(29.0, 34.0]      3032
(34.0, 39.0]      3217
(39.0, 44.0]      2753
(44.0, 49.0]      2680
(49.0, 54.0]      2358
(54.0, 59.0]      1780
(59.0, 64.0]      1867
(64.0, 69.0]      1623
(69.0, 74.0]      1569
(74.0, 79.0]      1028
(79.0, 84.0]       538
(84.0, 89.0]       266
(89.0, 94.0]       121
(94.0, 116.0]       60
NaN              54596
Name: count, dtype: int64

## Expediente_SEMEFO_transcrito

## Procedencia_transcrito
### Procedencia_estandar
### Procedencia_direccion
### Procedencia_alcaldia

In [18]:
df['Procedencia_estandar'] = df['Procedencia_estandar'].astype("category")
display( df['Procedencia_estandar'].value_counts(dropna=False) )
df['Procedencia_alcaldia'] = df['Procedencia_alcaldia'].astype("category")
display( df['Procedencia_alcaldia'].value_counts(dropna=False) )

Procedencia_estandar
S-D         26833
32A          3635
33A          3054
37A          2812
1A           2445
            ...
T-23            2
IZO-2           2
Iztacala        2
GAM             2
H.T.B.          1
Name: count, Length: 111, dtype: int64

Procedencia_alcaldia
NaN                    31946
Cuauhtémoc             10686
Miguel Hidalgo         10494
Gustavo A. Madero       9012
Benito Juárez           8647
Venustiano Carranza     7580
Iztacalco               4232
Coyoacán                2638
Álvaro Obregón          2412
Iztapalapa              2356
Azcapotzalco            2203
Tlalpan                 1619
Xochimilco              1146
Cuajimalpa               770
Tláhuac                  483
Magdalena Conteras       367
Milpa Alta               253
Name: count, dtype: int64

In [19]:
procedencias = df[['Procedencia_transcrito', 'Procedencia_estandar', 'Procedencia_direccion', 'Procedencia_alcaldia']]
procedencias = procedencias.value_counts(dropna=False)
procedencias.to_csv('catalogos/conteo_procedencia.csv')
procedencias

Procedencia_transcrito  Procedencia_estandar  Procedencia_direccion                        Procedencia_alcaldia
S-D                     S-D                   Sin datos                                    nan                     25780
32a                     32A                   Ministerio Público 32                        nan                      2073
33a                     33A                   Ministerio Público 33 (Col Jardín Balbuena)  Venustiano Carranza      1968
37a                     37A                   Ministerio Público 37 (Col Polanco)          Miguel Hidalgo           1701
32                      32A                   Ministerio Público 32                        nan                      1562
                                                                                                                   ...
C-I [HX]                nan                   NaN                                          nan                         1
C-MH+HRL                HRL                   Hospital Rubén Leñero (Col Santo Tomás)      Miguel Hidalgo              1
C-MH-1                  nan                   NaN                                          nan                         1
C-MH-2                  nan                   NaN                                          nan                         1
xoco                    nan                   NaN                                          nan                         1
Name: count, Length: 921, dtype: int64

## Numero_acta_transcrito
### Procedencia_acta

In [20]:
df['Procedencia_acta'] = df[['Procedencia_estandar','Numero_acta_transcrito']].replace('S-D',nan) \
                         .apply(join_strings_with_nans,sep='/',axis=1)
df['Procedencia_acta'].value_counts(dropna=False)

Procedencia_acta
NaN         25642
26A/144        27
HX             16
TP-1/868       13
10A/1658       12
            ...
AO-1/325        1
HTV/185         1
TP-1/181        1
VC-1/353        1
9A/4193         1
Name: count, Length: 55652, dtype: int64

## Diagnostico_transcrito
### Diagnostico_estandar
### Diagnostico_extendido

In [21]:
df['Diagnostico_estandar'] = df['Diagnostico_estandar'].astype("category")
display( df['Diagnostico_estandar'].value_counts(dropna=False) )

Diagnostico_estandar
S-D            55895
NaN             8267
TM              7513
TCE             5951
BN              1859
               ...
SH                 2
P                  2
APENDICITIS        1
NECROSIS           1
E                  1
Name: count, Length: 109, dtype: int64

In [22]:
cols = ['Procedencia_direccion', 'Procedencia_alcaldia','Diagnostico_extendido']
df[cols] = df[cols].replace('sin datos','S-D')

## Tipo_restos
## Conocido_desconocido

In [23]:
df[df['Tipo_restos']=='S-D']

Empty DataFrame
Columns: [ID, Numero_progresivo_transcrito, Nombre_completo_transcrito, Primer_apellido, Segundo_apellido, Nombres_propios, Fecha_transcrito, Fecha_estandar, Expediente_SEMEFO_transcrito, Procedencia_transcrito, Procedencia_estandar, Procedencia_direccion, Procedencia_alcaldia, Numero_acta_transcrito, Procedencia_acta, Diagnostico_transcrito, Diagnostico_estandar, Diagnostico_extendido, Sexo, Edad_transcrito, Edad_estandar, Tipo_restos, Bitacora_ingresos, Pagina_PDF, Foja_transcrito, Observaciones, Conocido_desconocido, Fecha_añomes, Fecha_diasemana, Edad_rango]
Index: []

[0 rows x 30 columns]

In [24]:
cat_type = ['Cadáver', 'Recién nacido', 'Feto', 'Miembros', 'Restos óseos']
cat_type = pd.CategoricalDtype(categories=cat_type, ordered=True)
df['Tipo_restos'] = df['Tipo_restos'].astype(cat_type)
display( df['Tipo_restos'].value_counts(dropna=False) )

Tipo_restos
Cadáver          91254
Feto              2844
Miembros          2065
Recién nacido      633
Restos óseos        48
Name: count, dtype: int64

In [25]:
display( df['Conocido_desconocido'].value_counts(dropna=False) )

Conocido_desconocido
conocido       78613
desconocido    18212
S-D               19
Name: count, dtype: int64

In [26]:
df['Conocido_desconocido'] = df['Conocido_desconocido'].replace('S-D','desconocido')
df['Conocido_desconocido'] = df['Conocido_desconocido'].astype("category")
display( df['Conocido_desconocido'].value_counts(dropna=False) )

Conocido_desconocido
conocido       78613
desconocido    18231
Name: count, dtype: int64

## Bitacora_ingresos
### Pagina_PDF
### Foja_transcrito
### Observaciones

In [27]:
df['Bitacora_ingresos'] = df['Bitacora_ingresos'].astype("category")
display( df['Bitacora_ingresos'].value_counts(dropna=False) )

Bitacora_ingresos
semefo_df_bo_1981    7629
semefo_df_bo_1980    7619
semefo_df_bo_1982    7493
semefo_df_bo_1979    7461
semefo_df_bo_1977    7166
semefo_df_bo_1978    7140
semefo_df_bo_1976    6907
semefo_df_bo_1975    6861
semefo_df_bo_1973    6471
semefo_df_bo_1972    5768
semefo_df_bo_1974    5731
semefo_df_bo_1971    5524
semefo_df_bo_1970    5303
semefo_df_bo_1969    5052
semefo_df_bo_1968    4719
Name: count, dtype: int64

In [28]:
df['Pagina_PDF'] = pd.to_numeric(df['Pagina_PDF'], downcast='integer')

In [29]:
df.groupby('Bitacora_ingresos').agg({'Pagina_PDF':'max'}).sum()

Pagina_PDF    3276
dtype: int64

## Guardar

In [30]:
df = df[['ID', 'Numero_progresivo_transcrito', 'Nombre_completo_transcrito',
         'Primer_apellido', 'Segundo_apellido', 'Nombres_propios',
         'Fecha_transcrito', 'Fecha_estandar', 'Fecha_añomes', 'Fecha_diasemana',
         'Sexo', 'Edad_transcrito', 'Edad_estandar', 'Edad_rango', 
         'Expediente_SEMEFO_transcrito', 'Procedencia_transcrito', 'Procedencia_estandar',
         'Procedencia_direccion', 'Procedencia_alcaldia', 'Numero_acta_transcrito', 'Procedencia_acta', 
         'Diagnostico_transcrito', 'Diagnostico_estandar', 'Diagnostico_extendido', 
         'Tipo_restos', 'Conocido_desconocido',  'Bitacora_ingresos',
         'Pagina_PDF', 'Foja_transcrito', 'Observaciones',
         ]]
df.to_csv('data_clean/SEMEFO_BO_all_revision.csv', index=False)
df.to_pickle('data_clean/SEMEFO_BO_all.pkl')

f_profile = 'profiles/SEMEFO_BO_all_revision_profile.html'
profile_minimal(df, f_profile, force=True)

/home/esther/anaconda3/envs/SEMEFO_busqueda/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Calculating profile profiles/SEMEFO_BO_all_revision_profile.html

Summarize dataset:  83%|▊| 29/35 [00:04<00:00, 14.95it/s, Describe variable:Proc

TypeError: Expected unicode, got getset_descriptor

Exception ignored in: 'pandas._libs.lib.is_interval_array'
Traceback (most recent call last):
  File "/home/esther/anaconda3/envs/SEMEFO_busqueda/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 6181, in map
    same_dtype = lib.infer_dtype(new_values, skipna=False) == self.inferred_type
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Expected unicode, got getset_descriptor

TypeError: Expected unicode, got getset_descriptor

Exception ignored in: 'pandas._libs.lib.is_interval_array'
Traceback (most recent call last):
  File "/home/esther/anaconda3/envs/SEMEFO_busqueda/lib/python3.11/site-packages/pandas/core/dtypes/cast.py", line 1204, in maybe_infer_to_datetimelike
    return lib.maybe_convert_objects(  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Expected unicode, got getset_descriptor

TypeError: Expected unicode, got getset_descriptor

Exception ignored in: 'pandas._libs.lib.is_interval_array'
Traceback (most recent call last):
  File "/home/esther/anaconda3/envs/SEMEFO_busqueda/lib/python3.11/site-packages/pandas/core/dtypes/cast.py", line 1204, in maybe_infer_to_datetimelike
    return lib.maybe_convert_objects(  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Expected unicode, got getset_descriptor
Summarize dataset: 100%|█████████████| 36/36 [00:04<00:00,  8.17it/s, Completed]
Generate report structure: 100%|██████████████████| 1/1 [00:15<00:00, 15.62s/it]
Render HTML: 100%|████████████████████████████████| 1/1 [00:00<00:00,  1.17it/s]
Export report to file: 100%|██████████████████████| 1/1 [00:00<00:00, 45.44it/s]