# Bitacoras onomásticas SEMEFO 1968-1982
# Revisión de bitacoras

In [1]:
import re
import logging
import pandas as pd
from numpy import nan
from glob import glob
from os.path import exists
from ydata_profiling import ProfileReport
from helper_pandas import simplify_string, to_dtype_with_errors
from helper_pandas import join_strings_with_nans

/home/esther/anaconda3/lib/python3.9/site-packages/numba/core/decorators.py:262: NumbaDeprecationWarning: numba.generated_jit is deprecated. Please see the documentation at: https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-generated-jit for more information and advice on a suitable replacement.
  warnings.warn(msg, NumbaDeprecationWarning)
/home/esther/anaconda3/lib/python3.9/site-packages/visions/backends/shared/nan_handling.py:51: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def hasna(x: np.ndarray) -> bool:

In [2]:
def check_bo(year, df):
    columns = {'ID':'categorical', 'Numero_progresivo':'int', 'Nombre_completo':'str', 'Primer_apellido':'str', 
               'Segundo_apellido':'str', 'Nombres_propios':'str', 'Fecha':'datetime', 'Expediente_Semefo':'categorical', 
               'Procedencia':'categorical', 'Numero_acta':'categorical', 'Diagnostico':'categorical', 'Sexo':'categorical', 
               'Edad':'int', 'Tipo_restos':'categorical', 'Bitacora_ingresos':'str', 'Pagina_PDF':'int', 'Foja':'str', 
               'Posible_identificado_como':'str', 'Observaciones_capturista':'str', }
    # check col names
    for col in columns.keys():
        if col not in df.columns:
            logging.warning('\t{}\t Missing col {}'.format(year,col))
    for col, type in columns.items():
        # format str columns
        if type=='str':
            df[col] = df[col].apply(simplify_string)
        # create columns with dtype
        elif type=='int':
            df = to_dtype_with_errors(df, col, dtype='numeric', downcast='integer')
        elif type=='datetime':
            df = to_dtype_with_errors(df, col, dtype='datetime')
    return df

In [3]:
def minimal_profile(df, f_profile, force_profile=False):
    if force_profile or not exists(f_profile):
        logging.info('\tProfile: {}'.format(f_profile))
        prof = df.profile_report(title=f_profile, minimal=True, correlations=None)
        prof.to_file(output_file=f_profile)

## Cargar df y convertir a tipo de datos

data_dir = 'data_raw/Transcritas_20230829/'
dfs = dict()
for file in glob(data_dir+'*'):
    # Load
    logging.warning(' Load: '+file)
    year = re.findall(r"\d+", file)[-1]
    df = pd.read_excel(file, dtype='str')
    logging.info('\tSize: {}'.format(df.shape))
    # Check
    df = check_bo(year, df)
    # Profile
    f_profile = file.split('/')[-1]
    f_profile = 'profiles/'+f_profile.replace('.xlsx', '_profile.html')
    minimal_profile(df, f_profile, force_profile=False)
    # Save
    dfs[year] = df

## Unir

df = pd.concat(dfs)
df = df.set_index('ID').sort_index()
df = df.dropna(how='all', axis=1)
df.to_pickle('data_clean/SEMEFO_BO_all.pkl')
df

# Procesar

In [4]:
df = pd.read_pickle('data_clean/SEMEFO_BO_all.pkl')
df.reset_index(inplace=True)
df

,ID,Numero_progresivo,Numero_progresivo_clean,Nombre_completo,Primer_apellido,Segundo_apellido,Nombres_propios,Fecha,Fecha_clean,Fecha_error,...,Edad_clean,Edad_error,Tipo_restos,Bitacora_ingresos,Pagina_PDF,Pagina_PDF_clean,Pagina_PDF_error,Foja,Posible_identificado_como,Observaciones_capturista
0,BO_1968_00001,S-D,NaN,acosta ortega teresa,acosta,ortega,teresa,1968-01-03,1968-01-03,NaN,...,NaN,NaN,Cadáver,semefo_df_bo_1968,2,2.0,NaN,1,s-d,s-d
1,BO_1968_00002,S-D,NaN,avila de cuestas catalina,avila,de cuestas,catalina,1968-01-05,1968-01-05,NaN,...,NaN,NaN,Cadáver,semefo_df_bo_1968,2,2.0,NaN,1,s-d,s-d
2,BO_1968_00003,S-D,NaN,arzate paredes juan,arzate,paredes,juan,1968-01-07,1968-01-07,NaN,...,NaN,NaN,Cadáver,semefo_df_bo_1968,2,2.0,NaN,1,s-d,s-d
3,BO_1968_00004,S-D,NaN,alvarez martinez isaac,alvarez,martinez,isaac,1968-01-07,1968-01-07,NaN,...,NaN,NaN,Cadáver,semefo_df_bo_1968,2,2.0,NaN,1,s-d,s-d
4,BO_1968_00005,S-D,NaN,arellano viuda de campos ma.,arellano,viuda de campos,ma.,1968-01-07,1968-01-07,NaN,...,NaN,NaN,Cadáver,semefo_df_bo_1968,2,2.0,NaN,1,s-d,s-d
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96855,BO_1982_07489,S-D,NaN,placenta,s-d,s-d,s-d,1982-06-05,1982-06-05,NaN,...,NaN,NaN,Miembros,semefo_df_bo_1982,251,251.0,NaN,156,s-d,s-d
96856,BO_1982_07490,S-D,NaN,5 dedos del pie derecho de desconocido,s-d,s-d,s-d,1982-06-05,1982-06-05,NaN,...,NaN,NaN,Miembros,semefo_df_bo_1982,251,251.0,NaN,156,s-d,s-d
96857,BO_1982_07491,S-D,NaN,dedo de desconocido,s-d,s-d,s-d,1982-11-19,1982-11-19,NaN,...,NaN,NaN,Miembros,semefo_df_bo_1982,251,251.0,NaN,156,s-d,s-d
96858,BO_1982_07492,S-D,NaN,4 dedos de desconocido,s-d,s-d,s-d,1982-11-28,1982-11-28,NaN,...,NaN,NaN,Miembros,semefo_df_bo_1982,251,251.0,NaN,156,s-d,s-d
96859,BO_1982_07493,S-D,NaN,osamenta de desconocido,s-d,s-d,s-d,1982-10-11,1982-10-11,NaN,...,NaN,NaN,Cadáver,semefo_df_bo_1982,251,251.0,NaN,156,s-d,no se recibio necropsia. es una osamenta.

## Numero_progresivo

In [5]:
df['Numero_progresivo'] = df['Numero_progresivo_clean']
df.drop('Numero_progresivo_clean', axis=1, inplace=True)

## Fecha

In [6]:
df.loc[df['Fecha_error'].notna(), 
       ['Nombre_completo', 'Fecha', 'Expediente_Semefo', 'Procedencia', 
        'Numero_acta', 'Diagnostico', 'Sexo', 'Edad', 'Tipo_restos']]

,Nombre_completo,Fecha,Expediente_Semefo,Procedencia,Numero_acta,Diagnostico,Sexo,Edad,Tipo_restos
8046,miembro superior de david quiroz,1969-07-21\n1969-07-18,2755,7a deleg,21259,S-D,Masculino,S-D,Miembros
10937,desconocido,1970-04-31,1920,HX,67732,S-D,Masculino,S-D,Cadáver
12766,larios toscano agapito,1970-02-29,S-D,S-D,S-D,S-D,Masculino,S-D,Cadáver
13004,m. de fausto contreras foco,1970-02-29,503,HX,67145,S-D,Masculino,S-D,Miembros
15392,benitez sanchez arturo,1971-02-29,501,S-D,S-D,S-D,Masculino,S-D,Cadáver
26130,vega bravo alfonso,1972-02-30,1478,S-D,S-D,S-D,Masculino,S-D,Cadáver
29380,desconocido,1973-09-17\n1973-07-24,3454,Coyoacan,1458,S-D,Masculino,S-D,Cadáver
34846,herrera regalado fernando,29/02/1974,476,HB,110/18/,TM,Masculino,40,Cadáver
45886,barajas bonifacio salvador,1976-04-31,2949,TP-I,583,TM,Masculino,49,Cadáver
46018,bustos rigo ignacio,1976-11-31,7098,GAM-I,3752,TM,Masculino,55,Cadáver
46720,esparza pruneda j. evaristo,1976-06-31,3429,MH-II,784,TM,Masculino,25,Cadáver
47891,jimenez mora ignacio,1976-02-31,1795,GAM-2,334,TM,Masculino,30,Cadáver
48121,lopez jaimes jose magdaleno,1976-04-31,2972,HCM,1346,TTP,Masculino,45,Cadáver
48395,moreno baltazar bernardino,1976-02-31,624,HTV,67,HPAFP,Masculino,31,Cadáver
60738,escamilla perez magdalena,1978-02-30,1086,34a,160,TT,Femenino,75,Cadáver
63495,pineda bringas guadalupe,1978-09-31,4695,6a,1667,TTP,Femenino,8 años,Cadáver
63738,rojas lias maria elena,1978-02-29,1144,36a,324,TCE,Femenino,38,Cadáver
66692,armenta morales antonio,1979-02-29,516,33a,167,TM,Masculino,37,Cadáver
66719,arciniega mexhuciro camilo,1979-02-29,1117,13a,597,HPAFPC,Masculino,22,Cadáver
66995,aviles aviles elisa,1979-11-31,6050,36a,1770,TCE,Femenino,70,Cadáver
67084,barrera munoz sacramento,1979-02-29,588,5a,382,TM,Masculino,49,Cadáver
67085,baltazar morales ruben,1979-02-30,603,23a,171,TT,Masculino,12,Cadáver
67086,bravo castillo filemon,1979-02-31,638,35a,120,TM+BN,Masculino,27,Cadáver
67348,cervantes nieves isidro,1979-02-30,612,36a,165,TM,Masculino,45,Cadáver
68802,garcia hernandez juana,1979-11-31,6210,35a,1787,"Tumor cerebral ""CA""",Femenino,57,Cadáver
69298,jimenez de gonzalez victoria,1979-10-36,5518,1a,3260,I Cerebral,Femenino,36,Cadáver
69965,mejia cortes jose,1979-06-31,3066,35a,906,TCE,Masculino,6,Cadáver
70144,monge reyes gilberto,1979-08-00,5305,34a,109,TCE+BN,Masculino,86,Cadáver
70145,martinez gutierrez josefina,1979-08-00,5304,34a,2526,TCT,Femenino,75,Cadáver
70146,morales lopez bernabe,1979-09-00,5294,7a,1254,TCE,Masculino,26,Cadáver
71861,solares rodriguez armando,1979-01-00,5318,34a,77/79,Quemaduras,Masculino,33,Cadáver
72704,desconocido,1979-02-29,1198,34a,101,Cisticercosis,Masculino,40,Cadáver
74287,araujo rodriguez manuel,1980-04-31,3013,32,1534,S-D,Masculino,S-D,Cadáver
79499,sanchez francisco tomas,1980-06-31,3023,24,1329,S-D,Masculino,S-D,Cadáver
88106,desconocido,1981-02-31,646,36,154,S-D,Masculino,S-D,Cadáver
88297,desconocido,1981-04-31,1860,18,841,S-D,Masculino,S-D,Cadáver
88298,desconocido,1981-04-31,1861,18,842,S-D,Masculino,S-D,Cadáver
88299,desconocido,1981-04-31,1865,15,455,S-D,Masculino,S-D,Cadáver
88314,desconocido,1981-04-31,1926,36,498,S-D,Masculino,S-D,Cadáver
91588,garland poole charles,1982-11-31,5973,12a,2368,S-D,Masculino,S-D,Cadáver

## Procedencia

In [7]:
df['Procedencia'] = df['Procedencia'].apply(simplify_string, str_case=None)
cat = pd.read_csv('catalogos/catalogo_procedencia.csv')
df = pd.merge(df, cat, on='Procedencia', how='left')
df.columns

df = df.rename(columns={'Equivalencia':'Procedencia_clean', 'Direccion':'Procedencia_direccion', 
                   'Alcaldia':'Procedencia_alcaldia'})
df = df[['ID', 'Numero_progresivo', 'Nombre_completo', 'Primer_apellido', 'Segundo_apellido', 'Nombres_propios', 
         'Fecha', 'Fecha_clean', 'Fecha_error', 'Expediente_Semefo', 'Procedencia', 'Procedencia_clean', 
         'Procedencia_direccion', 'Procedencia_alcaldia', 'Numero_acta', 'Diagnostico', 'Sexo', 'Edad', 
         'Edad_clean', 'Edad_error', 'Tipo_restos', 'Bitacora_ingresos', 'Pagina_PDF', 'Pagina_PDF_clean',
         'Pagina_PDF_error', 'Foja', 'Posible_identificado_como', 'Observaciones_capturista']]

df['Procedencia_clean'] = df['Procedencia_clean'].astype("category")
df['Procedencia_alcaldia'] = df['Procedencia_alcaldia'].astype("category")
df

,ID,Numero_progresivo,Nombre_completo,Primer_apellido,Segundo_apellido,Nombres_propios,Fecha,Fecha_clean,Fecha_error,Expediente_Semefo,...,Edad_clean,Edad_error,Tipo_restos,Bitacora_ingresos,Pagina_PDF,Pagina_PDF_clean,Pagina_PDF_error,Foja,Posible_identificado_como,Observaciones_capturista
0,BO_1968_00001,NaN,acosta ortega teresa,acosta,ortega,teresa,1968-01-03,1968-01-03,NaN,37,...,NaN,NaN,Cadáver,semefo_df_bo_1968,2,2.0,NaN,1,s-d,s-d
1,BO_1968_00002,NaN,avila de cuestas catalina,avila,de cuestas,catalina,1968-01-05,1968-01-05,NaN,58,...,NaN,NaN,Cadáver,semefo_df_bo_1968,2,2.0,NaN,1,s-d,s-d
2,BO_1968_00003,NaN,arzate paredes juan,arzate,paredes,juan,1968-01-07,1968-01-07,NaN,83,...,NaN,NaN,Cadáver,semefo_df_bo_1968,2,2.0,NaN,1,s-d,s-d
3,BO_1968_00004,NaN,alvarez martinez isaac,alvarez,martinez,isaac,1968-01-07,1968-01-07,NaN,86,...,NaN,NaN,Cadáver,semefo_df_bo_1968,2,2.0,NaN,1,s-d,s-d
4,BO_1968_00005,NaN,arellano viuda de campos ma.,arellano,viuda de campos,ma.,1968-01-07,1968-01-07,NaN,88,...,NaN,NaN,Cadáver,semefo_df_bo_1968,2,2.0,NaN,1,s-d,s-d
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96855,BO_1982_07489,NaN,placenta,s-d,s-d,s-d,1982-06-05,1982-06-05,NaN,3079,...,NaN,NaN,Miembros,semefo_df_bo_1982,251,251.0,NaN,156,s-d,s-d
96856,BO_1982_07490,NaN,5 dedos del pie derecho de desconocido,s-d,s-d,s-d,1982-06-05,1982-06-05,NaN,3060,...,NaN,NaN,Miembros,semefo_df_bo_1982,251,251.0,NaN,156,s-d,s-d
96857,BO_1982_07491,NaN,dedo de desconocido,s-d,s-d,s-d,1982-11-19,1982-11-19,NaN,6389,...,NaN,NaN,Miembros,semefo_df_bo_1982,251,251.0,NaN,156,s-d,s-d
96858,BO_1982_07492,NaN,4 dedos de desconocido,s-d,s-d,s-d,1982-11-28,1982-11-28,NaN,6528,...,NaN,NaN,Miembros,semefo_df_bo_1982,251,251.0,NaN,156,s-d,s-d
96859,BO_1982_07493,NaN,osamenta de desconocido,s-d,s-d,s-d,1982-10-11,1982-10-11,NaN,5629,...,NaN,NaN,Cadáver,semefo_df_bo_1982,251,251.0,NaN,156,s-d,no se recibio necropsia. es una osamenta.

In [8]:
procedencias = df[['Procedencia', 'Procedencia_clean', 'Procedencia_direccion', 'Procedencia_alcaldia']]
procedencias = procedencias.value_counts(dropna=False).reset_index()
procedencias.to_csv('data_raw/conteo_procedencia.csv', index=False)

## Numero_acta

In [9]:
data = df[['Procedencia', 'Numero_acta']].replace('S-D',nan) \
         .apply(join_strings_with_nans, sep=' -- ', axis=1)
index = df.columns.get_loc('Numero_acta')
df.insert(index+1, 'Acta_procedencia', data)
df.columns

Index(['ID', 'Numero_progresivo', 'Nombre_completo', 'Primer_apellido',
       'Segundo_apellido', 'Nombres_propios', 'Fecha', 'Fecha_clean',
       'Fecha_error', 'Expediente_Semefo', 'Procedencia', 'Procedencia_clean',
       'Procedencia_direccion', 'Procedencia_alcaldia', 'Numero_acta',
       'Acta_procedencia', 'Diagnostico', 'Sexo', 'Edad', 'Edad_clean',
       'Edad_error', 'Tipo_restos', 'Bitacora_ingresos', 'Pagina_PDF',
       'Pagina_PDF_clean', 'Pagina_PDF_error', 'Foja',
       'Posible_identificado_como', 'Observaciones_capturista'],
      dtype='object')

## Diagnostico

In [10]:
df.shape

(96860, 29)

In [11]:
cat = pd.read_csv('catalogos/catalogo_diagnostico_simplificado.csv')
df['Diagnostico'] = df['Diagnostico'].apply(simplify_string, str_case=None)
df = df.merge(cat, on='Diagnostico', how='left')
df = df.rename({'Equivalencia':'Diagnostico_estandar','Extendido':'Diagnostico_extendido'}, axis=1)
df = df[['ID', 'Numero_progresivo', 'Nombre_completo', 'Primer_apellido', 'Segundo_apellido', 'Nombres_propios', 
         'Fecha', 'Fecha_clean', 'Fecha_error', 'Expediente_Semefo', 'Procedencia', 'Procedencia_clean',
         'Procedencia_direccion', 'Procedencia_alcaldia', 'Numero_acta', 'Acta_procedencia', 'Diagnostico', 
         'Diagnostico_estandar', 'Diagnostico_extendido', 'Sexo', 'Edad', 'Edad_clean','Edad_error', 'Tipo_restos', 
         'Bitacora_ingresos', 'Pagina_PDF', 'Pagina_PDF_clean', 'Pagina_PDF_error', 'Foja', 'Posible_identificado_como', 'Observaciones_capturista']]
df['Diagnostico'] = df['Diagnostico'].astype("category")

## Sexo

In [12]:
replace_dict = {'Masculino':'Masculino', 'Femenino': 'Femenino', 'S-D':'S-D',
                'M':'Masculino', 'Masculino ':'Masculino', 'M.F':'S-D', 'N':'S-D',
                'Mascullino':'Masculino', 'I':'S-D', 'S-D ':'S-D', 'MAsculino':'Masculino',
                'masculino':'Masculino', '  Masculino':'Masculino'}
df['Sexo'] = df['Sexo'].replace(replace_dict).astype("category")
df['Sexo'].value_counts()

Masculino    73740
Femenino     20602
S-D           2518
Name: Sexo, dtype: int64

## Edad

In [13]:
from math import floor
def replace_edades_menor_al_año(edad):
    if type(edad)==str:
        edad_ = simplify_string(edad)
        edad_ = edad_.replace(' 1/2','.5')
        edad_ = edad_.replace('horas','hora').replace('dias','dia').replace('semanas','semana').replace('meses','mes').replace('anos','ano')
        dic_time = {'ano':1, 'mes':12, 'semana':52, 'dia':365, 'hora':8766}
        for nombre, n in dic_time.items():
            if nombre in edad_:
                edad_ = simplify_string( edad_.replace(nombre,'') )
                try: edad_ = float(edad_)
                except ValueError: return edad
                return floor( edad_ / n )
        dic_time = {'a':1, 'm':12, 'd':365}
        for nombre, n in dic_time.items():
            if nombre in edad_:
                edad_ = simplify_string( edad_.replace(nombre,'') )
                try: edad_ = float(edad_)
                except ValueError: return edad
                return floor( edad_ / n )
        try: edad_ = float(edad_)
        except(ValueError): return edad
        return floor(edad_)
    return edad

In [14]:
dic_replace = {'[1-10 días]':0, '10 SEMNS':0, '15-30 días':0, '2 mese':0, '2 o 3 meses':0, '30 - 90 días':0, '5 meses 15 días':0, 
               '6 meses UI':0, '7 - 12 meses':0, '72 hrs':0, '-12 horas':1, '1 año 3 meses':1, '1 año 4 meses':1, '1 año 7 meses':1, 
               '1 Y 8 meses':1, '15 mese':1, '18 mese':1, '3 años y medio ':3, '7 añoss':7, '[8]':8, '-72 años':72, ' S-D':'S-D', 
               '-':'S-D', '?':'S-D', 'F':'S-D', 'M':'S-D', 'S-d':'S-D', '-72 años':72, '-1':1,
               ' +3-5':4,'7-9':8,' +6-8':7,' +7-9':8,'4-6':5,'5-7':6,'6-8':7,'4 y 5':'S-D',' +4-6':5,'8 años7':8,'más 72':'S-D',
               '1 - 3':2,'1-2':1,'9-9':9,'3-4':3,'7-8':7,'2-4':3,'8 Ins.':8,'41 n':41,'R.N':0,'18-25':21,'8 172':'S-D','7 - 9':8,
               '25-30':27,' +3-4':3,' +5-6':5,' +2-3':2,' +4-7':5,' +7-8':7,' +5-7':6,' +6-7':6,'25-40':'S-D','20 o 24':22,'25/30':22
              }

df['Edad_error'] = df['Edad_error'].apply(replace_edades_menor_al_año)
df['Edad_error'] = df['Edad_error'].replace(dic_replace)
df['Edad_error'] = pd.to_numeric(df['Edad_error'], errors='coerce')
df['Edad_error'].value_counts().to_dict()

df['Edad_clean'] = df['Edad_clean'].fillna(df['Edad_error']).drop_duplicates()
df['Edad_clean'] = df['Edad_clean'].abs().mask(df['Edad_clean']>99)

## Tipo_restos

In [15]:
replace_dict = {'Cadáver':'Cadáver', 'Cadáver ':'Cadáver', 'Feto':'Feto', 'Miembros':'Miembros',
                'Recién nacido':'Recién nacido', 'Miembros  ':'Miembros', 'Restos óseos':'Restos óseos',
                'S-D':'S-D', 'Cádaver':'Cadáver', 'Miembros ':'Miembros', 'Recién nacidos':'Recién nacido',
                'Cadáver. ':'Cadáver', 'Cadáver y Feto':'S-D'}

df['Tipo_restos'] = df['Tipo_restos'].replace(replace_dict).astype("category")
df['Tipo_restos'].value_counts()

Cadáver          91258
Feto              2840
Miembros          2060
Recién nacido      635
Restos óseos        47
S-D                 20
Name: Tipo_restos, dtype: int64

In [16]:
cat_nom = ['desconocido', 'feto', 'desconocida', 'r. nacido', 'recien nacido', 'r. nacida', 'recien nacida',
           's-d', 'r nacido', 'osamenta', 'restos humanos', 'r nacida', 'placenta', 'm.i. de:',
           'restos oseos', 'miembro inferior', 'fetos', 'm. inf.', 'm. inf. izq.', 'r-nacida',
           'restos placentarios', 'mi de', 'm s de desconocido', 'nacida', ]
data = df.loc[ df['Nombre_completo'].isin(cat_nom), ['Nombre_completo','Tipo_restos']]
data.value_counts()

Nombre_completo      Tipo_restos
desconocido          Cadáver          12820
feto                 Feto              2773
desconocida          Cadáver           1293
r. nacido            Recién nacido      224
recien nacido        Recién nacido      121
r. nacida            Recién nacido       96
recien nacida        Recién nacido       83
r nacido             Recién nacido       34
osamenta             Restos óseos        29
restos humanos       Miembros            25
s-d                  Cadáver             24
                     S-D                 18
r nacida             Recién nacido       11
placenta             Miembros            10
m.i. de:             Miembros             8
restos oseos         Restos óseos         8
miembro inferior     Miembros             7
m. inf.              Miembros             6
desconocido          Feto                 6
feto                 Cadáver              6
fetos                Feto                 6
m. inf. izq.         Miembros             5
r-nacida             Recién nacido        5
m s de desconocido   Miembros             4
desconocido          Recién nacido        4
nacida               Recién nacido        4
mi de                Miembros             4
restos placentarios  Miembros             4
feto                 Recién nacido        3
desconocido          Restos óseos         3
s-d                  Miembros             3
desconocida          Recién nacido        2
placenta             Cadáver              1
desconocida          Feto                 1
restos humanos       Cadáver              1
restos placentarios  Cadáver              1
osamenta             Miembros             1
dtype: int64

## Bitacora_ingresos

In [17]:
df['Bitacora_ingresos'] = df['Bitacora_ingresos'].astype("category")

## Posible_identificado_como
## Observaciones_capturista

In [18]:
df['Observaciones_capturista'] = df['Observaciones_capturista'].replace('s-d',nan)
df['Posible_identificado_como'] = df['Posible_identificado_como'].replace('s-d',nan)
df['Posible_identificado_como'] = df['Posible_identificado_como'].apply(lambda s: 'Posible identificado como: '+s if type(s)==str else nan)
df['Observaciones'] = df[['Posible_identificado_como', 'Observaciones_capturista']].apply(lambda l: '.   '.join([s for s in l if type(s)==str]), axis=1 )
df['Observaciones'] = df['Observaciones'].replace({'':nan})
df[['Posible_identificado_como', 'Observaciones_capturista', 'Observaciones']]
df = df.drop(['Posible_identificado_como', 'Observaciones_capturista'], axis=1)
df.columns

Index(['ID', 'Numero_progresivo', 'Nombre_completo', 'Primer_apellido',
       'Segundo_apellido', 'Nombres_propios', 'Fecha', 'Fecha_clean',
       'Fecha_error', 'Expediente_Semefo', 'Procedencia', 'Procedencia_clean',
       'Procedencia_direccion', 'Procedencia_alcaldia', 'Numero_acta',
       'Acta_procedencia', 'Diagnostico', 'Diagnostico_estandar',
       'Diagnostico_extendido', 'Sexo', 'Edad', 'Edad_clean', 'Edad_error',
       'Tipo_restos', 'Bitacora_ingresos', 'Pagina_PDF', 'Pagina_PDF_clean',
       'Pagina_PDF_error', 'Foja', 'Observaciones'],
      dtype='object')

## Exportar y profile

In [20]:
df.to_csv('data_clean/SEMEFO_BO_all_revision.csv', index=False)
df.to_pickle('data_clean/SEMEFO_BO_all.pkl')

f_profile = 'profiles/SEMEFO_BO_all_revision_profile.html'
minimal_profile(df, f_profile, force_profile=True)

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]