# Bitacoras onomásticas SEMEFO 1968-1982
# Revisión de bitacoras

In [1]:
import re
import logging
import pandas as pd
from numpy import nan
from glob import glob
from os.path import exists
from ydata_profiling import ProfileReport
from helper_pandas import simplify_string, to_dtype_with_errors
from helper_pandas import join_strings_with_nans

/home/esther/anaconda3/envs/SEMEFO_busqueda/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
def check_bo(year, df):
    columns = {'ID':'categorical', 'Numero_progresivo':'int', 'Nombre_completo':'str', 'Primer_apellido':'str', 
               'Segundo_apellido':'str', 'Nombres_propios':'str', 'Fecha':'datetime', 'Expediente_Semefo':'categorical', 
               'Procedencia':'categorical', 'Numero_acta':'categorical', 'Diagnostico':'categorical', 'Sexo':'categorical', 
               'Edad':'int', 'Tipo_restos':'categorical', 'Bitacora_ingresos':'str', 'Pagina_PDF':'int', 'Foja':'str', 
               'Posible_identificado_como':'str', 'Observaciones_capturista':'str', }
    # check col names
    for col in columns.keys():
        if col not in df.columns:
            logging.warning('\t{}\t Missing col {}'.format(year,col))
    for col, type in columns.items():
        # format str columns
        if type=='str':
            df[col] = df[col].apply(simplify_string)
        # create columns with dtype
        elif type=='int':
            df = to_dtype_with_errors(df, col, dtype='numeric', downcast='integer')
        elif type=='datetime':
            df = to_dtype_with_errors(df, col, dtype='datetime')
    return df

In [3]:
def minimal_profile(df, f_profile, force_profile=False):
    if force_profile or not exists(f_profile):
        logging.info('\tProfile: {}'.format(f_profile))
        prof = df.profile_report(title=f_profile, minimal=True, correlations=None)
        prof.to_file(output_file=f_profile)

## Cargar df y convertir a tipo de datos

In [4]:
data_dir = 'data_raw/Transcritas_20230920/'
dfs = dict()

size = dict()
for file in glob(data_dir+'*'):
    # Load
    logging.warning(' Load: '+file)
    year = re.findall(r"\d+", file)[-1]
    df = pd.read_excel(file, dtype='str')
    size[file] = df.shape[0]
    logging.info('\tSize: {}'.format(df.shape))
    # Check
    df = check_bo(year, df)
    # Profile
    f_profile = file.split('/')[-1]
    f_profile = 'profiles/'+f_profile.replace('.xlsx', '_profile.html')
    minimal_profile(df, f_profile, force_profile=False)
    if size[file]!= df.shape[0]:
        logging.warning(f"Change in size of file {file}")
    # Save
    dfs[year] = df

df = pd.concat(dfs)
df = df.set_index('ID').sort_index()
df = df.dropna(how='all', axis=1)
df.to_pickle('data_raw/SEMEFO_BO_all_revision.pkl')
df

WARNING:root: Load: data_raw/Transcritas_20230920/SEMEFO_BO_1980_revision.xlsx
WARNING:root: Load: data_raw/Transcritas_20230920/SEMEFO_BO_1982_revision.xlsx
WARNING:root: Load: data_raw/Transcritas_20230920/SEMEFO_BO_1968_revision.xlsx
/home/esther/anaconda3/envs/SEMEFO_busqueda/lib/python3.11/site-packages/openpyxl/worksheet/_reader.py:312: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
WARNING:root: Load: data_raw/Transcritas_20230920/SEMEFO_BO_1971_revision.xlsx
WARNING:root: Load: data_raw/Transcritas_20230920/SEMEFO_BO_1975_revision.xlsx
WARNING:root: Load: data_raw/Transcritas_20230920/SEMEFO_BO_1978_revision.xlsx
WARNING:root: Load: data_raw/Transcritas_20230920/SEMEFO_BO_1969_revision.xlsx
WARNING:root: Load: data_raw/Transcritas_20230920/SEMEFO_BO_1972_revision.xlsx
WARNING:root: Load: data_raw/Transcritas_20230920/SEMEFO_BO_1981_revision.xlsx
WARNING:root: Load: data_raw/Transcritas_20230920/SEMEFO_BO_1977_revision.xlsx
WARNING:root: Load: data_raw/Transcritas_20230920/SEMEFO_BO_1979_revision.xlsx
WARNING:root: Load: data_raw/Transcritas_20230920/SEMEFO_BO_1976_revision.xlsx
WARNING:root: Load: data_raw/Transcritas_20230920/SEMEFO_BO_1974_revision.xlsx
WARNING:root: Load: data_raw/Transcritas_20230920/SEMEFO_BO_1970_revision.xlsx
WARNING:root: Load: data_raw/Transcritas_20230920/SEMEFO_BO_1973_revision.xlsx
/home/esther/anaconda3/envs/SEMEFO_busqueda/lib/python3.11/site-packages/openpyxl/worksheet/_reader.py:312: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

,Numero_progresivo,Numero_progresivo_clean,Nombre_completo,Primer_apellido,Segundo_apellido,Nombres_propios,Fecha,Fecha_clean,Fecha_error,Expediente_Semefo,...,Edad,Edad_clean,Edad_error,Tipo_restos,Bitacora_ingresos,Pagina_PDF,Pagina_PDF_clean,Foja,Posible_identificado_como,Observaciones_capturista
ID,,,,,,,,,,,,,,,,,,,,,
BO_1968_00001,S-D,NaN,acosta ortega teresa,acosta,ortega,teresa,1968-01-03,1968-01-03,NaN,37,...,S-D,NaN,NaN,Cadáver,semefo_df_bo_1968,2,2,1,s-d,s-d
BO_1968_00002,S-D,NaN,avila de cuestas catalina,avila,de cuestas,catalina,1968-01-05,1968-01-05,NaN,58,...,S-D,NaN,NaN,Cadáver,semefo_df_bo_1968,2,2,1,s-d,s-d
BO_1968_00003,S-D,NaN,arzate paredes juan,arzate,paredes,juan,1968-01-07,1968-01-07,NaN,83,...,S-D,NaN,NaN,Cadáver,semefo_df_bo_1968,2,2,1,s-d,s-d
BO_1968_00004,S-D,NaN,alvarez martinez isaac,alvarez,martinez,isaac,1968-01-07,1968-01-07,NaN,86,...,S-D,NaN,NaN,Cadáver,semefo_df_bo_1968,2,2,1,s-d,s-d
BO_1968_00005,S-D,NaN,arellano viuda de campos ma.,arellano,viuda de campos,ma.,1968-01-07,1968-01-07,NaN,88,...,S-D,NaN,NaN,Cadáver,semefo_df_bo_1968,2,2,1,s-d,s-d
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
BO_1982_07489,S-D,NaN,placenta,s-d,s-d,s-d,1982-06-05,1982-06-05,NaN,3079,...,S-D,NaN,NaN,Miembros,semefo_df_bo_1982,251,251,156,s-d,s-d
BO_1982_07490,S-D,NaN,5 dedos del pie derecho de desconocido,s-d,s-d,s-d,1982-06-05,1982-06-05,NaN,3060,...,S-D,NaN,NaN,Miembros,semefo_df_bo_1982,251,251,156,s-d,s-d
BO_1982_07491,S-D,NaN,dedo de desconocido,s-d,s-d,s-d,1982-11-19,1982-11-19,NaN,6389,...,S-D,NaN,NaN,Miembros,semefo_df_bo_1982,251,251,156,s-d,s-d
BO_1982_07492,S-D,NaN,4 dedos de desconocido,s-d,s-d,s-d,1982-11-28,1982-11-28,NaN,6528,...,S-D,NaN,NaN,Miembros,semefo_df_bo_1982,251,251,156,s-d,s-d
BO_1982_07493,S-D,NaN,osamenta de desconocido,s-d,s-d,s-d,1982-10-11,1982-10-11,NaN,5629,...,S-D,NaN,NaN,Cadáver,semefo_df_bo_1982,251,251,156,s-d,no se recibio necropsia. es una osamenta.

# Procesar

In [5]:
df = pd.read_pickle('data_raw/SEMEFO_BO_all_revision.pkl')
df.reset_index(inplace=True)
df

,ID,Numero_progresivo,Numero_progresivo_clean,Nombre_completo,Primer_apellido,Segundo_apellido,Nombres_propios,Fecha,Fecha_clean,Fecha_error,...,Edad,Edad_clean,Edad_error,Tipo_restos,Bitacora_ingresos,Pagina_PDF,Pagina_PDF_clean,Foja,Posible_identificado_como,Observaciones_capturista
0,BO_1968_00001,S-D,NaN,acosta ortega teresa,acosta,ortega,teresa,1968-01-03,1968-01-03,NaN,...,S-D,NaN,NaN,Cadáver,semefo_df_bo_1968,2,2,1,s-d,s-d
1,BO_1968_00002,S-D,NaN,avila de cuestas catalina,avila,de cuestas,catalina,1968-01-05,1968-01-05,NaN,...,S-D,NaN,NaN,Cadáver,semefo_df_bo_1968,2,2,1,s-d,s-d
2,BO_1968_00003,S-D,NaN,arzate paredes juan,arzate,paredes,juan,1968-01-07,1968-01-07,NaN,...,S-D,NaN,NaN,Cadáver,semefo_df_bo_1968,2,2,1,s-d,s-d
3,BO_1968_00004,S-D,NaN,alvarez martinez isaac,alvarez,martinez,isaac,1968-01-07,1968-01-07,NaN,...,S-D,NaN,NaN,Cadáver,semefo_df_bo_1968,2,2,1,s-d,s-d
4,BO_1968_00005,S-D,NaN,arellano viuda de campos ma.,arellano,viuda de campos,ma.,1968-01-07,1968-01-07,NaN,...,S-D,NaN,NaN,Cadáver,semefo_df_bo_1968,2,2,1,s-d,s-d
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96855,BO_1982_07489,S-D,NaN,placenta,s-d,s-d,s-d,1982-06-05,1982-06-05,NaN,...,S-D,NaN,NaN,Miembros,semefo_df_bo_1982,251,251,156,s-d,s-d
96856,BO_1982_07490,S-D,NaN,5 dedos del pie derecho de desconocido,s-d,s-d,s-d,1982-06-05,1982-06-05,NaN,...,S-D,NaN,NaN,Miembros,semefo_df_bo_1982,251,251,156,s-d,s-d
96857,BO_1982_07491,S-D,NaN,dedo de desconocido,s-d,s-d,s-d,1982-11-19,1982-11-19,NaN,...,S-D,NaN,NaN,Miembros,semefo_df_bo_1982,251,251,156,s-d,s-d
96858,BO_1982_07492,S-D,NaN,4 dedos de desconocido,s-d,s-d,s-d,1982-11-28,1982-11-28,NaN,...,S-D,NaN,NaN,Miembros,semefo_df_bo_1982,251,251,156,s-d,s-d
96859,BO_1982_07493,S-D,NaN,osamenta de desconocido,s-d,s-d,s-d,1982-10-11,1982-10-11,NaN,...,S-D,NaN,NaN,Cadáver,semefo_df_bo_1982,251,251,156,s-d,no se recibio necropsia. es una osamenta.

## ID

In [6]:
# Format
df.loc[(df['ID'].str.startswith('BO')!=True), ['ID', 'Nombre_completo', 'Fecha']]

Empty DataFrame
Columns: [ID, Nombre_completo, Fecha]
Index: []

In [7]:
# Format
data = pd.DataFrame([row.split('_') for row in df['ID'].to_list()], columns=['BO', 'year','ID'])
data.index = df['ID']
data['year'] = pd.to_numeric(data['year'], downcast='integer')
data['ID'] = pd.to_numeric(data['ID'], downcast='integer')
data

data.groupby('year').agg({
            'BO':'size',
            'ID':['max', pd.Series.nunique]
            })

        BO    ID
      size   max nunique
year
1968  4719  4719    4719
1969  5052  5052    5052
1970  5303  5303    5303
1971  5524  5524    5524
1972  5770  5770    5770
1973  6471  6471    6471
1974  5731  5731    5731
1975  6861  6861    6861
1976  6907  6907    6907
1977  7166  7166    7166
1978  7154  7154    7154
1979  7461  7461    7461
1980  7619  7619    7619
1981  7629  7629    7629
1982  7493  7493    7493

## Numero_progresivo

In [8]:
#df['Numero_progresivo'] = df['Numero_progresivo_clean']
df.drop('Numero_progresivo_clean', axis=1, inplace=True)

## Fecha

In [9]:
df.loc[df['Fecha_error'].notna(), ['ID', 'Fecha', 'Fecha_error', 'Observaciones_capturista']]

,ID,Fecha,Fecha_error,Observaciones_capturista
10937,BO_1970_01167,1970-04-31,1970-04-31,"en la bitacora original se anoto 31 de abril, ..."
12766,BO_1970_02996,1970-02-29,1970-02-29,"1970 no fue un ano bisiesto, sin embargo en la..."
13004,BO_1970_03234,1970-02-29,1970-02-29,"1970 no fue un ano bisiesto, sin embargo en la..."
15392,BO_1971_00319,1971-02-29,1971-02-29,"nota: (dispensa). 1971 no fue un ano bisiesto,..."
26130,BO_1972_05533,1972-02-30,1972-02-30,al parecer la bitacora ssi senala que se entre...
34846,BO_1974_02008,1974-02-29,1974-02-29,"1974 no fue un ano bisiesto, sin embargo en la..."
45886,BO_1976_00456,1976-04-31,1976-04-31,"la fecha indica un dia que no existe, se corro..."
46018,BO_1976_00588,1976-11-31,1976-11-31,"la fecha indica un dia que no existe, se corro..."
46720,BO_1976_01290,1976-06-31,1976-06-31,"la fecha indica un dia que no existe, se corro..."
47891,BO_1976_02461,1976-02-31,1976-02-31,"la fecha indica un dia que no existe, se corro..."
48121,BO_1976_02691,1976-04-31,1976-04-31,"la fecha indica un dia que no existe, se corro..."
48395,BO_1976_02965,1976-02-31,1976-02-31,dos puntos rojos en expediente_semefo. fecha y...
60738,BO_1978_01235,1978-02-30,1978-02-30,"fecha escrita como 30"" y el mes en curso era f..."
64303,BO_1978_04800,1977-12,1977-12,numero de acta escrito como 4169/77. expedient...
66995,BO_1979_00338,1979-11-31,1979-11-31,la fecha en la bitacora original es 1979-11-31...
67084,BO_1979_00427,1979-02-29,1979-02-29,la fecha en la bitacora original es 1979-02-29...
67085,BO_1979_00428,1979-02-30,1979-02-30,la fecha en la bitacora original es 1979-02-30...
67086,BO_1979_00429,1979-02-31,1979-02-31,la fecha en la bitacora original es 1979-02-31...
72704,BO_1979_06047,1979-02-29,1979-02-29,punto rojo en numero_acta. en la bitacora orig...
79499,BO_1980_05381,1980-06-31,1980-06-31,"la bitacora original dice 1980-06-31, pero se ..."
88106,BO_1981_06369,1981-02-31,1981-02-31,marca de verificacion al final del nombre; pun...
88297,BO_1981_06560,1981-04-31,1981-04-31,marca de verificacion al final del nombre. la ...
88298,BO_1981_06561,1981-04-31,1981-04-31,marca de verificacion al final del nombre. la ...
88299,BO_1981_06562,1981-04-31,1981-04-31,marca de verificacion al final del nombre. la ...
88314,BO_1981_06577,1981-04-31,1981-04-31,punto rojo en expediente_semefo. la bitacora o...

## Procedencia

In [10]:
df['Procedencia'] = df['Procedencia'].apply(simplify_string, str_case=None)
cat = pd.read_csv('catalogos/catalogo_procedencia.csv')
df = pd.merge(df, cat, on='Procedencia', how='left')
df.columns

df = df.rename(columns={'Equivalencia':'Procedencia_clean', 'Direccion':'Procedencia_direccion', 
                        'Alcaldia':'Procedencia_alcaldia'})
df = df[['ID', 'Numero_progresivo', 'Nombre_completo', 'Primer_apellido', 'Segundo_apellido', 'Nombres_propios', 
         'Fecha', 'Fecha_clean', 'Fecha_error', 'Expediente_Semefo', 'Procedencia', 'Procedencia_clean', 
         'Procedencia_direccion', 'Procedencia_alcaldia', 'Numero_acta', 'Diagnostico', 'Sexo', 'Edad', 
         'Edad_clean', 'Edad_error', 'Tipo_restos', 'Bitacora_ingresos', 'Pagina_PDF', 'Pagina_PDF_clean',
         'Foja', 'Posible_identificado_como', 'Observaciones_capturista']]

df['Procedencia_clean'] = df['Procedencia_clean'].astype("category")
df['Procedencia_alcaldia'] = df['Procedencia_alcaldia'].astype("category")
df

,ID,Numero_progresivo,Nombre_completo,Primer_apellido,Segundo_apellido,Nombres_propios,Fecha,Fecha_clean,Fecha_error,Expediente_Semefo,...,Edad,Edad_clean,Edad_error,Tipo_restos,Bitacora_ingresos,Pagina_PDF,Pagina_PDF_clean,Foja,Posible_identificado_como,Observaciones_capturista
0,BO_1968_00001,S-D,acosta ortega teresa,acosta,ortega,teresa,1968-01-03,1968-01-03,NaN,37,...,S-D,NaN,NaN,Cadáver,semefo_df_bo_1968,2,2,1,s-d,s-d
1,BO_1968_00002,S-D,avila de cuestas catalina,avila,de cuestas,catalina,1968-01-05,1968-01-05,NaN,58,...,S-D,NaN,NaN,Cadáver,semefo_df_bo_1968,2,2,1,s-d,s-d
2,BO_1968_00003,S-D,arzate paredes juan,arzate,paredes,juan,1968-01-07,1968-01-07,NaN,83,...,S-D,NaN,NaN,Cadáver,semefo_df_bo_1968,2,2,1,s-d,s-d
3,BO_1968_00004,S-D,alvarez martinez isaac,alvarez,martinez,isaac,1968-01-07,1968-01-07,NaN,86,...,S-D,NaN,NaN,Cadáver,semefo_df_bo_1968,2,2,1,s-d,s-d
4,BO_1968_00005,S-D,arellano viuda de campos ma.,arellano,viuda de campos,ma.,1968-01-07,1968-01-07,NaN,88,...,S-D,NaN,NaN,Cadáver,semefo_df_bo_1968,2,2,1,s-d,s-d
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96855,BO_1982_07489,S-D,placenta,s-d,s-d,s-d,1982-06-05,1982-06-05,NaN,3079,...,S-D,NaN,NaN,Miembros,semefo_df_bo_1982,251,251,156,s-d,s-d
96856,BO_1982_07490,S-D,5 dedos del pie derecho de desconocido,s-d,s-d,s-d,1982-06-05,1982-06-05,NaN,3060,...,S-D,NaN,NaN,Miembros,semefo_df_bo_1982,251,251,156,s-d,s-d
96857,BO_1982_07491,S-D,dedo de desconocido,s-d,s-d,s-d,1982-11-19,1982-11-19,NaN,6389,...,S-D,NaN,NaN,Miembros,semefo_df_bo_1982,251,251,156,s-d,s-d
96858,BO_1982_07492,S-D,4 dedos de desconocido,s-d,s-d,s-d,1982-11-28,1982-11-28,NaN,6528,...,S-D,NaN,NaN,Miembros,semefo_df_bo_1982,251,251,156,s-d,s-d
96859,BO_1982_07493,S-D,osamenta de desconocido,s-d,s-d,s-d,1982-10-11,1982-10-11,NaN,5629,...,S-D,NaN,NaN,Cadáver,semefo_df_bo_1982,251,251,156,s-d,no se recibio necropsia. es una osamenta.

In [11]:
procedencias = df[['Procedencia', 'Procedencia_clean', 'Procedencia_direccion', 'Procedencia_alcaldia']]
procedencias = procedencias.value_counts(dropna=False)
procedencias.to_csv('data_raw/conteo_procedencia.csv')
procedencias

Procedencia  Procedencia_clean  Procedencia_direccion                        Procedencia_alcaldia
S-D          S-D                Sin datos                                    nan                     26862
32a          32A                Ministerio Público 32                        nan                      2073
33a          33A                Ministerio Público 33 (Col Jardín Balbuena)  Venustiano Carranza      1970
37a          37A                Ministerio Público 37 (Col Polanco)          Miguel Hidalgo           1701
32           32A                Ministerio Público 32                        nan                      1562
                                                                                                     ...
C-H-6        nan                NaN                                          nan                         1
C-H-5        nan                NaN                                          nan                         1
C-H          nan                NaN                                          nan                         1
C-GAM-HV     nan                NaN                                          nan                         1
xoco         nan                NaN                                          nan                         1
Name: count, Length: 809, dtype: int64

## Numero_acta

In [12]:
data = df[['Procedencia', 'Numero_acta']].replace('S-D',nan) \
         .apply(join_strings_with_nans, sep=' : ', axis=1) \
         .fillna('S-D')
index = df.columns.get_loc('Numero_acta')
df.insert(index+1, 'Acta_procedencia', data)
df.columns

Index(['ID', 'Numero_progresivo', 'Nombre_completo', 'Primer_apellido',
       'Segundo_apellido', 'Nombres_propios', 'Fecha', 'Fecha_clean',
       'Fecha_error', 'Expediente_Semefo', 'Procedencia', 'Procedencia_clean',
       'Procedencia_direccion', 'Procedencia_alcaldia', 'Numero_acta',
       'Acta_procedencia', 'Diagnostico', 'Sexo', 'Edad', 'Edad_clean',
       'Edad_error', 'Tipo_restos', 'Bitacora_ingresos', 'Pagina_PDF',
       'Pagina_PDF_clean', 'Foja', 'Posible_identificado_como',
       'Observaciones_capturista'],
      dtype='object')

In [13]:
df['Acta_procedencia'].value_counts(dropna=False)

Acta_procedencia
S-D           25651
26a : 144        27
TP-1 : 868       13
10 : 1658        12
1a : 3737        11
              ...
HRL : 423         1
VC-2 : 862        1
CH-1 : 422        1
HCM : 79          1
9a : 4193         1
Name: count, Length: 61826, dtype: int64

## Diagnostico

In [14]:
df.shape

(96860, 28)

In [15]:
cat = pd.read_csv('catalogos/catalogo_diagnostico_simplificado.csv')
df['Diagnostico'] = df['Diagnostico'].apply(simplify_string, str_case=None)
df = df.merge(cat, on='Diagnostico', how='left')
df = df.rename({'Equivalencia':'Diagnostico_estandar','Extendido':'Diagnostico_extendido'}, axis=1)
df = df[['ID', 'Numero_progresivo', 'Nombre_completo', 'Primer_apellido', 'Segundo_apellido', 'Nombres_propios', 
         'Fecha', 'Fecha_clean', 'Fecha_error', 'Expediente_Semefo', 'Procedencia', 'Procedencia_clean',
         'Procedencia_direccion', 'Procedencia_alcaldia', 'Numero_acta', 'Acta_procedencia', 'Diagnostico', 
         'Diagnostico_estandar', 'Diagnostico_extendido', 'Sexo', 'Edad', 'Edad_clean','Edad_error', 'Tipo_restos', 
         'Bitacora_ingresos', 'Pagina_PDF', 'Pagina_PDF_clean', 'Foja', 'Posible_identificado_como', 'Observaciones_capturista']]
df['Diagnostico'] = df['Diagnostico'].astype("category")

## Sexo

In [16]:
replace_dict = {'Masculino':'Masculino', 'Femenino': 'Femenino', 'S-D':'S-D',
                'M':'Masculino', 'Masculino ':'Masculino', 'M.F':'S-D', 'N':'S-D',
                'Mascullino':'Masculino', 'I':'S-D', 'S-D ':'S-D', 'MAsculino':'Masculino',
                'masculino':'Masculino', '  Masculino':'Masculino'}
df['Sexo'] = df['Sexo'].replace(replace_dict).astype("category")
df['Sexo'].value_counts()

Sexo
Masculino    73740
Femenino     20601
S-D           2519
Name: count, dtype: int64

## Edad

In [17]:
from math import floor
def replace_edades_menor_al_año(edad):
    if type(edad)==str:
        edad_ = simplify_string(edad)
        edad_ = edad_.replace(' 1/2','.5')
        edad_ = edad_.replace('horas','hora').replace('dias','dia').replace('semanas','semana').replace('meses','mes').replace('anos','ano')
        dic_time = {'ano':1, 'mes':12, 'semana':52, 'dia':365, 'hora':8766}
        for nombre, n in dic_time.items():
            if nombre in edad_:
                edad_ = simplify_string( edad_.replace(nombre,'') )
                try: edad_ = float(edad_)
                except ValueError: return edad
                return floor( edad_ / n )
        dic_time = {'a':1, 'm':12, 'd':365}
        for nombre, n in dic_time.items():
            if nombre in edad_:
                edad_ = simplify_string( edad_.replace(nombre,'') )
                try: edad_ = float(edad_)
                except ValueError: return edad
                return floor( edad_ / n )
        try: edad_ = float(edad_)
        except(ValueError): return edad
        return floor(edad_)
    return edad

In [18]:
dic_replace = {'[1-10 días]':0, '10 SEMNS':0, '15-30 días':0, '2 mese':0, '2 o 3 meses':0, '30 - 90 días':0, '5 meses 15 días':0, 
               '6 meses UI':0, '7 - 12 meses':0, '72 hrs':0, '-12 horas':1, '1 año 3 meses':1, '1 año 4 meses':1, '1 año 7 meses':1, 
               '1 Y 8 meses':1, '15 mese':1, '18 mese':1, '3 años y medio ':3, '7 añoss':7, '[8]':8, '-72 años':72, ' S-D':'S-D', 
               '-':'S-D', '?':'S-D', 'F':'S-D', 'M':'S-D', 'S-d':'S-D', '-72 años':72, '-1':1,
               ' +3-5':4,'7-9':8,' +6-8':7,' +7-9':8,'4-6':5,'5-7':6,'6-8':7,'4 y 5':'S-D',' +4-6':5,'8 años7':8,'más 72':'S-D',
               '1 - 3':2,'1-2':1,'9-9':9,'3-4':3,'7-8':7,'2-4':3,'8 Ins.':8,'41 n':41,'R.N':0,'18-25':21,'8 172':'S-D','7 - 9':8,
               '25-30':27,' +3-4':3,' +5-6':5,' +2-3':2,' +4-7':5,' +7-8':7,' +5-7':6,' +6-7':6,'25-40':'S-D','20 o 24':22,'25/30':22
              }

df['Edad_error'] = df['Edad_error'].apply(replace_edades_menor_al_año)
df['Edad_error'] = df['Edad_error'].replace(dic_replace)
df['Edad_error'] = pd.to_numeric(df['Edad_error'], errors='coerce')
df['Edad_error'].value_counts().to_dict()

df['Edad_clean'] = df['Edad_clean'].fillna(df['Edad_error']).drop_duplicates()
df['Edad_clean'] = df['Edad_clean'].abs().mask(df['Edad_clean']>99)

## Tipo_restos

In [19]:
replace_dict = {'Cadáver':'Cadáver', 'Cadáver ':'Cadáver', 'Feto':'Feto', 'Miembros':'Miembros',
                'Recién nacido':'Recién nacido', 'Miembros  ':'Miembros', 'Restos óseos':'Restos óseos',
                'S-D':'S-D', 'Cádaver':'Cadáver', 'Miembros ':'Miembros', 'Recién nacidos':'Recién nacido',
                'Cadáver. ':'Cadáver', 'Cadáver y Feto':'S-D'}

df['Tipo_restos'] = df['Tipo_restos'].replace(replace_dict).astype("category")
df['Tipo_restos'].value_counts()

Tipo_restos
Cadáver          91254
Feto              2843
Miembros          2062
Recién nacido      633
Restos óseos        48
S-D                 20
Name: count, dtype: int64

In [20]:
cat_nom = ['desconocido', 'feto', 'desconocida', 'r. nacido', 'recien nacido', 'r. nacida', 'recien nacida',
           's-d', 'r nacido', 'osamenta', 'restos humanos', 'r nacida', 'placenta', 'm.i. de:',
           'restos oseos', 'miembro inferior', 'fetos', 'm. inf.', 'm. inf. izq.', 'r-nacida',
           'restos placentarios', 'mi de', 'm s de desconocido', 'nacida', ]
data = df.loc[ df['Nombre_completo'].isin(cat_nom), ['ID','Nombre_completo','Tipo_restos']]
data

                  ID      Nombre_completo Tipo_restos
729    BO_1968_00730          desconocido     Cadáver
730    BO_1968_00731          desconocido     Cadáver
731    BO_1968_00732          desconocida     Cadáver
732    BO_1968_00733          desconocido     Cadáver
733    BO_1968_00734          desconocido     Cadáver
...              ...                  ...         ...
96815  BO_1982_07449   m s de desconocido    Miembros
96821  BO_1982_07455   m s de desconocido    Miembros
96839  BO_1982_07473   m s de desconocido    Miembros
96853  BO_1982_07487  restos placentarios    Miembros
96855  BO_1982_07489             placenta    Miembros

[17650 rows x 3 columns]

In [21]:
cat_prob = [['restos humanos','Miembros'], ['m.i. de:','Miembros'], ['desconocido','Feto'], ['feto','Cadáver'], 
            ['feto','Recién nacido'], ['placenta','Cadáver'], ['restos humanos','Cadáver'],
            ['restos placentarios','Cadáver'], ['osamenta','Miembros']]
data = df[['ID','Nombre_completo','Tipo_restos']]

data = [data[(data['Nombre_completo']==nom) & (data['Tipo_restos']==tipo)] for nom,tipo in cat_prob ]
data = pd.concat(data)
data

                  ID Nombre_completo    Tipo_restos
8774   BO_1969_04056  restos humanos       Miembros
8931   BO_1969_04213  restos humanos       Miembros
9474   BO_1969_04756  restos humanos       Miembros
19466  BO_1971_04393  restos humanos       Miembros
19542  BO_1971_04469  restos humanos       Miembros
19576  BO_1971_04503  restos humanos       Miembros
19648  BO_1971_04575  restos humanos       Miembros
19666  BO_1971_04593  restos humanos       Miembros
19730  BO_1971_04657  restos humanos       Miembros
25103  BO_1972_04506  restos humanos       Miembros
25221  BO_1972_04624  restos humanos       Miembros
25263  BO_1972_04666  restos humanos       Miembros
25307  BO_1972_04710  restos humanos       Miembros
25331  BO_1972_04734  restos humanos       Miembros
25345  BO_1972_04748  restos humanos       Miembros
25409  BO_1972_04812  restos humanos       Miembros
31441  BO_1973_05074  restos humanos       Miembros
31542  BO_1973_05175  restos humanos       Miembros
31647  BO_1973_05280  restos humanos       Miembros
31672  BO_1973_05305  restos humanos       Miembros
31694  BO_1973_05327  restos humanos       Miembros
31789  BO_1973_05422  restos humanos       Miembros
31897  BO_1973_05530  restos humanos       Miembros
32462  BO_1973_06095  restos humanos       Miembros
81732  BO_1980_07614  restos humanos       Miembros
89155  BO_1981_07418  restos humanos       Miembros
59376  BO_1977_07039        m.i. de:       Miembros
59378  BO_1977_07041        m.i. de:       Miembros
59469  BO_1977_07132        m.i. de:       Miembros
59470  BO_1977_07133        m.i. de:       Miembros
59471  BO_1977_07134        m.i. de:       Miembros
59472  BO_1977_07135        m.i. de:       Miembros
59474  BO_1977_07137        m.i. de:       Miembros
59475  BO_1977_07138        m.i. de:       Miembros
22230  BO_1972_01633     desconocido           Feto
22523  BO_1972_01926     desconocido           Feto
22894  BO_1972_02297            feto  Recién nacido

## Bitacora_ingresos

In [22]:
df['Bitacora_ingresos'] = df['Bitacora_ingresos'].astype("category")

## Posible_identificado_como
## Observaciones_capturista

In [23]:
df['Observaciones_capturista'] = df['Observaciones_capturista'].replace('s-d',nan)
df['Posible_identificado_como'] = df['Posible_identificado_como'].replace('s-d',nan)
df['Posible_identificado_como'] = df['Posible_identificado_como'].apply(lambda s: 'Posible identificado como: '+s if type(s)==str else nan)
df['Observaciones'] = df[['Posible_identificado_como', 'Observaciones_capturista']].apply(lambda l: '.   '.join([s for s in l if type(s)==str]), axis=1 )
df['Observaciones'] = df['Observaciones'].replace({'':nan})
df[['Posible_identificado_como', 'Observaciones_capturista', 'Observaciones']]
df = df.drop(['Posible_identificado_como', 'Observaciones_capturista'], axis=1)
df.columns

Index(['ID', 'Numero_progresivo', 'Nombre_completo', 'Primer_apellido',
       'Segundo_apellido', 'Nombres_propios', 'Fecha', 'Fecha_clean',
       'Fecha_error', 'Expediente_Semefo', 'Procedencia', 'Procedencia_clean',
       'Procedencia_direccion', 'Procedencia_alcaldia', 'Numero_acta',
       'Acta_procedencia', 'Diagnostico', 'Diagnostico_estandar',
       'Diagnostico_extendido', 'Sexo', 'Edad', 'Edad_clean', 'Edad_error',
       'Tipo_restos', 'Bitacora_ingresos', 'Pagina_PDF', 'Pagina_PDF_clean',
       'Foja', 'Observaciones'],
      dtype='object')

## Desconocidos

1. S-D, desconocidos, feto, r nacido, etc en completo
2. desconocido o nan en parciales
3. solo un caracter en parciales
4. suma de casos especiales
5. miembros

In [24]:
cat_des = ['s-d', 'descono', 'feto', 'nacid', 'recien', 'osamenta', 'restos']
col_des = {s:df['Nombre_completo'].str.contains(s) for s in cat_des}
col_des = pd.concat(col_des,axis=1).any(axis=1)
df['Desconocido_ncompleto'] = col_des
col_des.value_counts()

False    78696
True     18164
Name: count, dtype: int64

In [25]:
# agrega buscar qie sea una sola letra y separa por columna
des_nom = df[['Primer_apellido', 'Segundo_apellido', 'Nombres_propios']]
des_nom = des_nom.replace({s:nan for s in ['s-d','desconocido', 'desconocida']})
des_nom = des_nom.applymap(simplify_string, str_case='lower', remove_special=True)
des_nom = des_nom.applymap(lambda s: len(s) if type(s)==str else 0)
des_nom = (des_nom > 1).sum(axis=1)
df['Desconocido_nseparado'] = des_nom
des_nom.value_counts(dropna=False)

3    73655
0    17598
2     4943
1      664
Name: count, dtype: int64

In [26]:
cat_mie = ['m. ', 'mi ', 'ms ', 'm i ', 'm s ', 'm.s.', 'm.i.', 'miembro', 'placenta']
col_mie = {s:df['Nombre_completo'].str.contains(s) for s in cat_mie}
col_mie = pd.concat(col_mie,axis=1).any(axis=1)
df['Desconocido_nmiembro'] = col_mie
col_mie.value_counts()

False    91745
True      5115
Name: count, dtype: int64

## Exportar y profile

In [27]:
df.to_csv('data_clean/SEMEFO_BO_all_revision.csv', index=False)
df.to_pickle('data_clean/SEMEFO_BO_all.pkl')

f_profile = 'profiles/SEMEFO_BO_all_revision_profile.html'
minimal_profile(df, f_profile, force_profile=True)

Summarize dataset: 100%|█████████████| 38/38 [00:04<00:00,  7.75it/s, Completed]
Generate report structure: 100%|██████████████████| 1/1 [00:17<00:00, 17.17s/it]
Render HTML: 100%|████████████████████████████████| 1/1 [00:00<00:00,  1.03it/s]
Export report to file: 100%|██████████████████████| 1/1 [00:00<00:00, 37.64it/s]

## Hipotesis

In [28]:
df.columns

Index(['ID', 'Numero_progresivo', 'Nombre_completo', 'Primer_apellido',
       'Segundo_apellido', 'Nombres_propios', 'Fecha', 'Fecha_clean',
       'Fecha_error', 'Expediente_Semefo', 'Procedencia', 'Procedencia_clean',
       'Procedencia_direccion', 'Procedencia_alcaldia', 'Numero_acta',
       'Acta_procedencia', 'Diagnostico', 'Diagnostico_estandar',
       'Diagnostico_extendido', 'Sexo', 'Edad', 'Edad_clean', 'Edad_error',
       'Tipo_restos', 'Bitacora_ingresos', 'Pagina_PDF', 'Pagina_PDF_clean',
       'Foja', 'Observaciones', 'Desconocido_ncompleto',
       'Desconocido_nseparado', 'Desconocido_nmiembro'],
      dtype='object')

In [29]:
data = df.loc[df['Expediente_Semefo']=='S-D', ['Nombre_completo', 'Fecha',  'Expediente_Semefo', 'Procedencia',  'Numero_acta']] \
         .replace('S-D',nan)
data

,Nombre_completo,Fecha,Expediente_Semefo,Procedencia,Numero_acta
613,cabrera perea evaristo,1968-08-28,NaN,NaN,NaN
662,chemor vda. de chuayffet,1968-10-31,NaN,NaN,NaN
711,chumasero bueno andres,1968-12-04,NaN,NaN,NaN
1416,figueroa de la luz sara,1968-08-13,NaN,NaN,NaN
2390,desconocido,1968-09-25,NaN,H.T.V.,74242
...,...,...,...,...,...
96410,desconocido,1982-11-18,NaN,13a,4591
96554,desconocido,NaN,NaN,NaN,NaN
96572,desconocido,NaN,NaN,NaN,NaN
96575,desconocido,1982-12-27,NaN,33a,2375
96611,feto,1982-04-14,NaN,33a,953

In [30]:
data[(data['Numero_acta'].notna()) & (data['Procedencia'].isna()) ]

,Nombre_completo,Fecha,Expediente_Semefo,Procedencia,Numero_acta
18422,m. sup. de gerardo villa,1971-01-08,NaN,NaN,73023
21504,desconocida,1972-01-11,NaN,NaN,67071
21918,desconocido,1972-06-01,NaN,NaN,71259
22474,diaz sanchez ana maria,NaN,NaN,NaN,31382
22593,feto,NaN,NaN,NaN,2
22645,feto,1972-03-30,NaN,NaN,31523
73988,msis de esteban caltzontzin,1979-06-22,NaN,NaN,1065

In [31]:
df.loc[df['Fecha_clean'].dt.year==1972, 'Expediente_Semefo']

20598       5
20599      49
20600      71
20601     101
20602     127
         ...
26365    5039
26366    5674
26367    5770
29391     S-D
30280     229
Name: Expediente_Semefo, Length: 5754, dtype: object

In [32]:
df['Expediente_Semefo'].value_counts()

Expediente_Semefo
S-D       584
108        21
2861       20
319        20
25         20
         ...
839-79      1
829-79      1
63097       1
382-79      1
92/83       1
Name: count, Length: 7795, dtype: int64

In [47]:
key_col = ['ID','Nombre_completo', 'Sexo', 'Edad_clean', 'Fecha_clean', 'Expediente_Semefo', 'Acta_procedencia', 'Diagnostico']

In [48]:
df.loc[df['Procedencia'].str.contains('SC'), key_col]

,ID,Nombre_completo,Sexo,Edad_clean,Fecha_clean,Expediente_Semefo,Acta_procedencia,Diagnostico
38887,BO_1975_00318,alatorre carlos,Masculino,NaN,NaT,S-D,SC : 4596,S-D
39665,BO_1975_01096,cardenas ismael roberto,Masculino,NaN,1975-12-08,S-D,SC : 7098,HsPSFPs
41578,BO_1975_03009,molinas de de la poza margarita,Femenino,NaN,1975-05-21,2573,SC-CH : 300,??
41996,BO_1975_03427,morales gonzalez j luis,Masculino,NaN,1975-12-18,S-D,SC : 7098-7,HsPAF
45432,BO_1976_00002,arbel d. viuda de ch. esperanza,Femenino,NaN,1976-01-03,25,SC : 0014 M-105,BN+CH
49081,BO_1976_03651,ochoa melendez jesus,Masculino,NaN,1976-08-02,4119,SC : 3322,HPAFPA
49669,BO_1976_04239,rojas zamora pablo,Masculino,NaN,1976-05-11,2539,SC : 2840,HPAFPC
52423,BO_1977_00086,alonso hernandez jose luis,Masculino,NaN,1977-03-29,1719,SC : 1903,HPAFPC
55665,BO_1977_03328,martinez magdaleno celia,Femenino,NaN,1977-09-03,4712,SC : 5430,HPAFPT
55666,BO_1977_03329,montoya ortiz cruz e.,Femenino,NaN,1977-09-03,4713,SC : 5430,HPAFPC
56817,BO_1977_04480,ramirez duarte j. manuel,Masculino,NaN,1977-09-03,4714,SC : 5430,HSPAF
65255,BO_1978_05752,desconocido ndeg1,Masculino,NaN,1978-01-10,175,SC : 97,HPAFPC
65256,BO_1978_05753,desconocido ndeg2,Masculino,NaN,1978-01-10,176,SC : 97,HsPAFP
65257,BO_1978_05754,desconocido ndeg 3,Masculino,NaN,1978-01-10,177,SC : 97,HPAFPC
65668,BO_1978_06165,desconocida,Femenino,NaN,1978-06-09,3057,SC : 3697,HsPAFPs
65669,BO_1978_06166,desconocido,Masculino,NaN,1978-06-09,3058,SC : 3697,HsPAFPs
67182,BO_1979_00525,badillo hernandez raquel [exhumacion],Femenino,NaN,1979-07-10,S-D,SC : 1550,CVG
68123,BO_1979_01466,flores millan enrique,Masculino,NaN,1979-02-04,707,SC : 727,HPAFPA
69049,BO_1979_02392,hurat araiza gilberto,Masculino,NaN,1979-06-23,3532,SC : 3726,CVG
69530,BO_1979_02873,lopez martinez maria elena,Femenino,NaN,1979-09-06,5133,SC : 6580,Dispensa
70063,BO_1979_03406,martinez perez jose luis,Masculino,NaN,1979-08-08,4435,SC : 5776,HsPAFPs
71698,BO_1979_05041,silva pina jesus,Masculino,NaN,1979-04-13,2162,SC : 2511,HPAFPTA
72078,BO_1979_05421,tovar villagordoa luis,Masculino,NaN,1979-09-06,5134,SC : 6580,Dispensa
72319,BO_1979_05662,vadillo hernandez raquel,Femenino,NaN,1979-07-10,S-D,SC : 1550,S-D
73825,BO_1979_07168,feto,Masculino,NaN,1979-10-31,6119,SC : 7987,Exp PSM
73836,BO_1979_07179,feto,S-D,NaN,1979-11-15,6447,SC : 8313,Indeterminado
73883,BO_1979_07226,recien nacido,Masculino,NaN,1979-11-19,5911,SC : 7401,Hernia Bockdebe
89750,BO_1982_00384,aguilera hernandez guillermo,Masculino,NaN,1982-12-15,6894,SC : 9373,S-D
90913,BO_1982_01547,estrada rendon manuel,Masculino,NaN,1982-01-01,7286-7018,SC : 9567,S-D

In [49]:
df.loc[df['Procedencia'].str.contains('PGR'), key_col]

,ID,Nombre_completo,Sexo,Edad_clean,Fecha_clean,Expediente_Semefo,Acta_procedencia,Diagnostico
35057,BO_1974_02219,iturralde arguelles joaquin,Masculino,NaN,1974-06-22,3020,PGR : 3032,HPAFPC
37372,BO_1974_04534,desconocido (1),Masculino,NaN,1974-02-15,791,PGR : 746,HsPPAEP
37373,BO_1974_04535,desconocido (2),Masculino,NaN,1974-02-15,792,PGR : 746,HPAFPC
37374,BO_1974_04536,desconocido (3),Masculino,NaN,1974-02-15,793,PGR : 746,HsPAFPsTA
37375,BO_1974_04537,desconocida (4),Femenino,NaN,1974-02-15,794,PGR : 746,HPAFPC
37376,BO_1974_04538,desconocida (5),Femenino,NaN,1974-02-15,795,PGR : 746,HsPAPPTyA
57086,BO_1977_04749,s. fambosky lucia,Femenino,NaN,1977-02-28,1137,PGR M-XIII,Dispensa

In [60]:
data = df.loc[df['Diagnostico_estandar'].str.contains('HPAF')==True, key_col]
index = data['Acta_procedencia'].value_counts()>2
index = index[index].index
data[data['Acta_procedencia'].isin(index)].sort_values(by='Acta_procedencia')

,ID,Nombre_completo,Sexo,Edad_clean,Fecha_clean,Expediente_Semefo,Acta_procedencia,Diagnostico
58540,BO_1977_06203,desconocido,Masculino,NaN,1977-06-25,3390,12a : 1512,HsPAFPs
58514,BO_1977_06177,desconocido,Masculino,NaN,1977-06-25,3390,12a : 1512,HsPAFPs
58506,BO_1977_06169,desconocido,Masculino,NaN,1977-06-25,3391,12a : 1512,HsPAFPsT
33721,BO_1974_00883,calixto de la cruz antonio a.,Masculino,NaN,1974-10-01,4715,15a : 1993,HsPAFPC
35851,BO_1974_03013,maldonado sanchez jose a,Masculino,NaN,1974-10-01,4716,15a : 1993,HsPAFPsCT
36381,BO_1974_03543,perales hernandez guillermo,Masculino,NaN,1974-10-02,4714,15a : 1993,HPAFPC
63752,BO_1978_04249,rodriguez de san miguel martha,Femenino,NaN,1978-03-12,1435,18a : 644,HPAFPT
59943,BO_1978_00440,bustos rodriguez jorge o.,Masculino,NaN,1978-03-12,1437,18a : 644,HPAFPC
59942,BO_1978_00439,bustos noriega jorge,Masculino,NaN,1978-03-12,1436,18a : 644,HPAFPT
70490,BO_1979_03833,ortiz de montano dolores,Masculino,NaN,1979-05-08,2008,19a : 634,HPAFPT
69842,BO_1979_03185,montano escobar luis,Masculino,NaN,1979-04-08,2016,19a : 634,HPAFPC
70488,BO_1979_03831,ortiz de montano dolores,Masculino,NaN,1979-04-08,2008,19a : 634,HPAFPT
33033,BO_1974_00195,amastal zamora luis,Masculino,NaN,1974-08-18,3930,24a : 1324,HsPAFPsC
34052,BO_1974_01214,estrada alegria marco antonio,Masculino,NaN,1974-08-19,3950,24a : 1324,HPAFPT
33797,BO_1974_00959,cortes chaves agustin,Masculino,NaN,1974-11-23,5662,24a : 1324,HsPAFPsTA
62842,BO_1978_03339,medrano correa manuel,Masculino,NaN,1978-10-01,5299,27a : 745,HPAFPA
33736,BO_1974_00898,castillo perez ivan,Masculino,NaN,1974-10-09,4856,27a : 745,HsPAFPsCT
35060,BO_1974_02222,ibanez flores jose luis,Masculino,NaN,1974-06-09,4857,27a : 745,HsPAFPsT
33735,BO_1974_00897,correa hernandez antelmo,Masculino,NaN,1974-10-09,4855,27a : 745,HSPAFPsA
53600,BO_1977_01263,dominguez lozada eligio,Masculino,NaN,1977-08-04,4089,6a : 1599,HsPAFPs
58628,BO_1977_06291,desconocido,Masculino,NaN,1977-08-04,4091,6a : 1599,HsPAFPs
53601,BO_1977_01264,dominguez lozada isidro,Masculino,NaN,1977-08-04,4090,6a : 1599,HsPAFPs
55911,BO_1977_03574,naranjo martinez diosdado,Masculino,NaN,1977-01-18,343,CH-II : 66,HsPAFPsTA
56464,BO_1977_04127,ruiz matuto leobardo,Masculino,NaN,1977-01-17,341,CH-II : 66,HsPA
52346,BO_1977_00009,alvarado munoz leticia,Femenino,NaN,1977-01-17,330,CH-II : 66,HPAFPT
52754,BO_1977_00417,barajas fernandez rosario,Femenino,NaN,1977-01-17,342,CH-II : 66,HsPAFPsTA
37375,BO_1974_04537,desconocida (4),Femenino,NaN,1974-02-15,794,PGR : 746,HPAFPC
37373,BO_1974_04535,desconocido (2),Masculino,NaN,1974-02-15,792,PGR : 746,HPAFPC
37374,BO_1974_04536,desconocido (3),Masculino,NaN,1974-02-15,793,PGR : 746,HsPAFPsTA
55666,BO_1977_03329,montoya ortiz cruz e.,Femenino,NaN,1977-09-03,4713,SC : 5430,HPAFPC
55665,BO_1977_03328,martinez magdaleno celia,Femenino,NaN,1977-09-03,4712,SC : 5430,HPAFPT
56817,BO_1977_04480,ramirez duarte j. manuel,Masculino,NaN,1977-09-03,4714,SC : 5430,HSPAF
65256,BO_1978_05753,desconocido ndeg2,Masculino,NaN,1978-01-10,176,SC : 97,HsPAFP
65257,BO_1978_05754,desconocido ndeg 3,Masculino,NaN,1978-01-10,177,SC : 97,HPAFPC
65255,BO_1978_05752,desconocido ndeg1,Masculino,NaN,1978-01-10,175,SC : 97,HPAFPC
42795,BO_1975_04226,romero de la rosa mordorio,Masculino,NaN,1975-04-26,2141,TP-1 : 222,HsPAFPsC
42791,BO_1975_04222,rabodan salgado hipolito,Masculino,NaN,1975-04-26,2140,TP-1 : 222,HsPAFPs
42171,BO_1975_03602,ortiz pineda jesus,Masculino,NaN,1975-04-26,2134,TP-1 : 222,HPAF
40300,BO_1975_01731,garza arrieta enrique,Masculino,NaN,1975-04-26,2136,TP-1 : 222,HsPAFPsTA
39883,BO_1975_01314,espinoza olascoaga miguel,Masculino,NaN,1975-04-26,2138,TP-1 : 222,HsPAFPsC
39324,BO_1975_00755,camahco cruz m francisco,Masculino,NaN,1975-04-26,2135,TP-1 : 222,HsPAFPs
39007,BO_1975_00438,barcenas orduna alberto,Masculino,NaN,1975-04-26,2137,TP-1 : 222,HsPAFPs
41229,BO_1975_02660,lara guerrero cipriano,Masculino,NaN,1975-08-13,4122,VC-1 : 1620,HsPAFPsTA
39461,BO_1975_00892,camparan arias anacleto,Masculino,NaN,1975-08-12,4119,VC-1 : 1620,HsPAFPs
39452,BO_1975_00883,cano cortes luis,Masculino,NaN,1975-08-12,4120,VC-1 : 1620,HPAFPC
38777,BO_1975_00208,alonso varas sergio,Masculino,NaN,1975-08-13,4135,VC-1 : 1620,HsPA
42990,BO_1975_04421,rojaro miranda mario,Masculino,NaN,1975-09-13,4719,VC-2 : 2014,HPAFPC
41257,BO_1975_02688,lopez rincon lessia,Femenino,NaN,1975-09-14,4735,VC-2 : 2014,HPAFPT
38803,BO_1975_00234,aguirre tapia gonzalo,Masculino,NaN,1975-09-13,4718,VC-2 : 2014,HsPAFPsTA

In [95]:
data = df.loc[df['Diagnostico_estandar'].str.contains('HPAF')==True, key_col]
data.groupby('Fecha_clean').filter(lambda g: len(g)>3).sort_values(by=['Fecha_clean','Acta_procedencia'])

,ID,Nombre_completo,Sexo,Edad_clean,Fecha_clean,Expediente_Semefo,Acta_procedencia,Diagnostico
35497,BO_1974_02659,mendoza pena antonio,Masculino,NaN,1974-02-15,780,23a : 81,HPAFPC
37373,BO_1974_04535,desconocido (2),Masculino,NaN,1974-02-15,792,PGR : 746,HPAFPC
37374,BO_1974_04536,desconocido (3),Masculino,NaN,1974-02-15,793,PGR : 746,HsPAFPsTA
37375,BO_1974_04537,desconocida (4),Femenino,NaN,1974-02-15,794,PGR : 746,HPAFPC
33909,BO_1974_01071,devesa sanabre angel,Masculino,NaN,1974-03-04,2147,13a : 2436,HPAFPC
...,...,...,...,...,...,...,...,...
70453,BO_1979_03796,nunez barrionuevo julio c.,Masculino,NaN,1979-12-25,7380,33a : 2602,HPAFP
67052,BO_1979_00395,ayala hernandez jose luis,Masculino,NaN,1979-12-26,7381,11a : 3393,HPAFPC
69611,BO_1979_02954,luna bonilla jose e,Masculino,NaN,1979-12-26,7376,13a : 2295,HPAFPT
71557,BO_1979_04900,ramirez oseguera carlos,Masculino,NaN,1979-12-26,7365,20a : 3693,HPAFPT
70589,BO_1979_03932,ortega gonzalez esteban,Masculino,NaN,1979-12-26,7401,37a : 1045,HPAFP

In [68]:
from datetime import datetime

date_min = datetime(1968, 10, 2)
data_max = datetime(1968, 10, 16)

df.loc[df['Fecha_clean'].between(date_min, data_max, inclusive='both'), key_col].sort_values(by='Fecha_clean')

In [78]:
import datetime

date_min = datetime.datetime(1975, 4, 25)
date_max = date_min + datetime.timedelta(days=7)

df.loc[df['Fecha_clean'].between(date_min, date_max, inclusive='both'), key_col].sort_values(by=['Fecha_clean','Acta_procedencia'])

,ID,Nombre_completo,Sexo,Edad_clean,Fecha_clean,Expediente_Semefo,Acta_procedencia,Diagnostico
42167,BO_1975_03598,orozco saenzs francisco,Masculino,NaN,1975-04-25,2129,AO-1 : 626,TM
44371,BO_1975_05802,desconocido,Masculino,NaN,1975-04-25,2117,AZ-1 : 78,TM
44372,BO_1975_05803,desconocido,Masculino,NaN,1975-04-25,2118,AZ-1 : 783,TM
44373,BO_1975_05804,desconocido,Masculino,NaN,1975-04-25,2119,AZ-1 : 783,TM
45312,BO_1975_06743,m inf de martin cruz,Masculino,NaN,1975-04-25,2127,BJ-CM : 797,AQxAgenos
...,...,...,...,...,...,...,...,...
42374,BO_1975_03805,paredes tapia ma guadalupe,Femenino,NaN,1975-05-02,2537,MH-HRL : 192,QuemEP
43337,BO_1975_04768,samano arriaga camilo,Masculino,NaN,1975-05-02,2546,MH-HRL : 438,HPAFPA
43803,BO_1975_05234,valladolid romero lidia,Femenino,NaN,1975-05-02,2251,TP-1 : 231,TCE
40291,BO_1975_01722,garcia montoya margarita,Femenino,NaN,1975-05-02,2268,VC-HB : 421,TCE
41545,BO_1975_02976,montes gordiano jose vidal,Masculino,NaN,1975-05-02,2264,VC-HB : 720,TCE