# Historico de Bitácoras Onomásticas del SEMEFO-DF
# Análisis de datos

Las [Historico de Bitácoras Onomásticas del Servicio Médico Forense del Distrito Federal (SEMEFO-DF)](https://datamx.io/dataset/ingresos-del-semefo-df-1965-1982-inai), han sido sistematizada por la Comisión Nacional de Búsqueda (CNB). Este conjunto de datos se obtuvo a través de una solicitud de acceso a la información disponible en el Portal de Transparencia del Instituto Nacional de acceso a la Información (INAI) en noviembre de 2023 y existe una copia en el portal ciudadano _datamx_ de Codeando México.

El **SEMEFO-DF (Servicio Médico Forense Distrito Federal)** ahora [INCIFO-CdMx](https://www.incifocdmx.gob.mx/) es una institución oficial encargada de realizar autopsias y estudios forenses para esclarecer las causas de muerte, principalmente en casos de muertes violentas, sospechosas o relacionadas con hechos delictivos. Las **Bitácoras Onomásticas (BO)** son registros administrativos históricos utilizados por el SEMEFO para documentar el ingreso de cadáveres o restos humanos a sus instalaciones. Estas bitácoras contienen información detallada sobre cada ingreso, como el nombre de la persona fallecida, su edad, sexo, fecha de ingreso, institución de procedencia y diagnóstico preliminar de causa de muerte. En muchos casos, estos registros incluyen datos clave para identificar patrones históricos de mortalidad, enfermedades comunes y factores de riesgo, lo que las convierte en una fuente valiosa para estudios demográficos, epidemiológicos y de salud pública.

Podemos acceder a esta información con la [Plataforma de Transparencia](https://www.plataformadetransparencia.org.mx/Inicio), [datamx](https://datamx.io/dataset/ingresos-del-semefo-df-1965-1982-inai).

In [1]:
from numpy import nan
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from joblib import load

in_file = "data_clean/HBO_clean.pkl"
with open(in_file, 'rb') as f:
     df = load(f)
        
df.tail()

,Numero_progresivo_transcrito,Nombre_completo_transcrito,Primer_apellido,Segundo_apellido,Nombres_propios,Fecha_transcrito,Fecha_estandar,Fecha_año,Fecha_mes,Fecha_diasemana,...,Diagnostico_clasificacion,Procedencia_transcrito,Procedencia_estandar,Procedencia_extendido,Procedencia_alcaldia,Numero_acta_transcrito,Expediente_SEMEFO_transcrito,Bitacora_ingresos,Foja_transcrito,Observaciones
ID,,,,,,,,,,,,,,,,,,,,,
BO_1982_07489,S-D,placenta,NaN,NaN,NaN,1982-06-05,1982-06-05,1982.0,6.0,Sábado,...,NaN,15a,GAM-2,Coord Territorial 2 Gustavo A Madero (Col Arag...,Gustavo A Madero,960,3079,semefo_df_bo_1982,156,NaN
BO_1982_07490,S-D,5 dedos del pie derecho de desconocido,NaN,NaN,NaN,1982-06-05,1982-06-05,1982.0,6.0,Sábado,...,NaN,32a,COY-2,Coord Territorial 2 Coyoacan (Col Romero de Te...,Coyoacan,950,3060,semefo_df_bo_1982,156,NaN
BO_1982_07491,S-D,dedo de desconocido,NaN,NaN,NaN,1982-11-19,1982-11-19,1982.0,11.0,Viernes,...,NaN,32a,COY-2,Coord Territorial 2 Coyoacan (Col Romero de Te...,Coyoacan,2005,6389,semefo_df_bo_1982,156,NaN
BO_1982_07492,S-D,4 dedos de desconocido,NaN,NaN,NaN,1982-11-28,1982-11-28,1982.0,11.0,Domingo,...,NaN,27a,XO-2,Coord Territorial 2 Xochimilco (Barrio de San ...,Xochimilco,959,6528,semefo_df_bo_1982,156,NaN
BO_1982_07493,S-D,osamenta de desconocido,NaN,NaN,NaN,1982-10-11,1982-10-11,1982.0,10.0,Lunes,...,NaN,9a,MH-1,Coord Territorial 1 Miguel Hidalgo – Hospital ...,Miguel Hidalgo,4193,5629,semefo_df_bo_1982,156,no se recibio necropsia. es una osamenta.

In [2]:
col_trans = [c for c in df.columns if 'transcrito' in c]

## Datos faltantes

Datos faltantes por columna

In [3]:
df_nan = (df[col_trans]=='S-D')
df_nan.sum()

Numero_progresivo_transcrito    69673
Nombre_completo_transcrito         24
Fecha_transcrito                  233
Edad_transcrito                 56661
Diagnostico_transcrito          55878
Procedencia_transcrito          25780
Numero_acta_transcrito          25742
Expediente_SEMEFO_transcrito      567
Foja_transcrito                  7980
dtype: int64

Filas con más datos faltantes

In [5]:
df_nan.sum(axis=1).value_counts().sort_index() /df.shape[0]

/home/esther/anaconda3/envs/SEMEFO_busqueda/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  """Entry point for launching an IPython kernel.

0    0.272603
1    0.145017
2    0.006433
3    0.229049
4    0.081595
5    0.259717
6    0.004740
7    0.000785
8    0.000062
dtype: float64

In [6]:
df_nan.sum(axis=1)

/home/esther/anaconda3/envs/SEMEFO_busqueda/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  """Entry point for launching an IPython kernel.

ID
BO_1968_00001    5
BO_1968_00002    5
BO_1968_00003    5
BO_1968_00004    5
BO_1968_00005    5
                ..
BO_1982_07489    3
BO_1982_07490    3
BO_1982_07491    3
BO_1982_07492    3
BO_1982_07493    3
Length: 96844, dtype: int64

In [7]:
df.loc[df_nan.sum(axis=1)>=7, col_trans]

/home/esther/anaconda3/envs/SEMEFO_busqueda/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  """Entry point for launching an IPython kernel.

,Numero_progresivo_transcrito,Nombre_completo_transcrito,Fecha_transcrito,Edad_transcrito,Diagnostico_transcrito,Procedencia_transcrito,Numero_acta_transcrito,Expediente_SEMEFO_transcrito,Foja_transcrito
ID,,,,,,,,,
BO_1969_00877,S-D,desc. hija de ignacio colin perez,S-D,S-D,S-D,S-D,S-D,S-D,19
BO_1969_03374,S-D,nombre confidencial,S-D,S-D,S-D,S-D,S-D,S-D,77
BO_1969_03814,S-D,perez viuda de solis maria,S-D,S-D,S-D,S-D,S-D,S-D,90
BO_1969_04012,S-D,r. nacido,S-D,S-D,S-D,S-D,S-D,S-D,100
BO_1970_00291,S-D,bautista,S-D,S-D,S-D,S-D,S-D,S-D,9 reverso
...,...,...,...,...,...,...,...,...,...
BO_1982_03556,S-D,martinez martinez,S-D,S-D,S-D,S-D,S-D,S-D,72 reverso
BO_1982_05061,S-D,sanjuan villalpando guadalupe,S-D,S-D,S-D,S-D,S-D,S-D,104
BO_1982_05762,S-D,vazquez,S-D,S-D,S-D,S-D,S-D,S-D,118
BO_1982_07188,S-D,desconocido,S-D,S-D,S-D,S-D,S-D,S-D,144
BO_1982_07206,S-D,desconocido,S-D,S-D,S-D,S-D,S-D,S-D,144

Datos faltantes por año

## Tipo_restos
## Conocido_desconocido

## Sexo y Edad

## Fecha

## Nombre

## Diagnostico

## Procedencia

## Expediente_SEMEFO
## Numero_acta

## Bitacora_ingresos
## Foja
## Observaciones