# Confronta de base de datos

In [1]:
import pandas as pd

thr_diff = 3

df = pd.read_pickle('data_clean/SEMEFO_BO_all.pkl')
df.head()

,ID,Numero_progresivo_transcrito,Nombre_completo_transcrito,Primer_apellido,Segundo_apellido,Nombres_propios,Fecha_transcrito,Fecha_estandar,Fecha_añomes,Fecha_diasemana,...,Procedencia_acta,Diagnostico_transcrito,Diagnostico_estandar,Diagnostico_extendido,Tipo_restos,Conocido_desconocido,Bitacora_ingresos,Pagina_PDF,Foja_transcrito,Observaciones
0,BO_1968_00001,NaN,acosta ortega teresa,acosta,ortega,teresa,1968-01-03,1968-01-03,1968 Enero,Miércoles,...,NaN,S-D,S-D,S-D,Cadáver,conocido,semefo_df_bo_1968,2,1,NaN
1,BO_1968_00002,NaN,avila de cuestas catalina,avila,de cuestas,catalina,1968-01-05,1968-01-05,1968 Enero,Viernes,...,NaN,S-D,S-D,S-D,Cadáver,conocido,semefo_df_bo_1968,2,1,NaN
2,BO_1968_00003,NaN,arzate paredes juan,arzate,paredes,juan,1968-01-07,1968-01-07,1968 Enero,Domingo,...,NaN,S-D,S-D,S-D,Cadáver,conocido,semefo_df_bo_1968,2,1,NaN
3,BO_1968_00004,NaN,alvarez martinez isaac,alvarez,martinez,isaac,1968-01-07,1968-01-07,1968 Enero,Domingo,...,NaN,S-D,S-D,S-D,Cadáver,conocido,semefo_df_bo_1968,2,1,NaN
4,BO_1968_00005,NaN,arellano viuda de campos ma.,arellano,viuda de campos,ma.,1968-01-07,1968-01-07,1968 Enero,Domingo,...,NaN,S-D,S-D,S-D,Cadáver,conocido,semefo_df_bo_1968,2,1,NaN

In [20]:
df['Procedencia_estandar'].nunique()

110

In [18]:
df.loc[df['Diagnostico_estandar'].str.contains('HPAF').fillna(False),['Diagnostico_transcrito','Diagnostico_estandar']].drop_duplicates()

      Diagnostico_transcrito Diagnostico_estandar
32858                 HPAFPT               HPAFPT
32873                 HPAFPC               HPAFPC
32890                 HPAFPA               HPAFPA
32894                   HPAF                 HPAF
32932                 HPAFPV               HPAFPV
32974                 HPPAFP                 HPAF
32977                HPPAFPC               HPAFPC
33017                  HPAFP                 HPAF
33031               HsPAFPsC               HPAFPC
33095               HsPAFPsT               HPAFPT
33141                HPAFPTA              HPAFPTA
33352                 HPAFPE                 HPAF
33572                HsPAFPs                 HPAF
33719                HsPAFPC               HPAFPC
33733               HSPAFPsA               HPAFPA
33734              HsPAFPsCT              HPAFPCT
33739              HsPAFPsTA              HPAFPTA
33800                 HPAFPR                 HPAF
33863               HPAFPTyA              HPAFPTA
34557                 HPAFPI                 HPAF
35370                HPAFPTV              HPAFPTV
35524                HsPAFPT               HPAFPT
35626                 hpafpt               HPAFPT
35721                 HPAEPC               HPAFPC
36707                HPPAFPT               HPAFPT
38664            HPAFPCuello              HPAFPCU
38775                   HsPA                 HPAF
38805               HsPAFPsA               HPAFPA
38820                  HsPAF                 HPAF
40017                  HPAFC               HPAFPC
42317                 HsPAFP                 HPAF
45459                 HPAFPc               HPAFPC
46622                   HPAP                 HPAF
46894                    HPA                 HPAF
51926                HsPAFps                 HPAF
53766               HsPSAFPs                 HPAF
55791                  HspAF                 HPAF
56023                  HSPAF                 HPAF
56055                 HsPaFP                 HPAF
56194                   HSPA                 HPAF
56198                  HsPAf                 HPAF
57581               HsPsAFPs                 HPAF
66784               HPPAFPTA              HPAFPTA
69393                HsPAFPS                 HPAF

## Ingenieria de grupos de ingreso por acta y fecha

In [2]:
grupos_interes = df['Procedencia_acta'].value_counts()
grupos_interes = grupos_interes[grupos_interes>1].index
grupos_interes

df['Grupo_ingreso'] = None
thr_diff=3

for id_grupo in grupos_interes:
    data = df.loc[df['Procedencia_acta']==id_grupo,['ID','Fecha_estandar']]
    data = data.sort_values(by='Fecha_estandar')
    
    ids = []
    nom_grupo=None
    for d in data.rolling(window=2):
        if len(d)>1:
            diff = (d.iloc[1,1]-d.iloc[0,1]).days
            if diff<=thr_diff:
                if nom_grupo==None: 
                    nom_grupo = id_grupo +' '+ d.iloc[0,1].strftime('%Y-%m-%d')
                ids += d['ID'].to_list()
    ids = list(set(ids))
    df.loc[df['ID'].isin(ids),'Grupo_ingreso']= nom_grupo

In [3]:
data = df.loc[df['Procedencia_acta'].isin(grupos_interes),['ID', 'Fecha_estandar', 'Procedencia_acta', 'Grupo_ingreso']] \
          .sort_values(by=['Procedencia_acta','Fecha_estandar']) #.dropna(subset='Grupo_ingreso') \
data.iloc[50:100]

                  ID Fecha_estandar Procedencia_acta        Grupo_ingreso
33823  BO_1974_00987     1974-11-28         10A/1483                 None
54195  BO_1977_01860     1977-06-06         10A/1483                 None
52516  BO_1977_00181     1977-06-17         10A/1483                 None
33142  BO_1974_00306     1974-12-09         10A/1489                 None
92702  BO_1982_03352     1982-05-12         10A/1489                 None
56691  BO_1977_04356     1977-05-07         10A/1498                 None
56673  BO_1977_04338     1977-06-07         10A/1498                 None
55518  BO_1977_03183     1977-06-16         10A/1570                 None
83766  BO_1981_02045     1981-05-25         10A/1570                 None
69199  BO_1979_02558     1979-10-01         10A/1593                 None
90191  BO_1982_00841     1982-05-19         10A/1593                 None
54249  BO_1977_01914     1977-06-28         10A/1648                 None
80790  BO_1980_06688     1980-06-08         10A/1648                 None
75659  BO_1980_01557     1980-05-06         10A/1658                 None
75025  BO_1980_00923     1980-06-06         10A/1658  10A/1658 1980-06-06
77150  BO_1980_03048     1980-06-06         10A/1658  10A/1658 1980-06-06
77151  BO_1980_03049     1980-06-06         10A/1658  10A/1658 1980-06-06
77668  BO_1980_03566     1980-06-06         10A/1658  10A/1658 1980-06-06
77669  BO_1980_03567     1980-06-06         10A/1658  10A/1658 1980-06-06
77670  BO_1980_03568     1980-06-06         10A/1658  10A/1658 1980-06-06
78251  BO_1980_04149     1980-06-06         10A/1658  10A/1658 1980-06-06
78466  BO_1980_04364     1980-06-06         10A/1658  10A/1658 1980-06-06
78973  BO_1980_04871     1980-06-06         10A/1658  10A/1658 1980-06-06
80065  BO_1980_05963     1980-06-06         10A/1658  10A/1658 1980-06-06
80288  BO_1980_06186     1980-06-06         10A/1658  10A/1658 1980-06-06
74548  BO_1980_00446     1980-01-28          10A/166                 None
88030  BO_1981_06309     1981-01-20          10A/166                 None
57213  BO_1977_04878     1977-06-30         10A/1709                 None
85200  BO_1981_03479     1981-06-07         10A/1709                 None
55564  BO_1977_03229     1977-07-06         10A/1762                 None
83781  BO_1981_02060     1981-06-12         10A/1762                 None
80817  BO_1980_06715     1980-06-15         10A/1774                 None
91812  BO_1982_02462     1982-06-03         10A/1774                 None
55612  BO_1977_03277     1977-08-01         10A/1996                 None
76715  BO_1980_02613     1980-07-06         10A/1996                 None
89770  BO_1982_00420     1982-01-08          10A/200                 None
89768  BO_1982_00418     1982-01-18          10A/200                 None
53597  BO_1977_01262     1977-08-02         10A/2006  10A/2006 1977-08-02
59186  BO_1977_06851     1977-08-02         10A/2006  10A/2006 1977-08-02
58614  BO_1977_06279     1977-08-03         10A/2006  10A/2006 1977-08-02
78498  BO_1980_04396     1980-07-08         10A/2006                 None
88478  BO_1981_06757     1981-07-01         10A/2006                 None
73294  BO_1979_06653     1979-09-04         10A/2148                 None
80933  BO_1980_06831     1980-07-23         10A/2148                 None
34108  BO_1974_01272     1974-02-28          10A/237                 None
33853  BO_1974_01017     1974-12-30          10A/237                 None
66677  BO_1979_00036     1979-02-01          10A/237                 None
89562  BO_1982_00212     1982-07-29         10A/2431  10A/2431 1982-07-29
89870  BO_1982_00520     1982-07-29         10A/2431  10A/2431 1982-07-29
92310  BO_1982_02960     1982-07-29         10A/2431  10A/2431 1982-07-29

## Ingenieria por enfrentamientos

In [5]:
from datetime import timedelta

fechas = pd.read_csv('data_raw/Enfrentamientos_CDMX - 20230214_Datos.csv')
fechas = pd.to_datetime( fechas['Fecha'] ).dropna().sort_values().unique()
fechas

dic_fechas = {}
f_range = list(range(-1*thr_diff, thr_diff+1))
for f in fechas:
    f_str = 'Enfrentamiento ' +f.strftime('%Y-%m-%d')
    dic_fechas.update( {f+timedelta(days=i):f_str for i in f_range} )
dic_fechas

df['Enfrentamientos_fecha'] = df['Fecha_estandar'].map(dic_fechas)
df['Enfrentamientos_fecha'].value_counts()

Enfrentamientos_fecha
Enfrentamiento 1977-12-17    202
Enfrentamiento 1981-01-22    173
Enfrentamiento 1977-01-19    167
Enfrentamiento 1979-10-13    166
Enfrentamiento 1977-01-26    161
Enfrentamiento 1978-09-15    154
Enfrentamiento 1978-08-18    148
Enfrentamiento 1977-05-18    148
Enfrentamiento 1975-12-13    147
Enfrentamiento 1979-10-04    146
Enfrentamiento 1978-01-05    145
Enfrentamiento 1974-12-10    143
Enfrentamiento 1980-04-23    141
Enfrentamiento 1977-04-14    137
Enfrentamiento 1973-12-19    136
Enfrentamiento 1979-08-29    134
Enfrentamiento 1976-08-28    134
Enfrentamiento 1977-09-03    131
Enfrentamiento 1973-12-01    131
Enfrentamiento 1975-04-25    130
Enfrentamiento 1975-08-22    127
Enfrentamiento 1976-06-09    126
Enfrentamiento 1976-08-11    124
Enfrentamiento 1979-09-07    123
Enfrentamiento 1968-10-02    120
Enfrentamiento 1979-03-30    119
Enfrentamiento 1977-06-24    117
Enfrentamiento 1974-10-11    117
Enfrentamiento 1976-06-19    116
Enfrentamiento 1974-02-04    114
Enfrentamiento 1974-06-19    113
Enfrentamiento 1976-07-07    112
Enfrentamiento 1975-06-20    110
Enfrentamiento 1976-07-01    108
Enfrentamiento 1975-06-02    108
Enfrentamiento 1975-06-15    105
Enfrentamiento 1977-07-06     99
Enfrentamiento 1974-07-01     78
Enfrentamiento 1975-08-20     46
Enfrentamiento 1975-04-24     28
Enfrentamiento 1978-01-04     22
Name: count, dtype: int64

## Guardar

In [6]:
df.to_csv('data_clean/SEMEFO_BO_all_extendido.csv', index=False)
df.to_pickle('data_clean/SEMEFO_BO_all_extendido.pkl')

In [18]:
df.columns

Index(['ID', 'Numero_progresivo_transcrito', 'Nombre_completo_transcrito',
       'Primer_apellido', 'Segundo_apellido', 'Nombres_propios',
       'Fecha_transcrito', 'Fecha_estandar', 'Fecha_añomes', 'Fecha_diasemana',
       'Sexo', 'Edad_transcrito', 'Edad_estandar', 'Edad_rango',
       'Expediente_SEMEFO_transcrito', 'Procedencia_transcrito',
       'Procedencia_estandar', 'Procedencia_direccion', 'Procedencia_alcaldia',
       'Numero_acta_transcrito', 'Procedencia_acta', 'Diagnostico_transcrito',
       'Diagnostico_estandar', 'Diagnostico_extendido', 'Tipo_restos',
       'Conocido_desconocido', 'Bitacora_ingresos', 'Pagina_PDF',
       'Foja_transcrito', 'Observaciones', 'Grupo_ingreso',
       'Enfrentamientos_fecha'],
      dtype='object')

In [20]:
df.loc[(df['Diagnostico_estandar'].str.contains('HPAF')) & (df['Enfrentamientos_fecha'].notna()) & (df['Grupo_ingreso'].notna()),
       ['ID', 'Nombre_completo_transcrito', 'Fecha_transcrito', 'Edad_transcrito', 'Procedencia_acta', 'Diagnostico_transcrito']]

,ID,Nombre_completo_transcrito,Fecha_transcrito,Edad_transcrito,Procedencia_acta,Diagnostico_transcrito
33733,BO_1974_00897,correa hernandez antelmo,1974-10-09,70,27A/745,HSPAFPsA
33734,BO_1974_00898,castillo perez ivan,1974-10-09,35,27A/745,HsPAFPsCT
39005,BO_1975_00438,barcenas orduna alberto,1975-04-26,45,TP-1/222,HsPAFPs
39322,BO_1975_00755,camahco cruz m francisco,1975-04-26,28,TP-1/222,HsPAFPs
39461,BO_1975_00894,calderon salgado raul,1975-08-19,20,AO-1/1304,HsPAFPsT
39881,BO_1975_01314,espinoza olascoaga miguel,1975-04-26,30,TP-1/222,HsPAFPsC
40269,BO_1975_01702,gonzalez miranda sabino,1975-04-21,26,C-1/640,HsPAFPsT
40270,BO_1975_01703,gonzalez miranda eugenio,1975-04-21,24,C-1/640,HPAFPC
40298,BO_1975_01731,garza arrieta enrique,1975-04-26,55,TP-1/222,HsPAFPsTA
40462,BO_1975_01895,garcia raul,1975-08-18,25,MH-CR/885,HPAFPT
41236,BO_1975_02669,lira ruiz fco javier,1975-08-23,26,AO-1/1318,HsPAFPs
42169,BO_1975_03602,ortiz pineda jesus,1975-04-26,25,TP-1/222,HPAF
42789,BO_1975_04222,rabodan salgado hipolito,1975-04-26,38,TP-1/222,HsPAFPs
42793,BO_1975_04226,romero de la rosa mordorio,1975-04-26,32,TP-1/222,HsPAFPsC
43417,BO_1975_04850,sanchez islas porfirio,1975-08-19,30,AO-1/1304,HsPAFPsC
44048,BO_1975_05481,zarate garcia raul,1975-08-17,25,MH-CR/885,HPAFPCuello
47277,BO_1976_01849,grijalva de villamuel maria angeles,1976-07-10,26,AZ-1/1629,HsPAFPsT
50687,BO_1976_05259,villarruel marquez javier,1976-07-10,35,AZ-1/1629,HPAFP
51533,BO_1976_06105,desconocido,1976-08-11,28,BJ-1/2246,HPAFPC
52344,BO_1977_00009,alvarado munoz leticia,1977-01-17,21,CH-2/66,HPAFPT
52752,BO_1977_00417,barajas fernandez rosario,1977-01-17,59,CH-2/66,HsPAFPsTA
53468,BO_1977_01133,cabello luna felix,1977-12-19,31,22A/4883,HPAFPC
55095,BO_1977_02760,ledezma cruz olivia,1977-07-07,23,18A/1582,HPAF
55223,BO_1977_02888,lopez aguado m. antonio,1977-12-17,65,12A/3045,HPA
55278,BO_1977_02943,montiel castelan procaro,1977-01-20,30,GAM-1/171,HsPA
55288,BO_1977_02953,minero lezama j. luis,1977-01-22,19,VC-2/191,HPAF
55290,BO_1977_02955,moncada alvarez eusebio,1977-01-23,55,VC-2/191,HsPA
55663,BO_1977_03328,martinez magdaleno celia,1977-09-03,19,SC/5430,HPAFPT
55664,BO_1977_03329,montoya ortiz cruz e.,1977-09-03,20,SC/5430,HPAFPC
55909,BO_1977_03574,naranjo martinez diosdado,1977-01-18,35,CH-2/66,HsPAFPsTA
56462,BO_1977_04127,ruiz matuto leobardo,1977-01-17,25,CH-2/66,HsPA
56815,BO_1977_04480,ramirez duarte j. manuel,1977-09-03,27,SC/5430,HSPAF
57654,BO_1977_05319,vazquez reyes mayolo,1977-01-20,34,GAM-1/171,HsPAFPsTA
58504,BO_1977_06169,desconocido,1977-06-25,29,12A/1512,HsPAFPsT
58512,BO_1977_06177,desconocido,1977-06-25,29,12A/1512,HsPAFPs
58533,BO_1977_06198,desconocido liga 23 de sep.,1977-07-07,25,18A/1582,HPAFPC
58534,BO_1977_06199,desconocida liga 23 de sep.ledezma cruz olivia,1977-07-07,25,18A/1582,HPAFPC
58538,BO_1977_06203,desconocido,1977-06-25,29,12A/1512,HsPAFPs
59008,BO_1977_06673,desconocida,1977-12-17,25,12A/3045,HPAF
61412,BO_1978_01911,glen hart carroll,1978-09-15,42,12A/2295,HPAFPC
61790,BO_1978_02289,heart lupio brian,1978-09-15,2 años,12A/2295,HPAFPC
66740,BO_1979_00099,aguino esquivel hipolito,1979-03-31,22,19A/593,HPAFPT
68835,BO_1979_02194,garduno solorzano jose m.,1979-10-16,17,33A/2047,HPAFPT
68959,BO_1979_02318,hernandez gutierrez roberto,1979-03-31,25,19A/593,HPAFPC
70172,BO_1979_03531,mayen mayen guillermina,1979-10-10,20,14A/3216,HPAFPT
70173,BO_1979_03532,mayen gonzalez lorenzo,1979-10-10,54,14A/3216,HsPAFPs
70184,BO_1979_03543,mora gonzalez alejandro,1979-10-15,25,37A/821,HPAFPT