# Bitacoras onomásticas SEMEFO 1968-1982
# Hipotesis de búsqueda

In [1]:
import pandas as pd
from numpy import nan
import datetime

import matplotlib.pyplot as plt
import seaborn as sns

def summary_top_series(s, n_values=5, sep=', ', **kwargs):
    s = s.value_counts(**kwargs).head(n_values)
    s = s.to_dict()
    s = sep.join([f"{k} ({v})" for k,v in s.items()])
    return s

In [2]:
colors = {'conocido':'#8dd3c7', #verde retoño
          'desconocido':'#fdb462', #naranja
          'Femenino':'#bc80bd', #magenta
          'Masculino':'#80b1d3', #azul
          'S-D':'#999999', #gris
          'Cadáver':'#ffffb3', #amarillo
          'Recién nacido':'#f560ac', #rosa
          'Feto':'#bebada', #lila
          'Miembros':'#b3de69', #verde amarillo
          'Restos óseos':'#fb8072' # rojo
         }
colors['Cadáver conocido'] = colors['conocido']
colors['Cadáver desconocido'] = colors['desconocido']

key_col = ['ID','Nombre_completo_transcrito', 'Tipo_restos','Conocido_desconocido', 
           'Sexo', 'Edad_transcrito', 'Edad_estandar', 'Fecha_transcrito', 'Fecha_estandar', 
           'Expediente_SEMEFO_transcrito', 'Procedencia_acta', 'Procedencia_transcrito', 
           'Procedencia_direccion', 'Diagnostico_transcrito', 'Diagnostico_extendido']

In [3]:
df = pd.read_pickle('data_clean/SEMEFO_BO_all.pkl')
df['Bitacora_ingresos'] = df['Bitacora_ingresos'].apply(lambda s: s.replace('semefo_df_bo_',''))
df

,ID,Numero_progresivo_transcrito,Nombre_completo_transcrito,Primer_apellido,Segundo_apellido,Nombres_propios,Fecha_transcrito,Fecha_estandar,Fecha_añomes,Fecha_diasemana,...,Procedencia_acta,Diagnostico_transcrito,Diagnostico_estandar,Diagnostico_extendido,Tipo_restos,Conocido_desconocido,Bitacora_ingresos,Pagina_PDF,Foja_transcrito,Observaciones
0,BO_1968_00001,NaN,acosta ortega teresa,acosta,ortega,teresa,1968-01-03,1968-01-03,1968 Enero,Miércoles,...,NaN,S-D,S-D,S-D,Cadáver,conocido,1968,2,1,NaN
1,BO_1968_00002,NaN,avila de cuestas catalina,avila,de cuestas,catalina,1968-01-05,1968-01-05,1968 Enero,Viernes,...,NaN,S-D,S-D,S-D,Cadáver,conocido,1968,2,1,NaN
2,BO_1968_00003,NaN,arzate paredes juan,arzate,paredes,juan,1968-01-07,1968-01-07,1968 Enero,Domingo,...,NaN,S-D,S-D,S-D,Cadáver,conocido,1968,2,1,NaN
3,BO_1968_00004,NaN,alvarez martinez isaac,alvarez,martinez,isaac,1968-01-07,1968-01-07,1968 Enero,Domingo,...,NaN,S-D,S-D,S-D,Cadáver,conocido,1968,2,1,NaN
4,BO_1968_00005,NaN,arellano viuda de campos ma.,arellano,viuda de campos,ma.,1968-01-07,1968-01-07,1968 Enero,Domingo,...,NaN,S-D,S-D,S-D,Cadáver,conocido,1968,2,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96839,BO_1982_07489,NaN,placenta,S-D,S-D,S-D,1982-06-05,1982-06-05,1982 Junio,Sábado,...,15A/960,S-D,S-D,S-D,Miembros,desconocido,1982,251,156,NaN
96840,BO_1982_07490,NaN,5 dedos del pie derecho de desconocido,S-D,S-D,S-D,1982-06-05,1982-06-05,1982 Junio,Sábado,...,32A/950,S-D,S-D,S-D,Miembros,desconocido,1982,251,156,NaN
96841,BO_1982_07491,NaN,dedo de desconocido,S-D,S-D,S-D,1982-11-19,1982-11-19,1982 Noviembre,Viernes,...,32A/2005,S-D,S-D,S-D,Miembros,desconocido,1982,251,156,NaN
96842,BO_1982_07492,NaN,4 dedos de desconocido,S-D,S-D,S-D,1982-11-28,1982-11-28,1982 Noviembre,Domingo,...,27A/959,S-D,S-D,S-D,Miembros,desconocido,1982,251,156,NaN
96843,BO_1982_07493,NaN,osamenta de desconocido,S-D,S-D,S-D,1982-10-11,1982-10-11,1982 Octubre,Lunes,...,9A/4193,S-D,S-D,S-D,Cadáver,desconocido,1982,251,156,no se recibio necropsia. es una osamenta.

In [4]:
df.columns

Index(['ID', 'Numero_progresivo_transcrito', 'Nombre_completo_transcrito',
       'Primer_apellido', 'Segundo_apellido', 'Nombres_propios',
       'Fecha_transcrito', 'Fecha_estandar', 'Fecha_añomes', 'Fecha_diasemana',
       'Sexo', 'Edad_transcrito', 'Edad_estandar', 'Edad_rango',
       'Expediente_SEMEFO_transcrito', 'Procedencia_transcrito',
       'Procedencia_estandar', 'Procedencia_direccion', 'Procedencia_alcaldia',
       'Numero_acta_transcrito', 'Procedencia_acta', 'Diagnostico_transcrito',
       'Diagnostico_estandar', 'Diagnostico_extendido', 'Tipo_restos',
       'Conocido_desconocido', 'Bitacora_ingresos', 'Pagina_PDF',
       'Foja_transcrito', 'Observaciones'],
      dtype='object')

## 1. Confrontación con otras bases de datos

## 2. Características de interés

In [5]:
df.loc[(df['Procedencia_transcrito'].str.contains('SC')) | (df['Procedencia_estandar'].str.contains('SC')), key_col]

,ID,Nombre_completo_transcrito,Tipo_restos,Conocido_desconocido,Sexo,Edad_transcrito,Edad_estandar,Fecha_transcrito,Fecha_estandar,Expediente_SEMEFO_transcrito,Procedencia_acta,Procedencia_transcrito,Procedencia_direccion,Diagnostico_transcrito,Diagnostico_extendido
38885,BO_1975_00318,alatorre carlos,Cadáver,conocido,Masculino,S-D,NaN,S-D,NaT,S-D,SC/4596,SC,SC,S-D,S-D
39663,BO_1975_01096,cardenas ismael roberto,Cadáver,conocido,Masculino,25,25.0,1975-12-08,1975-12-08,S-D,SC/7098,SC,SC,HsPSFPs,NaN
41576,BO_1975_03009,molinas de de la poza margarita,Cadáver,conocido,Femenino,50,50.0,1975-05-21,1975-05-21,2573,300,SC-CH,NaN,??,S-D
41994,BO_1975_03427,morales gonzalez j luis,Cadáver,conocido,Masculino,28,28.0,1975-12-18,1975-12-18,S-D,SC/7098-7,SC,SC,HsPAF,herida arma fuego
45430,BO_1976_00002,arbel d. viuda de ch. esperanza,Cadáver,conocido,Femenino,80,80.0,1976-01-03,1976-01-03,25,SC/0014 M-105,SC,SC,BN+CH,NaN
49079,BO_1976_03651,ochoa melendez jesus,Cadáver,conocido,Masculino,25,25.0,1976-08-02,1976-08-02,4119,SC/3322,SC,SC,HPAFPA,herida arma fuego abdomen
49667,BO_1976_04239,rojas zamora pablo,Cadáver,conocido,Masculino,20,20.0,1976-05-11,1976-05-11,2539,SC/2840,SC,SC,HPAFPC,herida arma fuego craneo
52421,BO_1977_00086,alonso hernandez jose luis,Cadáver,conocido,Masculino,35,35.0,1977-03-29,1977-03-29,1719,SC/1903,SC,SC,HPAFPC,herida arma fuego craneo
55663,BO_1977_03328,martinez magdaleno celia,Cadáver,conocido,Femenino,19,19.0,1977-09-03,1977-09-03,4712,SC/5430,SC,SC,HPAFPT,herida arma fuego torax
55664,BO_1977_03329,montoya ortiz cruz e.,Cadáver,conocido,Femenino,20,20.0,1977-09-03,1977-09-03,4713,SC/5430,SC,SC,HPAFPC,herida arma fuego craneo
56815,BO_1977_04480,ramirez duarte j. manuel,Cadáver,conocido,Masculino,27,27.0,1977-09-03,1977-09-03,4714,SC/5430,SC,SC,HSPAF,herida arma fuego
65239,BO_1978_05738,desconocido 1,Cadáver,desconocido,Masculino,22,22.0,1978-01-10,1978-01-10,175,SC/97,SC,SC,HPAFPC,herida arma fuego craneo
65240,BO_1978_05739,desconocido 2,Cadáver,desconocido,Masculino,25,25.0,1978-01-10,1978-01-10,176,SC/97,SC,SC,HsPAFP,herida arma fuego
65241,BO_1978_05740,desconocido 3,Cadáver,desconocido,Masculino,24,24.0,1978-01-10,1978-01-10,177,SC/97,SC,SC,HPAFPC,herida arma fuego craneo
65652,BO_1978_06151,desconocida,Cadáver,desconocido,Femenino,24,24.0,1978-06-09,1978-06-09,3057,SC/3697,SC,SC,HsPAFPs,herida arma fuego
65653,BO_1978_06152,desconocido,Cadáver,desconocido,Masculino,27,27.0,1978-06-09,1978-06-09,3058,SC/3697,SC,SC,HsPAFPs,herida arma fuego
67166,BO_1979_00525,badillo hernandez raquel [exhumacion],Cadáver,conocido,Femenino,44,44.0,1979-07-10,1979-07-10,S-D,SC/1550,SC,SC,CVG,congestion visceral generalizada
67924,BO_1979_01283,dominguez reyes mariano,Cadáver,conocido,Masculino,17,17.0,1979-08-29,1979-08-29,4828,20A/2522,SC+20a,Ministerio Público 20 (UH Vicente Guerrero),TM,traumatismo multiple
68107,BO_1979_01466,flores millan enrique,Cadáver,conocido,Masculino,22,22.0,1979-02-04,1979-02-04,707,SC/727,SC,SC,HPAFPA,herida arma fuego abdomen
69033,BO_1979_02392,hurat araiza gilberto,Cadáver,conocido,Masculino,50,50.0,1979-06-23,1979-06-23,3532,SC/3726,SC,SC,CVG,congestion visceral generalizada
69514,BO_1979_02873,lopez martinez maria elena,Cadáver,conocido,Femenino,S-D,NaN,1979-09-06,1979-09-06,5133,SC/6580,SC,SC,Dispensa,dispensa
70047,BO_1979_03406,martinez perez jose luis,Cadáver,conocido,Masculino,35,35.0,1979-08-08,1979-08-08,4435,SC/5776,SC,SC,HsPAFPs,herida arma fuego
71682,BO_1979_05041,silva pina jesus,Cadáver,conocido,Masculino,49,49.0,1979-04-13,1979-04-13,2162,SC/2511,SC,SC,HPAFPTA,herida arma fuego torax abdomen
72062,BO_1979_05421,tovar villagordoa luis,Cadáver,conocido,Masculino,S-D,NaN,1979-09-06,1979-09-06,5134,SC/6580,SC,SC,Dispensa,dispensa
72303,BO_1979_05662,vadillo hernandez raquel,Cadáver,conocido,Femenino,44,44.0,1979-07-10,1979-07-10,S-D,SC/1550,SC,SC,S-D,S-D
73809,BO_1979_07168,feto,Feto,desconocido,Masculino,4,0.0,1979-10-31,1979-10-31,6119,SC/7987,SC,SC,Exp PSM,expulsion prematura del seno materno
73820,BO_1979_07179,feto,Feto,desconocido,S-D,S-D,0.0,1979-11-15,1979-11-15,6447,SC/8313,SC,SC,Indeterminado,indeterminado
73867,BO_1979_07226,recien nacido,Recién nacido,desconocido,Masculino,-72,0.0,1979-11-19,1979-11-19,5911,SC/7401,SC,SC,Hernia Bockdebe,NaN
89734,BO_1982_00384,aguilera hernandez guillermo,Cadáver,conocido,Masculino,S-D,NaN,1982-12-15,1982-12-15,6894,SC/9373,SC,SC,S-D,S-D
90897,BO_1982_01547,estrada rendon manuel,Cadáver,conocido,Masculino,S-D,NaN,1982-01-01,1982-01-01,7286+7018,SC/9567,SC,SC,S-D,S-D
91690,BO_1982_02340,hernandez mendez isaac,Cadáver,conocido,Masculino,S-D,NaN,1982-01-31,1982-01-31,645,8A/655,8a+37a+SC,Ministerio Público 8 (Col Narvarte),S-D,S-D

In [6]:
df.loc[(df['Procedencia_transcrito'].str.contains('SC')) | (df['Procedencia_estandar'].str.contains('SC')), key_col]

,ID,Nombre_completo_transcrito,Tipo_restos,Conocido_desconocido,Sexo,Edad_transcrito,Edad_estandar,Fecha_transcrito,Fecha_estandar,Expediente_SEMEFO_transcrito,Procedencia_acta,Procedencia_transcrito,Procedencia_direccion,Diagnostico_transcrito,Diagnostico_extendido
38885,BO_1975_00318,alatorre carlos,Cadáver,conocido,Masculino,S-D,NaN,S-D,NaT,S-D,SC/4596,SC,SC,S-D,S-D
39663,BO_1975_01096,cardenas ismael roberto,Cadáver,conocido,Masculino,25,25.0,1975-12-08,1975-12-08,S-D,SC/7098,SC,SC,HsPSFPs,NaN
41576,BO_1975_03009,molinas de de la poza margarita,Cadáver,conocido,Femenino,50,50.0,1975-05-21,1975-05-21,2573,300,SC-CH,NaN,??,S-D
41994,BO_1975_03427,morales gonzalez j luis,Cadáver,conocido,Masculino,28,28.0,1975-12-18,1975-12-18,S-D,SC/7098-7,SC,SC,HsPAF,herida arma fuego
45430,BO_1976_00002,arbel d. viuda de ch. esperanza,Cadáver,conocido,Femenino,80,80.0,1976-01-03,1976-01-03,25,SC/0014 M-105,SC,SC,BN+CH,NaN
49079,BO_1976_03651,ochoa melendez jesus,Cadáver,conocido,Masculino,25,25.0,1976-08-02,1976-08-02,4119,SC/3322,SC,SC,HPAFPA,herida arma fuego abdomen
49667,BO_1976_04239,rojas zamora pablo,Cadáver,conocido,Masculino,20,20.0,1976-05-11,1976-05-11,2539,SC/2840,SC,SC,HPAFPC,herida arma fuego craneo
52421,BO_1977_00086,alonso hernandez jose luis,Cadáver,conocido,Masculino,35,35.0,1977-03-29,1977-03-29,1719,SC/1903,SC,SC,HPAFPC,herida arma fuego craneo
55663,BO_1977_03328,martinez magdaleno celia,Cadáver,conocido,Femenino,19,19.0,1977-09-03,1977-09-03,4712,SC/5430,SC,SC,HPAFPT,herida arma fuego torax
55664,BO_1977_03329,montoya ortiz cruz e.,Cadáver,conocido,Femenino,20,20.0,1977-09-03,1977-09-03,4713,SC/5430,SC,SC,HPAFPC,herida arma fuego craneo
56815,BO_1977_04480,ramirez duarte j. manuel,Cadáver,conocido,Masculino,27,27.0,1977-09-03,1977-09-03,4714,SC/5430,SC,SC,HSPAF,herida arma fuego
65239,BO_1978_05738,desconocido 1,Cadáver,desconocido,Masculino,22,22.0,1978-01-10,1978-01-10,175,SC/97,SC,SC,HPAFPC,herida arma fuego craneo
65240,BO_1978_05739,desconocido 2,Cadáver,desconocido,Masculino,25,25.0,1978-01-10,1978-01-10,176,SC/97,SC,SC,HsPAFP,herida arma fuego
65241,BO_1978_05740,desconocido 3,Cadáver,desconocido,Masculino,24,24.0,1978-01-10,1978-01-10,177,SC/97,SC,SC,HPAFPC,herida arma fuego craneo
65652,BO_1978_06151,desconocida,Cadáver,desconocido,Femenino,24,24.0,1978-06-09,1978-06-09,3057,SC/3697,SC,SC,HsPAFPs,herida arma fuego
65653,BO_1978_06152,desconocido,Cadáver,desconocido,Masculino,27,27.0,1978-06-09,1978-06-09,3058,SC/3697,SC,SC,HsPAFPs,herida arma fuego
67166,BO_1979_00525,badillo hernandez raquel [exhumacion],Cadáver,conocido,Femenino,44,44.0,1979-07-10,1979-07-10,S-D,SC/1550,SC,SC,CVG,congestion visceral generalizada
67924,BO_1979_01283,dominguez reyes mariano,Cadáver,conocido,Masculino,17,17.0,1979-08-29,1979-08-29,4828,20A/2522,SC+20a,Ministerio Público 20 (UH Vicente Guerrero),TM,traumatismo multiple
68107,BO_1979_01466,flores millan enrique,Cadáver,conocido,Masculino,22,22.0,1979-02-04,1979-02-04,707,SC/727,SC,SC,HPAFPA,herida arma fuego abdomen
69033,BO_1979_02392,hurat araiza gilberto,Cadáver,conocido,Masculino,50,50.0,1979-06-23,1979-06-23,3532,SC/3726,SC,SC,CVG,congestion visceral generalizada
69514,BO_1979_02873,lopez martinez maria elena,Cadáver,conocido,Femenino,S-D,NaN,1979-09-06,1979-09-06,5133,SC/6580,SC,SC,Dispensa,dispensa
70047,BO_1979_03406,martinez perez jose luis,Cadáver,conocido,Masculino,35,35.0,1979-08-08,1979-08-08,4435,SC/5776,SC,SC,HsPAFPs,herida arma fuego
71682,BO_1979_05041,silva pina jesus,Cadáver,conocido,Masculino,49,49.0,1979-04-13,1979-04-13,2162,SC/2511,SC,SC,HPAFPTA,herida arma fuego torax abdomen
72062,BO_1979_05421,tovar villagordoa luis,Cadáver,conocido,Masculino,S-D,NaN,1979-09-06,1979-09-06,5134,SC/6580,SC,SC,Dispensa,dispensa
72303,BO_1979_05662,vadillo hernandez raquel,Cadáver,conocido,Femenino,44,44.0,1979-07-10,1979-07-10,S-D,SC/1550,SC,SC,S-D,S-D
73809,BO_1979_07168,feto,Feto,desconocido,Masculino,4,0.0,1979-10-31,1979-10-31,6119,SC/7987,SC,SC,Exp PSM,expulsion prematura del seno materno
73820,BO_1979_07179,feto,Feto,desconocido,S-D,S-D,0.0,1979-11-15,1979-11-15,6447,SC/8313,SC,SC,Indeterminado,indeterminado
73867,BO_1979_07226,recien nacido,Recién nacido,desconocido,Masculino,-72,0.0,1979-11-19,1979-11-19,5911,SC/7401,SC,SC,Hernia Bockdebe,NaN
89734,BO_1982_00384,aguilera hernandez guillermo,Cadáver,conocido,Masculino,S-D,NaN,1982-12-15,1982-12-15,6894,SC/9373,SC,SC,S-D,S-D
90897,BO_1982_01547,estrada rendon manuel,Cadáver,conocido,Masculino,S-D,NaN,1982-01-01,1982-01-01,7286+7018,SC/9567,SC,SC,S-D,S-D
91690,BO_1982_02340,hernandez mendez isaac,Cadáver,conocido,Masculino,S-D,NaN,1982-01-31,1982-01-31,645,8A/655,8a+37a+SC,Ministerio Público 8 (Col Narvarte),S-D,S-D

## 3. Eventos de interés

In [12]:
date_min = datetime.datetime(1968, 10, 2)
date_max = date_min + datetime.timedelta(days=7)

data = df.loc[df['Fecha_estandar'].between(date_min, date_max, inclusive='both'), key_col].sort_values(by=['Fecha_estandar','Procedencia_acta'])
data

,ID,Nombre_completo_transcrito,Tipo_restos,Conocido_desconocido,Sexo,Edad_transcrito,Edad_estandar,Fecha_transcrito,Fecha_estandar,Expediente_SEMEFO_transcrito,Procedencia_acta,Procedencia_transcrito,Procedencia_direccion,Diagnostico_transcrito,Diagnostico_extendido
2351,BO_1968_02352,desconocido,Cadáver,desconocido,Masculino,S-D,NaN,1968-10-02,1968-10-02,3566,IZA/98600,Iztapalapa,Iztapalapa,S-D,S-D
1447,BO_1968_01448,feto,Feto,desconocido,S-D,S-D,0.0,1968-10-02,1968-10-02,3584,XO/541,Xochimilco,Xochimilco,S-D,S-D
354,BO_1968_00355,bobadilla maldonado victor,Cadáver,conocido,Masculino,S-D,NaN,1968-10-02,1968-10-02,3570,NaN,S-D,Sin datos,S-D,S-D
355,BO_1968_00356,banuelos vda. de morales eulalia,Cadáver,conocido,Femenino,S-D,NaN,1968-10-02,1968-10-02,3576,NaN,S-D,Sin datos,S-D,S-D
642,BO_1968_00643,cruz lucero amado,Cadáver,conocido,Masculino,S-D,NaN,1968-10-02,1968-10-02,3563,NaN,S-D,Sin datos,S-D,S-D
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1830,BO_1968_01831,gonzalez campoz amor,Cadáver,conocido,S-D,S-D,NaN,1968-10-09,1968-10-09,3692,NaN,S-D,Sin datos,S-D,S-D
2084,BO_1968_02085,hernandez garcia guadalupe,Cadáver,conocido,Femenino,S-D,NaN,1968-10-09,1968-10-09,3688,NaN,S-D,Sin datos,S-D,S-D
3675,BO_1968_03676,pacheco martinez eduardo,Cadáver,conocido,Masculino,S-D,NaN,1968-10-09,1968-10-09,3683,NaN,S-D,Sin datos,S-D,S-D
4044,BO_1968_04045,ruiz andres,Cadáver,conocido,Masculino,S-D,NaN,1968-10-09,1968-10-09,3691,NaN,S-D,Sin datos,S-D,S-D
4045,BO_1968_04046,ruiz herrejon antonio,Cadáver,conocido,Masculino,S-D,NaN,1968-10-09,1968-10-09,3693,NaN,S-D,Sin datos,S-D,S-D

In [13]:
date_min = datetime.datetime(1975, 4, 25)
date_max = date_min + datetime.timedelta(days=7)

data = df.loc[(df['Fecha_estandar'].between(date_min, date_max, inclusive='both')) & (df['Diagnostico_estandar'].str.contains('HPAF')==True), key_col] \
         .sort_values(by=['Fecha_estandar','Procedencia_acta'])
data

,ID,Nombre_completo_transcrito,Tipo_restos,Conocido_desconocido,Sexo,Edad_transcrito,Edad_estandar,Fecha_transcrito,Fecha_estandar,Expediente_SEMEFO_transcrito,Procedencia_acta,Procedencia_transcrito,Procedencia_direccion,Diagnostico_transcrito,Diagnostico_extendido
39388,BO_1975_00821,carbajal garcia alvaro,Cadáver,conocido,Masculino,36,36.0,1975-04-25,1975-04-25,2128,VC-1/838,VC-1,Coordinación Territorial 1 Venustiano Carranza...,HPAFP,herida arma fuego
39312,BO_1975_00745,cazales acosta juan,Cadáver,conocido,Masculino,30,30.0,1975-04-26,1975-04-26,2142,222,T-P-1 MH-CR,NaN,HPAFPTA,herida arma fuego torax abdomen
40995,BO_1975_02428,juarez lira porfirio,Cadáver,conocido,Masculino,39,39.0,1975-04-26,1975-04-26,2148,HX/375,C-HX,Hospital Xoco (Col General Anaya),HPAFPT,herida arma fuego torax
39005,BO_1975_00438,barcenas orduna alberto,Cadáver,conocido,Masculino,45,45.0,1975-04-26,1975-04-26,2137,TP-1/222,TP-1,Coordinación Territorial 1 Tlalpan (Col Amplia...,HsPAFPs,herida arma fuego
39322,BO_1975_00755,camahco cruz m francisco,Cadáver,conocido,Masculino,28,28.0,1975-04-26,1975-04-26,2135,TP-1/222,TP-1,Coordinación Territorial 1 Tlalpan (Col Amplia...,HsPAFPs,herida arma fuego
39881,BO_1975_01314,espinoza olascoaga miguel,Cadáver,conocido,Masculino,30,30.0,1975-04-26,1975-04-26,2138,TP-1/222,TP-1,Coordinación Territorial 1 Tlalpan (Col Amplia...,HsPAFPsC,herida arma fuego craneo
40298,BO_1975_01731,garza arrieta enrique,Cadáver,conocido,Masculino,55,55.0,1975-04-26,1975-04-26,2136,TP-1/222,TP-1,Coordinación Territorial 1 Tlalpan (Col Amplia...,HsPAFPsTA,herida arma fuego torax abdomen
42169,BO_1975_03602,ortiz pineda jesus,Cadáver,conocido,Masculino,25,25.0,1975-04-26,1975-04-26,2134,TP-1/222,TP-1,Coordinación Territorial 1 Tlalpan (Col Amplia...,HPAF,herida arma fuego
42789,BO_1975_04222,rabodan salgado hipolito,Cadáver,conocido,Masculino,38,38.0,1975-04-26,1975-04-26,2140,TP-1/222,TP-1,Coordinación Territorial 1 Tlalpan (Col Amplia...,HsPAFPs,herida arma fuego
42793,BO_1975_04226,romero de la rosa mordorio,Cadáver,conocido,Masculino,32,32.0,1975-04-26,1975-04-26,2141,TP-1/222,TP-1,Coordinación Territorial 1 Tlalpan (Col Amplia...,HsPAFPsC,herida arma fuego craneo
42774,BO_1975_04207,ramirez guadarrama humberto,Cadáver,conocido,Masculino,31,31.0,1975-04-27,1975-04-27,2160,BJ-1/703,BJ-1,Coordinación Territorial 1 Benito Juárez (Col ...,HPAFPT,herida arma fuego torax
38996,BO_1975_00429,basurto leyva r mariano,Cadáver,conocido,Masculino,20,20.0,1975-04-27,1975-04-27,2159,HCM/814,BJ-CM,Hospital Centro Médico 20 de Noviembre (Col de...,HPAFPTA,herida arma fuego torax abdomen
41531,BO_1975_02964,montejo lopez manuel,Cadáver,conocido,Masculino,26,26.0,1975-04-27,1975-04-27,2181,HTB/708,VC-HB,Hospital Balbuena (Col Jardín Balbuena),HsPAFPsA,herida arma fuego abdomen
38997,BO_1975_00430,basaldua rivera rodolfo,Cadáver,conocido,Masculino,40,40.0,1975-04-27,1975-04-27,2172,TP-1/210,TP-1,Coordinación Territorial 1 Tlalpan (Col Amplia...,HsPAFPsTA,herida arma fuego torax abdomen
43310,BO_1975_04743,saucedo cadena francisco,Cadáver,conocido,Masculino,45,45.0,1975-04-28,1975-04-28,2179,VC-1/923,VC-1,Coordinación Territorial 1 Venustiano Carranza...,HPAFPC,herida arma fuego craneo
39877,BO_1975_01310,esparza guzman luz ma,Cadáver,conocido,Femenino,29,29.0,1975-04-29,1975-04-29,2206,AO-1/649,AO-1,Coordinación Territorial 1 Álvaro Obregón (Col...,HPAFPT,herida arma fuego torax
44381,BO_1975_05814,desconocido,Cadáver,desconocido,Masculino,28,28.0,1975-04-29,1975-04-29,2193,BJ-2/572,BJ-2,Coordinación Territorial 2 Benito Juárez (Col ...,HPAFPT,herida arma fuego torax
43800,BO_1975_05233,villegas resendiz raul,Cadáver,conocido,Masculino,21,21.0,1975-04-29,1975-04-29,2201,VC-2/940,VC-2,Coordinación Territorial 2 Venustiano Carranza...,HsPAFPsC,herida arma fuego craneo
42771,BO_1975_04204,rodriguez herrera severo,Cadáver,conocido,Masculino,20,20.0,1975-04-30,1975-04-30,2220,MH-CR/449,MH-CR,Cruz Roja (Col Polanco),HPAFPC,herida arma fuego craneo
42772,BO_1975_04205,ramirez arista jose luis,Cadáver,conocido,Masculino,30,30.0,1975-05-01,1975-05-01,2225,1137,BJ-CM-GAM-1,NaN,HPAFPTA,herida arma fuego torax abdomen
43335,BO_1975_04768,samano arriaga camilo,Cadáver,conocido,Masculino,42,42.0,1975-05-02,1975-05-02,2546,HRL/438,MH-HRL,Hospital Rubén Leñero (Col Santo Tomás),HPAFPA,herida arma fuego abdomen
40282,BO_1975_01715,gutierrez saenzs eduardo,Cadáver,conocido,Masculino,33,33.0,1975-05-02,1975-05-02,2245,MH-CR/463,MH-CR,Cruz Roja (Col Polanco),HPAFPC,herida arma fuego craneo

## 4. Grupos de interés
### Por acta

In [10]:
data = df.loc[df['Diagnostico_estandar'].str.contains('HPAF')==True, key_col]
display(data.shape)
index = data['Procedencia_acta'].value_counts()>2
index = index[index].index
data[data['Procedencia_acta'].isin(index)].sort_values(by='Procedencia_acta')

(3026, 15)

,ID,Nombre_completo_transcrito,Tipo_restos,Conocido_desconocido,Sexo,Edad_transcrito,Edad_estandar,Fecha_transcrito,Fecha_estandar,Expediente_SEMEFO_transcrito,Procedencia_acta,Procedencia_transcrito,Procedencia_direccion,Diagnostico_transcrito,Diagnostico_extendido
58538,BO_1977_06203,desconocido,Cadáver,desconocido,Masculino,29,29.0,1977-06-25,1977-06-25,3390,12A/1512,12a,Ministerio Público 12 (Col Portales),HsPAFPs,herida arma fuego
58512,BO_1977_06177,desconocido,Cadáver,desconocido,Masculino,29,29.0,1977-06-25,1977-06-25,3390,12A/1512,12a,Ministerio Público 12 (Col Portales),HsPAFPs,herida arma fuego
58504,BO_1977_06169,desconocido,Cadáver,desconocido,Masculino,29,29.0,1977-06-25,1977-06-25,3391,12A/1512,12a,Ministerio Público 12 (Col Portales),HsPAFPsT,herida arma fuego torax
33719,BO_1974_00883,calixto de la cruz antonio a.,Cadáver,conocido,Masculino,45,45.0,1974-10-01,1974-10-01,4715,15A/1993,15a,Ministerio Público 15 (Col Aragón La Villa),HsPAFPC,herida arma fuego craneo
35849,BO_1974_03013,maldonado sanchez jose a,Cadáver,conocido,Masculino,25,25.0,1974-10-01,1974-10-01,4716,15A/1993,15a,Ministerio Público 15 (Col Aragón La Villa),HsPAFPsCT,herida arma fuego craneo torax
36379,BO_1974_03543,perales hernandez guillermo,Cadáver,conocido,Masculino,65,65.0,1974-10-02,1974-10-02,4714,15A/1993,15a,Ministerio Público 15 (Col Aragón La Villa),HPAFPC,herida arma fuego craneo
58534,BO_1977_06199,desconocida liga 23 de sep.ledezma cruz olivia,Cadáver,conocido,Femenino,25,25.0,1977-07-07,1977-07-07,3604,18A/1582,18a,Ministerio Público 18 (Col Ramos Millán),HPAFPC,herida arma fuego craneo
58533,BO_1977_06198,desconocido liga 23 de sep.,Cadáver,desconocido,Masculino,25,25.0,1977-07-07,1977-07-07,3603,18A/1582,18a,Ministerio Público 18 (Col Ramos Millán),HPAFPC,herida arma fuego craneo
55095,BO_1977_02760,ledezma cruz olivia,Cadáver,conocido,Femenino,23,23.0,1977-07-07,1977-07-07,3604,18A/1582,18,Ministerio Público 18 (Col Ramos Millán),HPAF,herida arma fuego
63736,BO_1978_04235,rodriguez de san miguel martha,Cadáver,conocido,Femenino,39,39.0,1978-03-12,1978-03-12,1435,18A/644,18a,Ministerio Público 18 (Col Ramos Millán),HPAFPT,herida arma fuego torax
59940,BO_1978_00439,bustos rodriguez jorge o.,Cadáver,conocido,Masculino,21,21.0,1978-03-12,1978-03-12,1437,18A/644,18a,Ministerio Público 18 (Col Ramos Millán),HPAFPC,herida arma fuego craneo
59939,BO_1978_00438,bustos noriega jorge,Cadáver,conocido,Masculino,44,44.0,1978-03-12,1978-03-12,1436,18A/644,18a,Ministerio Público 18 (Col Ramos Millán),HPAFPT,herida arma fuego torax
70474,BO_1979_03833,ortiz de montano dolores,Cadáver,conocido,Masculino,42,42.0,1979-05-08,1979-05-08,2008,19A/634,19a,Ministerio Público 19 (Col Barrio de San Lucas),HPAFPT,herida arma fuego torax
69826,BO_1979_03185,montano escobar luis,Cadáver,conocido,Masculino,55,55.0,1979-04-08,1979-04-08,2016,19A/634,19a,Ministerio Público 19 (Col Barrio de San Lucas),HPAFPC,herida arma fuego craneo
70472,BO_1979_03831,ortiz de montano dolores,Cadáver,conocido,Masculino,42,42.0,1979-04-08,1979-04-08,2008,19A/634,19a,Ministerio Público 19 (Col Barrio de San Lucas),HPAFPT,herida arma fuego torax
33031,BO_1974_00195,amastal zamora luis,Cadáver,conocido,Masculino,28,28.0,1974-08-18,1974-08-18,3930,24A/1324,24a,Ministerio Público 24 (Col Progreso Tizapán),HsPAFPsC,herida arma fuego craneo
34050,BO_1974_01214,estrada alegria marco antonio,Cadáver,conocido,Masculino,18,18.0,1974-08-19,1974-08-19,3950,24A/1324,24a,Ministerio Público 24 (Col Progreso Tizapán),HPAFPT,herida arma fuego torax
33795,BO_1974_00959,cortes chaves agustin,Cadáver,conocido,Masculino,59,59.0,1974-11-23,1974-11-23,5662,24A/1324,24a,Ministerio Público 24 (Col Progreso Tizapán),HsPAFPsTA,herida arma fuego torax abdomen
33733,BO_1974_00897,correa hernandez antelmo,Cadáver,conocido,Masculino,70,70.0,1974-10-09,1974-10-09,4855,27A/745,27a,Ministerio Público 27 (San Pedro),HSPAFPsA,herida arma fuego abdomen
35058,BO_1974_02222,ibanez flores jose luis,Cadáver,conocido,Masculino,34,34.0,1974-06-09,1974-06-09,4857,27A/745,27a,Ministerio Público 27 (San Pedro),HsPAFPsT,herida arma fuego torax
33734,BO_1974_00898,castillo perez ivan,Cadáver,conocido,Masculino,35,35.0,1974-10-09,1974-10-09,4856,27A/745,27a,Ministerio Público 27 (San Pedro),HsPAFPsCT,herida arma fuego craneo torax
62826,BO_1978_03325,medrano correa manuel,Cadáver,conocido,Masculino,60,60.0,1978-10-01,1978-10-01,5299,27A/745,27a,Ministerio Público 27 (San Pedro),HPAFPA,herida arma fuego abdomen
58626,BO_1977_06291,desconocido,Cadáver,desconocido,Masculino,20,20.0,1977-08-04,1977-08-04,4091,6A/1599,6a,Ministerio Público 6 (Col Centro),HsPAFPs,herida arma fuego
53599,BO_1977_01264,dominguez lozada isidro,Cadáver,conocido,Masculino,36,36.0,1977-08-04,1977-08-04,4090,6A/1599,6a,Ministerio Público 6 (Col Centro),HsPAFPs,herida arma fuego
53598,BO_1977_01263,dominguez lozada eligio,Cadáver,conocido,Masculino,22,22.0,1977-08-04,1977-08-04,4089,6A/1599,6a,Ministerio Público 6 (Col Centro),HsPAFPs,herida arma fuego
56462,BO_1977_04127,ruiz matuto leobardo,Cadáver,conocido,Masculino,25,25.0,1977-01-17,1977-01-17,341,CH-2/66,CH-II,Coordinación Territorial 2 Cuauhtémoc (Col Bue...,HsPA,herida arma fuego
55909,BO_1977_03574,naranjo martinez diosdado,Cadáver,conocido,Masculino,35,35.0,1977-01-18,1977-01-18,343,CH-2/66,CH-II,Coordinación Territorial 2 Cuauhtémoc (Col Bue...,HsPAFPsTA,herida arma fuego torax abdomen
52752,BO_1977_00417,barajas fernandez rosario,Cadáver,conocido,Femenino,59,59.0,1977-01-17,1977-01-17,342,CH-2/66,CH-II,Coordinación Territorial 2 Cuauhtémoc (Col Bue...,HsPAFPsTA,herida arma fuego torax abdomen
52344,BO_1977_00009,alvarado munoz leticia,Cadáver,conocido,Femenino,21,21.0,1977-01-17,1977-01-17,330,CH-2/66,CH-II,Coordinación Territorial 2 Cuauhtémoc (Col Bue...,HPAFPT,herida arma fuego torax
49260,BO_1976_03832,palacio mena guilermo,Cadáver,conocido,Masculino,45,45.0,1976-05-07,1976-05-07,2460,GAM-1/1250,GAM-1,Coordinación Territorial 1 Gustavo A. Madero (...,HsPAFPs,herida arma fuego
47162,BO_1976_01734,guevara ortega manuel,Cadáver,conocido,Masculino,38,38.0,1976-05-07,1976-05-07,2456,GAM-1/1250,GAM-I,Coordinación Territorial 1 Gustavo A. Madero (...,HsPAF,herida arma fuego
46182,BO_1976_00754,lando morales alfredo,Cadáver,conocido,Masculino,25,25.0,1976-05-07,1976-05-07,2455,GAM-1/1250,GAM-I,Coordinación Territorial 1 Gustavo A. Madero (...,HPAFPC,herida arma fuego craneo
49657,BO_1976_04229,reyes morales raymundo,Cadáver,conocido,Masculino,40,40.0,1976-05-07,1976-05-07,2452,GAM-1/1250,GAM-1,Coordinación Territorial 1 Gustavo A. Madero (...,HsPAFPs,herida arma fuego
37373,BO_1974_04537,desconocida (4),Cadáver,desconocido,Femenino,19,19.0,1974-02-15,1974-02-15,794,PGR/746,PGR,Procuraduría General de la República,HPAFPC,herida arma fuego craneo
37372,BO_1974_04536,desconocido (3),Cadáver,desconocido,Masculino,25,25.0,1974-02-15,1974-02-15,793,PGR/746,PGR,Procuraduría General de la República,HsPAFPsTA,herida arma fuego torax abdomen
37371,BO_1974_04535,desconocido (2),Cadáver,desconocido,Masculino,38,38.0,1974-02-15,1974-02-15,792,PGR/746,PGR,Procuraduría General de la República,HPAFPC,herida arma fuego craneo
55663,BO_1977_03328,martinez magdaleno celia,Cadáver,conocido,Femenino,19,19.0,1977-09-03,1977-09-03,4712,SC/5430,SC,SC,HPAFPT,herida arma fuego torax
56815,BO_1977_04480,ramirez duarte j. manuel,Cadáver,conocido,Masculino,27,27.0,1977-09-03,1977-09-03,4714,SC/5430,SC,SC,HSPAF,herida arma fuego
55664,BO_1977_03329,montoya ortiz cruz e.,Cadáver,conocido,Femenino,20,20.0,1977-09-03,1977-09-03,4713,SC/5430,SC,SC,HPAFPC,herida arma fuego craneo
65240,BO_1978_05739,desconocido 2,Cadáver,desconocido,Masculino,25,25.0,1978-01-10,1978-01-10,176,SC/97,SC,SC,HsPAFP,herida arma fuego
65241,BO_1978_05740,desconocido 3,Cadáver,desconocido,Masculino,24,24.0,1978-01-10,1978-01-10,177,SC/97,SC,SC,HPAFPC,herida arma fuego craneo
65239,BO_1978_05738,desconocido 1,Cadáver,desconocido,Masculino,22,22.0,1978-01-10,1978-01-10,175,SC/97,SC,SC,HPAFPC,herida arma fuego craneo
42793,BO_1975_04226,romero de la rosa mordorio,Cadáver,conocido,Masculino,32,32.0,1975-04-26,1975-04-26,2141,TP-1/222,TP-1,Coordinación Territorial 1 Tlalpan (Col Amplia...,HsPAFPsC,herida arma fuego craneo
42789,BO_1975_04222,rabodan salgado hipolito,Cadáver,conocido,Masculino,38,38.0,1975-04-26,1975-04-26,2140,TP-1/222,TP-1,Coordinación Territorial 1 Tlalpan (Col Amplia...,HsPAFPs,herida arma fuego
42169,BO_1975_03602,ortiz pineda jesus,Cadáver,conocido,Masculino,25,25.0,1975-04-26,1975-04-26,2134,TP-1/222,TP-1,Coordinación Territorial 1 Tlalpan (Col Amplia...,HPAF,herida arma fuego
39322,BO_1975_00755,camahco cruz m francisco,Cadáver,conocido,Masculino,28,28.0,1975-04-26,1975-04-26,2135,TP-1/222,TP-1,Coordinación Territorial 1 Tlalpan (Col Amplia...,HsPAFPs,herida arma fuego
39005,BO_1975_00438,barcenas orduna alberto,Cadáver,conocido,Masculino,45,45.0,1975-04-26,1975-04-26,2137,TP-1/222,TP-1,Coordinación Territorial 1 Tlalpan (Col Amplia...,HsPAFPs,herida arma fuego
40298,BO_1975_01731,garza arrieta enrique,Cadáver,conocido,Masculino,55,55.0,1975-04-26,1975-04-26,2136,TP-1/222,TP-1,Coordinación Territorial 1 Tlalpan (Col Amplia...,HsPAFPsTA,herida arma fuego torax abdomen
39881,BO_1975_01314,espinoza olascoaga miguel,Cadáver,conocido,Masculino,30,30.0,1975-04-26,1975-04-26,2138,TP-1/222,TP-1,Coordinación Territorial 1 Tlalpan (Col Amplia...,HsPAFPsC,herida arma fuego craneo
39450,BO_1975_00883,cano cortes luis,Cadáver,conocido,Masculino,40,40.0,1975-08-12,1975-08-12,4120,VC-1/1620,VC-1,Coordinación Territorial 1 Venustiano Carranza...,HPAFPC,herida arma fuego craneo
41227,BO_1975_02660,lara guerrero cipriano,Cadáver,conocido,Masculino,35,35.0,1975-08-13,1975-08-13,4122,VC-1/1620,VC-1,Coordinación Territorial 1 Venustiano Carranza...,HsPAFPsTA,herida arma fuego torax abdomen
39459,BO_1975_00892,camparan arias anacleto,Cadáver,conocido,Masculino,43,43.0,1975-08-12,1975-08-12,4119,VC-1/1620,VC-1,Coordinación Territorial 1 Venustiano Carranza...,HsPAFPs,herida arma fuego
38775,BO_1975_00208,alonso varas sergio,Cadáver,conocido,Masculino,23,23.0,1975-08-13,1975-08-13,4135,VC-1/1620,VC-1,Coordinación Territorial 1 Venustiano Carranza...,HsPA,herida arma fuego
42988,BO_1975_04421,rojaro miranda mario,Cadáver,conocido,Masculino,21,21.0,1975-09-13,1975-09-13,4719,VC-2/2014,VC-2,Coordinación Territorial 2 Venustiano Carranza...,HPAFPC,herida arma fuego craneo
41255,BO_1975_02688,lopez rincon lessia,Cadáver,conocido,Femenino,20,20.0,1975-09-14,1975-09-14,4735,VC-2/2014,VC-2,Coordinación Territorial 2 Venustiano Carranza...,HPAFPT,herida arma fuego torax
38801,BO_1975_00234,aguirre tapia gonzalo,Cadáver,conocido,Masculino,40,40.0,1975-09-13,1975-09-13,4718,VC-2/2014,VC-2,Coordinación Territorial 2 Venustiano Carranza...,HsPAFPsTA,herida arma fuego torax abdomen
49434,BO_1976_04006,quintin ortiz maria dolores,Cadáver,conocido,Femenino,26,26.0,1976-04-22,1976-04-22,2202,VC-2/940,VC-2,Coordinación Territorial 2 Venustiano Carranza...,HPAFPT,herida arma fuego torax
46162,BO_1976_00734,chavez delgado fermin,Cadáver,conocido,Masculino,25,25.0,1976-04-22,1976-04-22,2186,VC-2/940,VC-II,Coordinación Territorial 2 Venustiano Carranza...,HPAFPC,herida arma fuego craneo
43800,BO_1975_05233,villegas resendiz raul,Cadáver,conocido,Masculino,21,21.0,1975-04-29,1975-04-29,2201,VC-2/940,VC-2,Coordinación Territorial 2 Venustiano Carranza...,HsPAFPsC,herida arma fuego craneo

### Por día de ingreso

In [14]:
data = df.loc[df['Diagnostico_estandar'].str.contains('HPAF')==True, key_col]
data.groupby('Fecha_estandar').filter(lambda g: len(g)>3).sort_values(by=['Fecha_estandar','Procedencia_acta'])

,ID,Nombre_completo_transcrito,Tipo_restos,Conocido_desconocido,Sexo,Edad_transcrito,Edad_estandar,Fecha_transcrito,Fecha_estandar,Expediente_SEMEFO_transcrito,Procedencia_acta,Procedencia_transcrito,Procedencia_direccion,Diagnostico_transcrito,Diagnostico_extendido
35495,BO_1974_02659,mendoza pena antonio,Cadáver,conocido,Masculino,25,25.0,1974-02-15,1974-02-15,780,23A/81,23a,Ministerio Público 23 (Col La Joya Tlalpan),HPAFPC,herida arma fuego craneo
37371,BO_1974_04535,desconocido (2),Cadáver,desconocido,Masculino,38,38.0,1974-02-15,1974-02-15,792,PGR/746,PGR,Procuraduría General de la República,HPAFPC,herida arma fuego craneo
37372,BO_1974_04536,desconocido (3),Cadáver,desconocido,Masculino,25,25.0,1974-02-15,1974-02-15,793,PGR/746,PGR,Procuraduría General de la República,HsPAFPsTA,herida arma fuego torax abdomen
37373,BO_1974_04537,desconocida (4),Cadáver,desconocido,Femenino,19,19.0,1974-02-15,1974-02-15,794,PGR/746,PGR,Procuraduría General de la República,HPAFPC,herida arma fuego craneo
33907,BO_1974_01071,devesa sanabre angel,Cadáver,conocido,Masculino,65,65.0,1974-03-04,1974-03-04,2147,13A/2436,13a,Ministerio Público 13 (Col Aragón La Villa),HPAFPC,herida arma fuego craneo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70437,BO_1979_03796,nunez barrionuevo julio c.,Cadáver,conocido,Masculino,13,13.0,1979-12-25,1979-12-25,7380,33A/2602,33a,Ministerio Público 33 (Col Jardín Balbuena),HPAFP,herida arma fuego
67036,BO_1979_00395,ayala hernandez jose luis,Cadáver,conocido,Masculino,5,5.0,1979-12-26,1979-12-26,7381,11A/3393,11a,Ministerio Público 11 (Col Tacubaya),HPAFPC,herida arma fuego craneo
69595,BO_1979_02954,luna bonilla jose e,Cadáver,conocido,Masculino,18,18.0,1979-12-26,1979-12-26,7376,13A/2295,13a,Ministerio Público 13 (Col Aragón La Villa),HPAFPT,herida arma fuego torax
71541,BO_1979_04900,ramirez oseguera carlos,Cadáver,conocido,Masculino,25,25.0,1979-12-26,1979-12-26,7365,20A/3693,20a,Ministerio Público 20 (UH Vicente Guerrero),HPAFPT,herida arma fuego torax
70573,BO_1979_03932,ortega gonzalez esteban,Cadáver,conocido,Masculino,22,22.0,1979-12-26,1979-12-26,7401,37A/1045,37a,Ministerio Público 37 (Col Polanco),HPAFP,herida arma fuego

## 5. Análisis de datos faltantes

In [16]:
df.columns

Index(['ID', 'Numero_progresivo_transcrito', 'Nombre_completo_transcrito',
       'Primer_apellido', 'Segundo_apellido', 'Nombres_propios',
       'Fecha_transcrito', 'Fecha_estandar', 'Fecha_añomes', 'Fecha_diasemana',
       'Sexo', 'Edad_transcrito', 'Edad_estandar', 'Edad_rango',
       'Expediente_SEMEFO_transcrito', 'Procedencia_transcrito',
       'Procedencia_estandar', 'Procedencia_direccion', 'Procedencia_alcaldia',
       'Numero_acta_transcrito', 'Procedencia_acta', 'Diagnostico_transcrito',
       'Diagnostico_estandar', 'Diagnostico_extendido', 'Tipo_restos',
       'Conocido_desconocido', 'Bitacora_ingresos', 'Pagina_PDF',
       'Foja_transcrito', 'Observaciones'],
      dtype='object')

In [26]:
data = df.replace('S-D',nan)
data.loc[(data['Numero_acta_transcrito'].notna()) & (data['Procedencia_transcrito'].isna()) , 'Procedencia_acta'].to_list()

['95502',
 '444',
 '38242',
 '67094',
 '48447',
 '96345',
 '96833',
 '27494',
 '73427',
 '26789',
 '37363',
 '97577',
 '83416',
 '199',
 '47635',
 '39348',
 '23948/69',
 '72859',
 '96328',
 '68282',
 '74698',
 '23140',
 '15290',
 '733',
 '31146',
 '37472',
 '98266',
 '18122',
 '49725',
 '57047',
 '1608',
 '44724',
 '90317',
 '13285',
 '99264-70',
 '1',
 '99264/70',
 '40333',
 '20382',
 '73376',
 '127',
 '860',
 '71029',
 'S',
 '98937',
 '72128',
 '15640',
 '3',
 '72731',
 '6461',
 '5',
 '73023',
 '20208',
 '71167',
 '83787',
 '71143',
 '68189',
 '84477',
 '75227',
 '27063',
 '25075',
 '49405',
 '47159',
 '310',
 '95234',
 '67655',
 'H.T.B./70879',
 '24211',
 '350',
 '40482',
 '21660',
 '1984',
 '13151',
 '22140',
 '68709',
 '29261',
 '31382',
 '3156',
 '73345',
 '31395',
 '70947',
 '83721',
 '40423',
 '97933',
 '37582',
 '738',
 '29066',
 '37',
 '9127',
 '73523',
 '13505',
 '816',
 '31759',
 '98176',
 '34984',
 '1440',
 '84162',
 '2066',
 '15599',
 '1113',
 '71284',
 '99275',
 '26448',
 '1183',
 '49619',
 '8389',
 '83297',
 '38532',
 '73505',
 '31690',
 '70873',
 '60733',
 '40461',
 '42934',
 '42933',
 '43939',
 '34786',
 '2293',
 '6035',
 '11-18-78',
 'TL-18-78',
 '556/195',
 '1936',
 '1371-77',
 '1230-77',
 '2738',
 '2923',
 '1065',
 '4482',
 '314',
 '3569',
 '4083',
 '5490',
 '1676',
 '3569',
 '4482',
 '4083',
 '4174',
 '5208',
 '2930',
 '5657',
 '181',
 '8537',
 '91',
 '5208',
 '5298',
 '8394',
 '8767',
 '5881',
 '6139',
 '6139',
 '5315',
 '3104',
 '3104',
 '5657',
 '7936',
 '24/3396/',
 '30/3121/82',
 '24/3396/',
 '30/3121/82']

In [21]:
data.loc[data['Expediente_SEMEFO_transcrito'].isna(), key_col]

,ID,Nombre_completo_transcrito,Tipo_restos,Conocido_desconocido,Sexo,Edad_transcrito,Edad_estandar,Fecha_transcrito,Fecha_estandar,Expediente_SEMEFO_transcrito,Procedencia_acta,Procedencia_transcrito,Procedencia_direccion,Diagnostico_transcrito,Diagnostico_extendido
613,BO_1968_00614,cabrera perea evaristo,Cadáver,conocido,Masculino,NaN,NaN,1968-08-28,1968-08-28,NaN,NaN,NaN,Sin datos,NaN,NaN
662,BO_1968_00663,chemor vda. de chuayffet,Cadáver,conocido,Femenino,NaN,NaN,1968-10-31,1968-10-31,NaN,NaN,NaN,Sin datos,NaN,NaN
711,BO_1968_00712,chumasero bueno andres,Cadáver,conocido,Masculino,NaN,NaN,1968-12-04,1968-12-04,NaN,NaN,NaN,Sin datos,NaN,NaN
1416,BO_1968_01417,figueroa de la luz sara,Cadáver,conocido,Femenino,NaN,NaN,1968-08-13,1968-08-13,NaN,NaN,NaN,Sin datos,NaN,NaN
2390,BO_1968_02391,desconocido,Cadáver,desconocido,Masculino,NaN,NaN,1968-09-25,1968-09-25,NaN,HTV/74242,H.T.V.,Hospital la Villa (Col Granjas Modernas),NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96394,BO_1982_07044,desconocido,Cadáver,desconocido,Masculino,NaN,NaN,1982-11-18,1982-11-18,NaN,13A/4591,13a,Ministerio Público 13 (Col Aragón La Villa),NaN,NaN
96538,BO_1982_07188,desconocido,Cadáver,desconocido,Masculino,NaN,NaN,NaN,NaT,NaN,NaN,NaN,Sin datos,NaN,NaN
96556,BO_1982_07206,desconocido,Cadáver,desconocido,Masculino,NaN,NaN,NaN,NaT,NaN,NaN,NaN,Sin datos,NaN,NaN
96559,BO_1982_07209,desconocido,Cadáver,desconocido,Masculino,NaN,NaN,1982-12-27,1982-12-27,NaN,33A/2375,33a,Ministerio Público 33 (Col Jardín Balbuena),NaN,NaN
96595,BO_1982_07245,feto,Feto,desconocido,NaN,NaN,0.0,1982-04-14,1982-04-14,NaN,33A/953,33a,Ministerio Público 33 (Col Jardín Balbuena),NaN,NaN

## 6. Detección de patrones